### ISSUE TITLE
Events not firing for local API

### ISSUE THREAD

**Issue by koya-io** [JohnnyCrazy/SpotifyAPI-NET#100]
I have only looked at this API for a couple of hours but can't seem to get events to work for Console, I can pause, mute, skip, etc but cannot get events. Is this project up to date or am I doing something stupidly wrong in the example below?

```
class Program
{
    static void Main(string[] args) => new Program().Start(args);

    public SpotifyLocalAPI spotify;
    public Track currentTrack;

    public void Start(string[] args)
    {
        spotify = new SpotifyLocalAPI();

        spotify.OnTrackChange += (s, e) =>
        {
            Console.WriteLine("Track Change");
            currentTrack = e.NewTrack;
        };

        Console.ReadKey(true);
    }
}
```

**Comment by JohnnyCrazy** [comment]
Did you have a look at the [example](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Example/LocalControl.cs#L32)?

**Comment by koya-io** [comment]
Thank you so much, overlooked `spotify.Connect();` and `spotify.ListenForEvents = true;`

**Comment by JohnnyCrazy** [comment]
No problem, I will try to add the local api to the docs within this week

**Comment by koya-io** [comment]
That would be awesome.

**Comment by JohnnyCrazy** [comment]
Just added the local API docs @koya-io .
It's not very detailed but should give you some overview how things work.
