### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by vivaldinho** [JohnnyCrazy/SpotifyAPI-NET#101]
Hello
I'm using your API from VB.NET.
I only use the localapi.
The program is running well, but some times, i got the following error:
"502 Bad Gateway" from "Microsoft .NET framework". I clik the "continue" button and all continues well too.
Can anyone give me some idea about to avoid this error window?
Thanks and regards

**Comment by JohnnyCrazy** [comment]
Hi @vivaldinho ,

Could you post the stacktrace of your exception? Where does the 502 error occur?

**Comment by vivaldinho** [comment]
Hello

i don't know where it occurs... I think in more than one...
The program continues working ok after that...
any idea for avoid this kind of messages?
thanks in advance!



************** Texto de la excepción **************
System.Net.WebException: No se puede resolver el nombre remoto:
'open.spotify.com'
   en System.Net.WebClient.DownloadDataInternal(Uri address,
WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en System.Net.WebClient.DownloadString(String address)
   en SpotifyAPI.Local.RemoteHandler.GetOAuthKey()
   en SpotifyAPI.Local.RemoteHandler.Init()
   en SpotifyAPI.Local.SpotifyLocalAPI.Connect()
   en MusicHallBridge.MusicHallBridge.timerWatchReg_Tick(Object
sender, EventArgs e)
   en System.Windows.Forms.Timer.OnTick(EventArgs e)
   en System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32
msg, IntPtr wparam, IntPtr lparam)


************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MusicHallBridge
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base:
file:///C:/Users/Administrador/AppData/Local/Apps/2.0/EZLMJY8D.NDM/L5O7AT64.20K/musi..tion_9ed3098d8bf80b7f_0001.0000_fa63ac1af80f1505/MusicHallBridge.exe
----------------------------------------
Microsoft.VisualBasic
    Versión del ensamblado: 10.0.0.0
    Versión Win32: 12.0.20806.33440 built by: FX45W81RTMREL
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SpotifyAPI
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base:
file:///C:/Users/Administrador/AppData/Local/Apps/2.0/EZLMJY8D.NDM/L5O7AT64.20K/musi..tion_9ed3098d8bf80b7f_0001.0000_fa63ac1af80f1505/SpotifyAPI.DLL
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 8.0.0.0
    Versión Win32: 8.0.2.19309
    Código base:
file:///C:/Users/Administrador/AppData/Local/Apps/2.0/EZLMJY8D.NDM/L5O7AT64.20K/musi..tion_9ed3098d8bf80b7f_0001.0000_fa63ac1af80f1505/Newtonsoft.Json.DLL
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de
configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.




2016-08-28 22:40 GMT+02:00, Jonas Dellinger <notifications@github.com>:

**Comment by vivaldinho** [comment]
Hello.
the error is on file RemoteHandler.cs on line 65:

 raw = wc.DownloadString("http://open.spotify.com/token");

but remember, i only use the local api.

Regards
![error](https://cloud.githubusercontent.com/assets/20864537/18121806/8adcddd4-6f66-11e6-968d-66ac2acaf888.png)

**Comment by vivaldinho** [comment]
I got the error too on the file SpotifyLocalAPI.cs on tline 142:
 return _rh.Init();

**Comment by JimmyAppelt** [comment]
@vivaldinho check the `Inner exception` ... , and what kind of anti virus are you using ?

**Comment by vivaldinho** [comment]
Hi and thanks for your answer.
I don't use anti virus. And i try on some differents PC's.
Can you give me more info about what you mean on "inner exception", please?

**Comment by vivaldinho** [comment]
If there is a way for do not show the errors?

**Comment by JimmyAppelt** [comment]
Remember that an error is a good thing ! (So you know there is something wrong :smile: )

Inner exception most of the time show you more detail about the exception.

![3b135a0b829955d9b5f9854be8d3ea7a](https://cloud.githubusercontent.com/assets/5420393/18125212/9bccaaa2-6f75-11e6-8a7a-39ab18286604.png)

**Comment by vivaldinho** [comment]
ok.
i think the problem is i have connection lost with internet and that is the origin of the errors.
How can i avoid error messages? 
I have a process doing the same continously, then, if in one ocasion i can not connect, is not bad for me. I'll try again in few seconds...
Then, how to do not show errors?
The errors does not come from VB. They come from the cs files...

**Comment by vivaldinho** [comment]
ok, solved.
catch the error and go.

**Comment by JohnnyCrazy** [comment]
@vivaldinho 
Next time, please don't delete your posts. They could be important for other people having the same issue

Furthermore, your stacktrace was showing some Timer-Tick method. Did you connect to Spotify each Tick? Because that's wrong, just connect once and then call `_spotify.GetStatus()` each tick or use the events.

**Comment by vivaldinho** [comment]
Sorry. I deleted them thinking about to remove wast from the post... 
About the timer, of course; one connect only. Thanks.
About events, can you give me some way for use the events from VB.net?
Thanks and regards
