### ISSUE TITLE
OnTrackChange is not invoked if the new track has the same name as the previous one

### ISSUE THREAD

**Issue by parkerreno** [JohnnyCrazy/SpotifyAPI-NET#103]
While this does not happen often by any means, I have had it occur where I play two songs in a row that have the same name, but are either on different albums or by different artists (a quick look at my Spotify yielded "Closer" by Teagan and Sara and also "Closer" by The Chainsmokers).  This can result in some strange behavior (track info doesn't update, but the progress will change).

**Comment by JohnnyCrazy** [comment]
Hey,

Should be fixed by ce376a3513e46ba268bc5da8b394de991fd52f2f. I don't know why we were comparing `Name` instead of `Uri`. Release will come within the next week :)

Feel free to report further issues @parkerreno !
