### ISSUE TITLE
SpotifyWebAPI rewrite/redesign

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#104]
This issue covers the following change: Rewrite and Redesign of our Auth-Services and HTTP-Requests for the Spotify Web-API
## Auth Services Web-API

Before I go into detail, I will quickly explain how each Auth-Service is working, you can find detailed infos at their Web-API docs.
- Credentials-Auth
- ImplicitGrant-Auth
- AuthorizationCode-Auth
### Credentials-Auth

This one is fairly easy, it uses both, `clientId` and `clientSecret` and you just need to make a call to spotify with both values and you will receive your token. You can't access account data with it, so there is no user-action involved. This one would be suited for pure server-side applications while no access to user-data is needed. In the following I will ignore this Auth-Service, since it can be achieved with pure HTTP-Requests, no server required.
### ImplicitGrant-Auth

This Auth-Service is short lived and requires user-action but will also give you access to account-data. It was designed for use on sites like [jsfiddle](http://jsfiddle.com), where you have no direct HTTP-Server and only have access to some Client JS code. The token will be passed as a hash-fragment in your return url. So, technically, the HTTP-Server can't fetch this token since hash-fragments are a browser concept and are not send over the wire. You could write some client-js, fetch the token, and redirect with the token as query-parameter. But this is hacky. Also, this would require adding `localhost:XXXX` to your allowed redirect URLs inside spotify (like we currently have to do it) --> Anyone can create tokens based on your `clientId`. This currently is the case.
### AuthorizationCode-Auth

This is the perfect Auth-Service for servers. This also uses `clientId` and `clientSecret`, so this is also just a server-side Auth-Service. It requires user-action, gives access to account-data and provides a refresh token. This refresh token can be used to get a new `token` without having the user to login again. After the user granted access, he will be redirected to an URL where the token is passed via parameter --> perfect for an HTTP-Server.
## Ideas for the redesign/rewrite
- **Patch** Credentials-Auth: Make it cross-platform using `HttpClient`
- **Delete** ImplicitGrant-Auth: It's not secure enough
- **Major** AuthorizationCode-Auth: This should be our main focus, more below
- **Patch** SpotifyWebAPI: Cross-Platform, replace `WebClient` with `HttpClient`
### Cross-Platform

We should make the whole Web-API cross-platform so we can run this shit on linux servers and actually use those auth methods correctly :P.

This would require following changes:
- Replace `WebClient` with `HttpClient` (`HttpClient` doesn't provide sync methods, we need some workaround)
- Rewrite the HTTP-Server (more below)
### HTTP-Server

The HTTP-Server currently is mostly messy due to the fact I took it from stackoverflow or something similar and just edited it. It will only be used for AuthorizationCode-Auth. We need to provide enough configuration like ports, bind to specific IP-Adresses, and my favorite feature: custom HTML. Currently, a rather simple message shows that authentication was successful. It would be nice to support injecting custom HTML into the response, or, even better, a custom redirect once everything is authed. The whole API is still to design, we can either go for async-methods or events like we did before.

Regarding AuthorizationCode-Auth:
We need to abstract the actual auth process in two types:
- **Standalone HTTP-Server:**  
  This will use the HTTP-Server above. It's useful when you don't need any further HTTP stuff. You just need it once and only for authenticating.
- **Custom Handler:**  
  Let's say we already have an ASP.NET app running. It would be stupid to start another HTTP-Server. Better: Due to the abstraction, we can implement our own strategy. We could define our own route within ASP.NET, fetch the token, and call our strategy callback.

I though of something like the following:
- An interface `AuthorizationCodeStrategy`
- A class `AuthorizationCodeAuth` which has one `AuthorizationCodeStrategy`
- A class `AuthorizationCodeServer` which implements `AuthorizationCodeStrategy` and handles a HTTP-Server internally

This way, everyone can make their own strategy without us having to add a dependecy to some large framework. We could even provide strategies in some other repo with specific dependecies.

A lot of text, I hope you have some input :+1:  
This is just the first step, if we have worked out the design-idea, we will go into details and API-design, so don't get started yet :hourglass: 
@erinxocon @petrroll @JimmyAppelt

**Comment by petrroll** [comment]
BTW: HttpClient not providing sync methods is not a problem as you can simply block and wait on the async ones. 

## Sync & Async API surface

Which leads me to a question. Is supporting every API in sync and non-sync version worth it when you can easily use the async ones in a synchronous and blocking way? Yes, it's true that async versions are sometimes even an order of magnitude slower (on ideal networks, etc.) but is performance really a problem for a library such as this one? 

Removing all code for async versions (either completely or at least just providing a thin wrappers that would simply wait in a blocking matter on respective Tasks's results) would vastly simplified the project and removed a lot of code duplicity.

---

I mean you don't have to await an async method. You can simply access returned [Tasks's Result property](https://msdn.microsoft.com/cs-cz/library/dd321468(v=vs.110).aspx) and continue the same way you would if it was synchronous call.

**Comment by erinxocon** [comment]
I'm gonna bring up using Kestral again as a backend HTTP server that we can use to define our own routes and auth strategies. This can handle OAuth pretty easily and while it adds some dependencies to the app, IMO they are worth it.  We can write middleware to handle all the auth for us.  It might seem like overkill, but it would definitely make this cross platform as Kestral can be run on Windows, Linux, and macOS.

**Comment by erinxocon** [comment]
P.S.  I tried to use the local API on my mac and it worked as well, so if we get rid of some of the windows only stuff, this could truly be cross platform.  

P.S.S Fun fact, when using Spotify Connect to my Chromecast, this lib can play and pause the client which then plays and pauses the sound from the Chromecast.  I have a little setup with cassette tapes with RFID stickers on them and then a tiny c# app using this lib to control spotify.  Each cassette is a different playlist and it just magically plays on the TV.  It's one of the reasons I want it to run on linux so badly so I don't have to keep my windows machine on all the time!  Raspberry Pi Controller anybody?

**Comment by erinxocon** [comment]
https://github.com/spotify/web-api-auth-examples

**Comment by JohnnyCrazy** [comment]
@erinxocon 
Just had a look at Kestral, nope, way too much dependencies. This would add like 40 DLL-Dependencies too this project. Way too much sadly :/

@petrroll 
Good question, while I would like to keep them, maybe it would be a good change for 3.0 since they really are a lot of code duplication. We then need to implement `ConfigureAwait(false)` for sure, else UI programs will deadlock.

**Comment by petrroll** [comment]
@JohnnyCrazy Can't really see how `ConfigureAwait(false)` is relevant to it. Accessing `Result` on `Task` (which is what either we in thin wrappers or users in their code will do for sync variations) blocks and then resumes the thread that calls it. Therefore there's no continuation that could run in a different context (the computation never leaves current thread) which means `ConfigureAwait(false)` is not really applicable there.

Speaking of `ConfigureAwait`, I've made a PR that should address it: https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/106

**Comment by JohnnyCrazy** [comment]
@petrroll 
If you don't use `ConfigureAwait(false)` and access `Result` directly inside an UI Context, it will deadlock. [Here is a blog post describing the issue](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

**Comment by petrroll** [comment]
@JohnnyCrazy Ah, I misunderstood you. You're absolutely right about that. Luckily that is solved now with #106. And frankly, that was a problem even without us blocking with `Result` because it's quite understandable to assume that libraries do `ConfigureAwait(false)` and are therefore safe to call and block.

**Comment by JohnnyCrazy** [comment]
Yes, was about time we change that, dont have much experience with async stuff yet, so thanks again! :)

**Comment by JohnnyCrazy** [comment]
I just found http://nancyfx.org/  
It would add 2 DLL Dependencies `Nancy.dll` and `Nancy.Hosting.Self.dll`. It's rather small and should work very well. It's also supported on .NET Core.

@erinxocon 
Do you still want to take this job? If so, I would write some small specs tomorrow

**Comment by erinxocon** [comment]
I reckon I can take a crack at it.  I'm going to play around with Nancy tonight and see what's possible!

**Comment by erinxocon** [comment]
Alas my hopes of having it work with .NET core are gone for now 

https://github.com/NancyFx/Nancy/issues/1959#issuecomment-236744265

Looks like you have to use Kestral serving now if you want to use core as `Nancy.Hosting.Self` isn't yet .NET core compatible. Curses!

**Comment by JohnnyCrazy** [comment]
@erinxocon Aw, that's a bummer. We then may have to split the HTTP-Server Implementation into two projects, like `SpotifyAPI.Net.HTTPServer` and SpotifyAPI.NetCore.HTTPServer`. Both will reference some kind of interface of the Main-Project `SpotifyAPI` and implement their own HTTP-Server. This way, the user can decide which HTTP-Server he would like to use (`_spotify.SetHTTPServer(ISpotifyHTTPServer` or sth. like that).

That sounds like the best approach. .NET Core User will have to live with a DLL-Hell and normal .NET Users can still use the tiny NancyFX dlls.

**Comment by voltagex** [comment]
I'd definitely like a split up version - for my particular use I only need a client implementation, not the local API or the HTTP server.

**Comment by JohnnyCrazy** [comment]
@voltagex A complete split won't come in the future. The local-API is very small and runs on the same devices as the web-api (if we do convert to .NET Core standards). There was some discussion in #102, it's not worth splitting it up at all.

**Comment by erinxocon** [comment]
@JohnnyCrazy Gotcha.  How do you approach we start if we were split Nancy, from .NET core?  Looking to learn best practices with this project.

**Comment by JohnnyCrazy** [comment]
There is now a new branch `core-3` https://github.com/JohnnyCrazy/SpotifyAPI-NET/tree/core-3

I ported most of the stuff, we now only support async-methods. I may forgot to rename some of them, but I will try to do it ASAP. This will break some programs, but it's a step in the correct direction. All the HTTP-Server stuff is only for .NET 4.6.1 right now. (`#if NET461...`)

@erinxocon 
I have literally no idea what's best in that case. What about creating 2 another library projects, one for .NET 4.6.1 with Nancy and one for .NET-Standard with Kestrel? We will publish both to Nuget and people can decide if they need it and if they do, which to install.

**Comment by fotiDim** [comment]
Any update on this? Looking forward to it.

**Comment by JohnnyCrazy** [comment]
Can you try out the core-3 branch @fotDim?

**Comment by fotiDim** [comment]
@JohnnyCrazy I will try and report back. Thanks

**Comment by fotiDim** [comment]
@JohnnyCrazy I tested both _master_ and _core-3_.
On _master_ while iOS seems to work, Android has this know issue: https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/117

On _core-3_ I couldn't compile. I tried opening your sample project on a Mac using Visual Studio for Mac and on Windows using Visual Studio 2017 RC. Visual Studio 2017 gave me:

`error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. `

I also tried to create a PCL Xamarin Forms project and manually import all the files under the _Web_ directory. I got stuck here:
<img width="1137" alt="screen shot 2017-01-21 at 21 47 58" src="https://cloud.githubusercontent.com/assets/2326415/22177708/f1ffc246-e023-11e6-93d9-0965ba9aa776.png">


Is there any way you can upload a compiled version of your library so that I can skip the compilation issues for now?

**Comment by JohnnyCrazy** [comment]
Here is the compiled dll for .netstandard1.4:
[http://dl.johnnycrazy.de/spotifyapi/SpotifyAPI.dll](http://dl.johnnycrazy.de/spotifyapi/SpotifyAPI.dll)

If you need anything else compiled, just say it. I will try to get some testing done with xamarin too soon. 👍

**Comment by fotiDim** [comment]
@JohnnyCrazy I have created [a demo repo](https://github.com/fotiDim/Spotify.Forms). I have some issues:

- SpotifyAPI.Web.Auth is not available
- I had to use `_spotify.GetTrack("3Hvu1pq89D4R0lyPBoujSv").Result` isntead of `_spotify.GetTrack("3Hvu1pq89D4R0lyPBoujSv")` as I was getting:
`Cannot implicitly convert type System.Threading.Tasks.Task<SpotifyAPI.Web.Models.FullTrack>' to SpotifyAPI.Web.Models.FullTrack' (CS0029) (SpotifyForms)`
- On Android `_spotify.GetTrack("3Hvu1pq89D4R0lyPBoujSv").Result` seems to hang my program. Code execution does not continue.

iOS seems to be working. I will continue with testing.

**Comment by JohnnyCrazy** [comment]
@fotiDim did you try `await _spotify.GetTrack`? All methods are mostly asynchronous

**Comment by fotiDim** [comment]
@JohnnyCrazy yes I did. It gives me this:
`Error CS4033: The `await' operator can only be used when its containing method is marked with the `async' modifier (CS4033) (SpotifyForms)`

Btw I am testing on VS for Mac.

**Comment by petrroll** [comment]
@fotiDim Well yes, of course. You can only use await from async functions. More about async/await: https://msdn.microsoft.com/en-us/library/mt674882.aspx

If you don't want to deal with all that (it's a shame, async/await is a very nice paradigm) you can always just access the `Result` property of the task that gets returned from an async function. Doing that will synchronously wait almost the same way calling a normal synchronous function would. 

It is, however, still weird that accessing `_spotify.GetTrack("3Hvu1pq89D4R0lyPBoujSv").Result` deadlocks. There has to be some sort of problem with the implementation that allows it to wait indefinitely. 

Are you sure the very same code works on iOS / Windows platforms? Also, do we have timeouts for situations where the download `Task` takes too long  @JohnnyCrazy  ?

**Comment by fotiDim** [comment]
Please ignore what I wrote above about `await`. It was a dummy mistake of mine. With `await`, Android works as well. However it is odd why `.Result` does not work..

What about "SpotifyAPI.Web.Auth"? Is it deprecated?

**Comment by petrroll** [comment]
@fotiDim That's still weird, `.Result` shouldn't deadlock... The only possible reason for that happening I can think of is that we forgot to put `.ConfigureAwait(false)` somewhere along the way and it deadlocks because of a captured sync. context.

**Comment by JohnnyCrazy** [comment]
`SpotifyAPI.Web.Auth` is currently commented out. `ClientCredentialsAuth` needs to be rewritten with `HTTPClient` and the other 2 out 3 auth-methods require a HTTP-Server to get the response back from spotify. Currently, I couldn't decide with which HTTP-Server lib we will go, but I will probably outsource this so different HTTP-Server libs can be used. (Something like `SpotifyAPI-ASP` and `SpotifyAPI-Nancy`).

This way, we can just plug in different HTTP-Providers:
```c#
_spotifyAuth = new AutorizationCodeAuth();
_spotifyAuth.Use(new SpotifyAPI.Nancy.HTTPProvider("localhost", 8080))

_spotifyAuth.StartAuth();
```

However, since you're designing a client-side app, you should either use their own android-auth library, or some server-backend which handles authentication.

**Comment by fotiDim** [comment]
I already run a native iOS app using the official iOS SDK and I have to maintain a Token Swap Service like [this](https://github.com/simontaen/SpotifyTokenSwap). I don't mind that. It is basically using the Authorization Code flow.

I would like to support UWP and perhaps Tizen so using the official SDKs (which exist only for iOS and Android) is not an option. What would it take to include Authorization Code flow in your lib?

**Comment by fotiDim** [comment]
@JohnnyCrazy any update on this?

**Comment by Zasam** [comment]
Is there any update on the issue that the SpotifyAPI doesn't work on Xamarin android? 
Or is there any possible work around for this? 

I always get this error and I can't find the point where the Spotify Api implements System.Drawing.
I only want to use the SpotifyWebApi and the ImplicitGrantAuthentication.
I also tried to convert it into a android library but I'll always get this error.

Thanks for any help in advance.

**Comment by iss0** [comment]
Hey guys,

I've made a pr #223. Have a look and tell me if it is helpful in any way. Would like to help refactoring for .net standard.

**Comment by JohnnyCrazy** [comment]
@iss0 wow, good stuff. Do you have some info about backwards compatibility? This is an important point for me, since I don't want to force some big change for library users.

**Comment by Zasam** [comment]
@iss0 @JohnnyCrazy  Sorry guys for my beginner question, but yet it is not possible to create a simple xamarin android app with the Web Api, or am I wrong? 
Thanks for any answer in advance.

**Comment by JohnnyCrazy** [comment]
Most of the stuff has been implemented

see #276 for more infos
