### ISSUE TITLE
Short question

### ISSUE THREAD

**Issue by D3thw0lf** [JohnnyCrazy/SpotifyAPI-NET#105]
Hey! Thanks for doing this great local api ^^

I've a short question: is there a way to say for example: "your songrequest 'name of song' has been added to list" or whatever? So if string contains spotify:track:whatever returns to 'name of song'?

Sorry for my bad english. Would be cool if you know a possible solution for me. :3

Thanks in advance. <3

**Comment by D3thw0lf** [comment]
aww shit...I've seen there's an example in your Wiki. But it's only for webbased api. :(

**Comment by JimmyAppelt** [comment]
![9b727904f6427a6429f57e9e9525ba80](https://cloud.githubusercontent.com/assets/5420393/18276955/0f90127c-744d-11e6-906c-73a1eef6a866.png)
