### ISSUE TITLE
After last Spotify Update does not work

### ISSUE THREAD

**Issue by vivaldinho** [JohnnyCrazy/SpotifyAPI-NET#108]
Does anybody have problems after the last version update?
I have now 1.0.37.150.gad02a02e version and i can't connect.
Regards

**Comment by JimmyAppelt** [comment]
* Spotify: 1.0.37.150.gad02a02e
* API: SpotifyAPI-NET 2.11.0

Working fine here ...

**Comment by JohnnyCrazy** [comment]
Hi,

I just published version 2.12.0, please check if this fixes your problem. It seems like they removed support for HTTP on Port `4380` (HTTP and `4381` still seem to work). We are now using HTTPS and Port 4371 which should work with the latest spotify version. Tested on windows (and linux, using JS).

@vivaldinho

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy how come `2.11.0` is still working on my machine then ? *(with 1.0.37.150.gad02a02e)*

**Comment by JohnnyCrazy** [comment]
@JimmyAppelt 
Good question, `http://spotify.spotilocal.com:4380/remote/status.json` results in a `Not Found` response for me. Is this query still working on your machine?

**Comment by Gruhlum** [comment]
I had the same Issue. Updating to 2.12 fixed the problem, before that I had 2.9.

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy `http://spotify.spotilocal.com:4380/remote/status.json` results in a `Not Found` correct. 
Still able to connect with `2.11.0`

**Comment by JohnnyCrazy** [comment]
Weird, but since 2.12.0 is out now, we can close this :+1:

**Comment by JimmyAppelt** [comment]
Nothing weird :) 

`2.11.0` uses `https://` and port `4371`

**Comment by vivaldinho** [comment]
ok.
with 2.12.0 all is ok.
thanks

**Comment by JimmyAppelt** [comment]
yes discard my reply, i already fetched with master before. That's why it was working for me :)
