### ISSUE TITLE
VB.Net

### ISSUE THREAD

**Issue by ItsCoding** [JohnnyCrazy/SpotifyAPI-NET#11]
Hi i tryed to use the api last night and if i want to connect to Spotify it always fails(the wihle is always trying)
Source :

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        If SpotifyAPI.SpotifyLocalAPI.SpotifyLocalAPIClass.IsSpotifyRunning = True Then
            MsgBox("Spotify Leuft :D")
        Else
            spotify.RunSpotify()
            Snooze(5000)
            MsgBox("Jetzt leuft Spotify :D")
        End If
        If SpotifyAPI.SpotifyLocalAPI.SpotifyLocalAPIClass.IsSpotifyWebHelperRunning = True Then
            MsgBox("Webhelper geht!")
        Else
            MsgBox("Webhelper Startet")
            spotify.RunSpotifyWebHelper()
            Snooze(5000)
        End If
        spotify.Connect()

        Dim retry As Boolean = True
        While retry = True
            If spotify.Connect = True Then
                retry = False
                MsgBox("jaaaaaaa")
            Else

                retry = True
            End If
        End While
        spotify.Update()
    End Sub
    Private Sub Snooze(ByVal seconds As Integer)
        For i As Integer = 0 To seconds * 100
            Application.DoEvents()
            System.Threading.Thread.Sleep(10)
        Next
    End Sub

    Private Sub ButtonBlue1_Click(sender As Object, e As EventArgs) Handles ButtonBlue1.Click
        If spotify.Connect = True Then
            TxtBox1.Text = mh.IsPlaying
            eh.ListenForEvents(True)

        Else
            MsgBox("am Arsch!")
        End If
    End Sub

    Private Sub ButtonBlue2_Click(sender As Object, e As EventArgs) Handles ButtonBlue2.Click
        mh.Pause()
    End Sub

    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        spotify.Connect()
    End Sub

**Comment by JohnnyCrazy** [comment]
Did you try running the example provided in the repo?
