### ISSUE TITLE
AuthorizationCodeAuth response token is in response.error instead of response.code

### ISSUE THREAD

**Issue by JackRyder** [JohnnyCrazy/SpotifyAPI-NET#110]
when you're gaining authentication using AutorizationCodeAuth, in the OnResponseReceivedEvent event, when you successfully gain an access code it's saved in the error variable, instead of the code variable.

Just a heads up, probably an easy fix, right?

**Comment by JohnnyCrazy** [comment]
I don't quite follow, the following works for me:

![alt](http://i.imgur.com/3o9pYAE.png)

**Comment by JackRyder** [comment]
I was following an old tutorial of your API, nevermind! :P
