### ISSUE TITLE
When would SpotifyLocalAPI.Connect() return false?

### ISSUE THREAD

**Issue by JackRyder** [JohnnyCrazy/SpotifyAPI-NET#111]
Hey!

Followed your newer guides and managed to get the web API stuff working, although for some reason connecting to the local process using .Connect() is returning false on both my machine (windows 10) and a windows server I use (running 2012 R2). Wondering what the reasons would be for it returning false!

Cheers,
Jack

**Comment by JimmyAppelt** [comment]
@JackRyder what version of the lib are you using ?

**Comment by JackRyder** [comment]
Just updated, didn't know a new verison was out! Thanks :)
