### ISSUE TITLE
No way to grab collaborative playlists 

### ISSUE THREAD

**Issue by JackRyder** [JohnnyCrazy/SpotifyAPI-NET#112]
Hey,

I've noticed that there's no way of grabbing a users playlists that they collaborate with, even though there's an option for this via scope on the spotify web API.

Is there anything built for this or will I need to query it myself?

Cheers

**Comment by JohnnyCrazy** [comment]
We just have support for all endpoints listed [here](https://developer.spotify.com/web-api/endpoint-reference/). You will propably have to filter them out yourself

**Comment by JackRyder** [comment]
Yes, but it seems like some scopes are missing from your enums, such as "playlist-read-collaborative". :)
