### ISSUE TITLE
Cfid response is empty

### ISSUE THREAD

**Issue by Tunfisch** [JohnnyCrazy/SpotifyAPI-NET#115]
Hi, when i use the library the cfid key is empty. The same problem occurs on my notebook.
![unbenannt](https://cloud.githubusercontent.com/assets/6475403/18682985/b1c0eaae-7f6e-11e6-8a3d-f9a752c07a74.png)

Thanks for help

**Comment by Tunfisch** [comment]
Additional i get this Exception. The Exception is in german and means.
the remote name could not be resolved
![unbenannt](https://cloud.githubusercontent.com/assets/6475403/18683326/0bacbe70-7f70-11e6-8489-be614af1736f.png)

**Comment by JohnnyCrazy** [comment]
Is the web-helper running? `SpotifyLocalAPI.IsSpotifyWebHelperRunning()`

**Comment by Tunfisch** [comment]
Yes the Webhelper is running
![unbenannt](https://cloud.githubusercontent.com/assets/6475403/18684402/57b959f0-7f74-11e6-8c8a-9efe85f5bd3c.png)

**Comment by JohnnyCrazy** [comment]
Are you on the latest version? There was an update last week

**Comment by Tunfisch** [comment]
yes i found your library today, so i have already the newest version.  My System cant resolve spotilocal.com but i dont know why. Its weird because i have already tested this on my notebook too.

**Comment by JohnnyCrazy** [comment]
Well, the Spotify helper should register this domain in your system. Do you have any anti-virus software installed? Or maybe some firewall software? Hard to debug since this URL is mandatory for all requests :P

**Comment by Tunfisch** [comment]
I have just closed all my applications that can collide with the program. I dont have any anti virus software on my developing machine and i already tried to shutdown windows firewall :(. Yesterday another api worked fine, today even this another api is not working at all.

**Comment by domialex** [comment]
Same thing here, I get "The remote certificate is invalid according to the validation procedure.".

**Comment by Tunfisch** [comment]
Cool thanks domialex this is working for me, unfornately it seems that i need change spotifyapi.spotilocal.com to 127.0.0.1 because my system doesnt resolve the host name properly.

`public const string Host = "SpotifyAPI.spotilocal.com";`
`public const string Host = "127.0.0.1";`

**Comment by domialex** [comment]
Yes, same here, it's always been like this in my case.

**Comment by JohnnyCrazy** [comment]
I guess we can change the Host and add the small SSL Hack. The Hack is probably needed due an self signed certificate.

**Comment by JimmyAppelt** [comment]
Is indeed strange, @domialex @Tunfisch what version of spotify do you guys have installed ?

**Comment by JohnnyCrazy** [comment]
Fixed by 281b684f5f80a14ed2b440ed4b0c514c1f630eec

Please reopen if you encounter similiar issues
