### ISSUE TITLE
Ads bug

### ISSUE THREAD

**Issue by Persi2** [JohnnyCrazy/SpotifyAPI-NET#116]
It seems that when ads occure and events are enabled, the local api stops working.
I don't know why but I suspect it is related with the fact that TrackRessource is null with ads.

**Comment by JohnnyCrazy** [comment]
Mh, this could be because of ce376a3513e46ba268bc5da8b394de991fd52f2f

Gonna test this tomorrow

**Comment by Persi2** [comment]
I can confirm it works. The name must be used if it is an ad.

**Comment by JohnnyCrazy** [comment]
Alright, I can push it this evening, but I'm open for PRs, should be a simple `if track.IsAd()` check

**Comment by JohnnyCrazy** [comment]
I sadly couldn't reproduce the crash.
When an ad is running, `TrackResource` is null, but since we use `TrackResource?`, it will just ignore it. Comparing `Name` sadly won't work, since the whole `TrackResource` is null.

**Comment by Persi2** [comment]
I retried with URI and it worked... Dont know why it wasn't working before.
