### ISSUE TITLE
GetAlbumArt doesn't do anything?

### ISSUE THREAD

**Issue by XceSx6** [JohnnyCrazy/SpotifyAPI-NET#118]
Is it just here, or do these functions just not return anything?
            bigAlbumPicture.Image = await track.GetAlbumArtAsync(AlbumArtSize.Size640);
            smallAlbumPicture.Image = await track.GetAlbumArtAsync(AlbumArtSize.Size160);
How do i get album art from Spotify?

**Comment by JimmyAppelt** [comment]
`await track.GetAlbumArtAsync(AlbumArtSize.Size160);` will get you the track album

Perhaps you want to share some more example code of what you have, since the function returns the album art just fine.

Is everything else working for you ? Like getting the track info ?

**Comment by XceSx6** [comment]
Well, i just re-downloaded the source code, ran the Example again.
And it doesn't show album art.. If i go through the debugger the AlbumResource.Uri contains "TODO", not an actual Uri.
I had to change the function to get the AlbumArt for the track:
In Track.cs:

Before:
            if (AlbumResource.Uri == null || !AlbumResource.Uri.Contains("spotify:album:") || AlbumResource.Uri.Contains("spotify:album:0000000000000000000000"))
                return "";
After:
            if (TrackResource.Uri == null || !TrackResource.Uri.Contains("spotify:track:") || TrackResource.Uri.Contains("spotify:track:0000000000000000000000"))
                return "";

Before:
raw = wc.DownloadString("http://open.spotify.com/album/" + AlbumResource.Uri.Split(new[] { ":" }, StringSplitOptions.None)[2]);
After:
raw = wc.DownloadString("http://open.spotify.com/track/" + TrackResource.Uri.Split(new[] { ":" }, StringSplitOptions.None)[2]);

Thats all, now it works fine.

**Comment by JimmyAppelt** [comment]
Could you specify what version of spotify you have ?

`http://open.spotify.com/track/2leURyZTNszWf0NOrbWOW4` doesn't exist when i test *(i'm on 1.0.38.171.g5e1cd7b2)*

**Comment by XceSx6** [comment]
I'm on 1.0.38.171.g5e1cd7b2 as well o_O

**Comment by JimmyAppelt** [comment]
![64299db79a0642dff5c5dc3f25542902](https://cloud.githubusercontent.com/assets/5420393/18987815/cfd90322-8703-11e6-9c45-c2538e70bc57.png)

Still comes in how it should ...

**Comment by XceSx6** [comment]
![huh](https://cloud.githubusercontent.com/assets/17053283/18987995/e746a194-8704-11e6-9c30-2c26b5256133.png)

Strange, i get this.. ofc stops at the first check in GetAlbumArtUrl

**Comment by JohnnyCrazy** [comment]
Is this a local track? A file on your pc?

**Comment by JohnnyCrazy** [comment]
I just tested this with spotify:album:50SGucGvMan1kbLqyuaEr6, works fine here.

**Comment by XceSx6** [comment]
No, not a local track. Freshly installed Spotify, fresh account.. played a song from "Infected Mushroom"
Strange :P

**Comment by JohnnyCrazy** [comment]
Most times this is related to some ISP's not being able to contact Spotify's image-CDN.
