### ISSUE TITLE
UWP and offline

### ISSUE THREAD

**Issue by MannusEtten** [JohnnyCrazy/SpotifyAPI-NET#119]
is the library ready to be used in an UWP (universal windows app) ?

you can play songs with the API, also in offline mode so you download the songs first and play them?

**Comment by JohnnyCrazy** [comment]
Hi, you can try out the `core-3` branch, which supports .NET Standard (and so .NET Core and .NET Framework)

The library only interacts with the spotify-client. If the client downloaded the tracks, they should be playable.
