### ISSUE TITLE
start playing track with timestamp

### ISSUE THREAD

**Issue by oimel** [JohnnyCrazy/SpotifyAPI-NET#12]
Hello,
Is it possible to play a song and specify a time where it starts?
spotify:track:1DfGPEHxTYeaJpiNA4xUb5#0:23
I can open this url in Spotify and the song starts at 0:23. When I pass this url through PlayURL() nothing happens.

Thank you.

**Comment by JohnnyCrazy** [comment]
No this is currently not possible :/
Maybe spotify's local API will support it sometime, but I don't think so.

**Comment by aherrick** [comment]
Is this still not the case? Are there any work arounds?
