### ISSUE TITLE
SpotifyAPI-NET behind proxy

### ISSUE THREAD

**Issue by ersensen** [JohnnyCrazy/SpotifyAPI-NET#120]
Hi,

We injected this nice library into our app via nuget. The app is running behind the proxy. So we got 
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ..." errors;

Is there a way not to set the proxy to null? Or do we have to get the source code into our project and remove the "Proxy = null;"s?

Thanks

**Comment by JimmyAppelt** [comment]
@ersensen What kind of app? Winforms, WPF, ASP.NET ?

You have to load in the source and build the library yourself to change the Proxy setting.

**Comment by ersensen** [comment]
hi @JimmyAppelt

its an asp.net web api app. it would be nice to have a setting for the proxy be enabled or not. anyway, it seems we will build the source.

**Comment by JimmyAppelt** [comment]
Yes it's a good idea to expose a property for that

**Comment by ersensen** [comment]
hi @JimmyAppelt,

For now we will pull the source code in. If you plan to add this feature we can add the package via nuget when its ready.

**Comment by JimmyAppelt** [comment]
Ok @ersensen, the project is open for Pull Requests, feel free to do so. @JohnnyCrazy wouldn't mind, I'm sure.

On the other hand, I'm very interested to know if setting a proxy actually solves your issue. Hope you give an update later on.

**Comment by JohnnyCrazy** [comment]
Hi,

Yes, the `Proxy = null`s needs to be removed. However, the .NET-Standard branch already has a fix for this by using `HTTPClient`. However, I don't know when I will have time to finish up on the `core-3` branch.

I guess your best option for now is running a custom version and update once 3.0 (.NET Standard release) is out

**Comment by ersensen** [comment]
Thanks @JohnnyCrazy we will go with custom version until the update becomes ready.

Hi @JimmyAppelt, yes when we comment "Proxy = null"s the WebClient.Proxy property is automatically set to the companies default proxy, then it works.

**Comment by JohnnyCrazy** [comment]
Removed proxy settings in [2.14.0](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.14.0)
