### ISSUE TITLE
Howto implement in C++

### ISSUE THREAD

**Issue by figgelz** [JohnnyCrazy/SpotifyAPI-NET#122]
Can I have an explementation of how to implement this api into c++ code? Leading me into the right direction would be enough. The internet is full of ways to do this, but its hard to filter wich would be the best. 
I've downloaded it already via NuGet, so i'm stuck with the DLL at the moment.

**Comment by JohnnyCrazy** [comment]
Hi, if you have some knowledge in c++, the code should be easy to understand. Have a look into the `Local`/`Web` folder located inside the `SpotifyAPI`-folder. 

If you have specific questions regarding the c# api, feel free to open another issue, however I can't give support for other languages due lack of time.

Some articles:
https://medium.com/@bengreenier/hijacking-spotify-web-control-5014b0a1a360#.pexbz3ftz
http://cgbystrom.com/articles/deconstructing-spotifys-builtin-http-server/
