### ISSUE TITLE
Events stop firing after a while

### ISSUE THREAD

**Issue by JackRyder** [JohnnyCrazy/SpotifyAPI-NET#123]
Hey,

I have a small issue with the SpotifyLocalAPI, where after a while the OnTrackTimeChange and OnTrackChange event will stop firing, although this can be fixed by readding the handlers to the events via the code (such as a button.)

Just wondering whether this is something that has been documented and i've mixed, since i've seen there is a sync property for the local API object.

Cheers,
Jack

**Comment by vivaldinho** [comment]
With the new version of spotify something is changed. After some minutes running, my software gives problems...

**Comment by JimmyAppelt** [comment]
>  After some minutes running, my software gives problems.

What kind of problems ... ? Same as OP ?

**Comment by JimmyAppelt** [comment]
After 5 hours of testing with versions `2.12.0`  and `1.0.43.123.g80176796` I'm unable to confirm this behavior.

**Comment by JohnnyCrazy** [comment]
Can't reproduce this, still working.
