### ISSUE TITLE
Get all the artists from the song

### ISSUE THREAD

**Issue by MagicLegend** [JohnnyCrazy/SpotifyAPI-NET#125]
Hi,

I need a way to get all the artists from a song, which is currently not possible according to the documentation. Is this something that can be put in?

Thanks.

MagicLegend

**Comment by JohnnyCrazy** [comment]
https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyWebAPI/tracks/#gettrack
and
https://developer.spotify.com/web-api/object-model/#track-object-full

**Comment by MagicLegend** [comment]
I'm sorry! I've only looked at the local API (which I'm using right now), not the web one. Guess I have some more work to do :). Thanks for your time!
