### ISSUE TITLE
[Request] Be able to set the song time

### ISSUE THREAD

**Issue by MagicLegend** [JohnnyCrazy/SpotifyAPI-NET#126]
Hi there,

For my application it would be a nice bonus if it can programmatically set the time of the song. Is this something that is possible to be done via the API?

Thank you in advance.

MagicLegend

**Comment by JimmyAppelt** [comment]
Please elaborate on >programmatically set the time of the song

**Comment by JohnnyCrazy** [comment]
Try setting the track time via a hash representing the seconds/minutes.

```csharp
// Will start at 0:10
_spotify.PlayURL("spotify:track:0MYAEVl5ls7GGLT1XbHKnl%230:10");
```

The `%23` is basically an encoded `#`. (We currently don't encode the call, should be changed in the future)

**Comment by MagicLegend** [comment]
@JimmyAppelt That I can tell Spotify to start playing at a specific time in the song.

@JohnnyCrazy Thank you for your response (and for the amazing API :))! I'll give it a go tomorrow!
