### ISSUE TITLE
Visual basic code

### ISSUE THREAD

**Issue by DanDeagle** [JohnnyCrazy/SpotifyAPI-NET#127]
Hi there, I am trying to hack together this API to make a "Jukebox" type application that runs Spotify for the music

My problem so far is I'm trying to make a search on my form, but look at the code below, the script does not return any results (I know the results are not output in the code) but my code crashes because of NULL

Please help! thank you

    Imports SpotifyAPI.Local
    Imports SpotifyAPI.Local.Models
    Imports SpotifyAPI.Local.Enums
    Imports SpotifyAPI.Web
    Imports SpotifyAPI.Web.Auth
    Imports SpotifyAPI.Web.Enums
    Imports SpotifyAPI.Web.Models
    Public Class Auth
        Public Shared Async Sub Main()
            Dim _spotify As New SpotifyAPI.Web.SpotifyWebAPI

            Dim webApiFactory As New WebAPIFactory("http://localhost", 8000, "XXXXXX", Scope.UserReadPrivate Or Scope.UserReadEmail Or Scope.PlaylistReadPrivate Or Scope.UserLibraryRead Or Scope.UserReadPrivate Or Scope.UserFollowRead Or Scope.UserReadBirthdate Or Scope.UserTopRead)
            Try
                _spotify = Await webApiFactory.GetWebApi()
            Catch ex As Exception
                MessageBox.Show(ex.Message)
            End Try

            If _spotify Is Nothing Then
                Return
            End If
        End Sub
    End Class
    Public Class frm_search
        Dim Actions As New SpotifyLocalAPI
        Dim track As New SpotifyAPI.Local.Models.Track
        Public Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            Dim _spotify As New SpotifyAPI.Web.SpotifyWebAPI
            Dim item As SearchItem = _spotify.SearchItems("roadhouse+blues", SearchType.Album, SearchType.Playlist)
        End Sub
    End Class

**Comment by JohnnyCrazy** [comment]
I can't give support for VB.NET code, but as @andseeb suggested, try filling in your `client_id`
