### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by DanDeagle** [JohnnyCrazy/SpotifyAPI-NET#128]
I keep getting this error:

> INVALID_CLIENT: Invalid redirect URI

my URI on the Spotify Developer website is set to 

> http://localhost

Please help?

**Comment by andseeb** [comment]
If your local server is running on a port other than 80, you need to include the port in the URI that is whitelisted for your application on the Spotify Developer website. Exmaple for port 8000:

> http://localhost:8000
