### ISSUE TITLE
System.NullReferenceException @ GetStatus()

### ISSUE THREAD

**Issue by M4sterZer0** [JohnnyCrazy/SpotifyAPI-NET#134]
Hi,
I get a System.NullReferenceException if I call the GetStatus() function.
![IScreen](https://i.imgur.com/QCyQpCP.png)

**Comment by jipjan** [comment]
Do you make sure spotify is running and connected before requesting the status?

You can do this with `if (Spotify.Connect()) { }`

**Comment by JohnnyCrazy** [comment]
Mh, I can confirm something isn't working correctly ATM, it seems like spotify changed something with OAuth tokens, gonna need some time to find out what tho.

And btw, your `status` is null because it wasn't assigned yet, put a breakpoint after the `GetStatus()`

**Comment by M4sterZer0** [comment]
@jipjan Yes, I check it before I call the function.
Let's wait for a API fix. :)

**Comment by jipjan** [comment]
But what is wrong with the OAuth? I'm using the API at this very moment and don't have any issues..

**Comment by M4sterZer0** [comment]
Do you have updated your Spotify (client)?

**Comment by JohnnyCrazy** [comment]
Can you guys please test the following endpoint: "https://open.spotify.com/token"
Do you receive a string with "faketoken" at the end? It seems it delivers fake tokens currently (at least for me)

**Comment by jipjan** [comment]
Don't know, my version is 1.0.50.41368.gbd68dbef

**Comment by JohnnyCrazy** [comment]
And please test it within the API and with a browser. You can put a breakpoint in the `RemoteHandler.cs` constructor

**Comment by jipjan** [comment]
nope, it's working, got: '{"t":"NAowChgKB1Nwb3RpZnkSABoGmAEByAEBJfgbwlgSFM7t94j8ebJU4H0kGoaT_uEbk_O-"}'

**Comment by M4sterZer0** [comment]
@jipjan I've the same version. hm.
@JohnnyCrazy No, I get this result:

> {"t":"NAowChgKB1Nw*************xO5DUWTM7kG"}

**Comment by JohnnyCrazy** [comment]
Are those values gathered by the C# API client? Maybe just an issue on my side...

**Comment by jipjan** [comment]
I'm using the compiled .dll in my project atm, so it's kinda hard for me to test this. As far as I can see everything is working fine in my solution.

**Comment by M4sterZer0** [comment]
So, I've created a new console application and installed this api with nuget.

Result:
![Screenshot](https://i.imgur.com/HtdfBZJ.png)

**Comment by xcrow** [comment]
Adding a "user-agent" Header in GetOAuthKey() method's WebClient worked for me. 
Now it is returning token without the "faketoken" string attached at the end.

**Comment by henningms** [comment]
Can confirm. Adding a User-Agent header in the GetOAuthKey will do the trick to get the local api working again.

**Comment by JohnnyCrazy** [comment]
Will be published as a Hotfix in 2.13.1 in the next hours

**Comment by ryandel13** [comment]
Hello, Maybe this issue is open again.
From the endpoint "https://open.spotify.com/token" I only get a token with "faketoken" at the end. I already tried to update the User-Agent to "Spotify (1.0.86.337.ga8d5cef9)".

Any Ideas? Struggling with this issue since a couple of days...

**Comment by JohnnyCrazy** [comment]
A simple search would help in a lot of times... #254
