### ISSUE TITLE
Unable to save Album Art.

### ISSUE THREAD

**Issue by PFCKrutonium** [JohnnyCrazy/SpotifyAPI-NET#137]
```
var pic = Path.GetTempFileName();
status.Track.GetAlbumArt(SpotifyAPI.Local.Enums.AlbumArtSize.Size320).Save(pic);
```

This code seems to always fail with a generic gdi+ error, regardless of AlbumArtSize or anything else I can think of - I can get the name of the track, artists, etc. Am I doing something wrong or is it broken?

**Comment by JohnnyCrazy** [comment]
You need to make a copy first

http://stackoverflow.com/questions/15862810/a-generic-error-occurred-in-gdi-in-bitmap-save-method
