### ISSUE TITLE
Get the User's Currently Playing Track

### ISSUE THREAD

**Issue by gabernardone** [JohnnyCrazy/SpotifyAPI-NET#141]
Spotify is now making available in the api the music that the user is currently listening to.

Https://developer.spotify.com/web-api/get-the-users-currently-playing-track/

It would be nice to include in the project

**Comment by JohnnyCrazy** [comment]
Yes, they are coming but no ETA yet. PRs welcome.

**Comment by JohnnyCrazy** [comment]
Will come in a new release tomorrow 👍

**Comment by JohnnyCrazy** [comment]
Endpoints are implemented in [2.14.0](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.14.0)
