### ISSUE TITLE
Doing auth in hidden browser

### ISSUE THREAD

**Issue by JackRyder** [JohnnyCrazy/SpotifyAPI-NET#146]
Hey, this is more of a discussion than anything, but i'm just wondering whether there's a way to hide the tab/window that opens when you require authorisation, since I have an office spotify player that requires authorisation multiple times throughout the day, there is a flicker on the screen, which then resolves itself, but is still noticable.

Is there a way to select for it to use a WebBrowser for example, rather than just the default web browser?

Thanks.

**Comment by JohnnyCrazy** [comment]
I would rather write a small backend server which does the auth handling via `AuthorizationCode`-Auth flow. With a hidden browser, the session cookie will be invalid at some point.

**Comment by JackRyder** [comment]
What about having a WebBrowser control handling the requests instead? Surely that should behave the same way as the current browser behaves anyway

**Comment by JohnnyCrazy** [comment]
You can just try it by calling `GetUri()` and pass that to the WeBrowser control. Report back if you find anything 👍

**Comment by JohnnyCrazy** [comment]
I'm gonna close this issue since it's more of a discussion, which suits best in our new [gitter channel](https://gitter.im/SpotifyAPI-NET/Lobby), so please feel free to write your results :)
