### ISSUE TITLE
New Spotify-Beta

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#15]
There is a new Spotify-Client ready for beta testing.

You can download it [here](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Welcome-to-the-Desktop-Beta/td-p/932803)

@gusper seems like it really got better now! Maybe there are also some new hidden features within the Spotify API, who knows? :joy:

**Comment by gusper** [comment]
Yep, so far really an improvement. Haven't searched for new features yet though. :)

**Comment by JohnnyCrazy** [comment]
Yea, didn't have any "timeouts" yet, the test-application is running for nearly 2 hours now without any problem

**Comment by gusper** [comment]
Any plans to update the NuGet package version with the latest soon?

**Comment by JohnnyCrazy** [comment]
Yea, why not, give me a minute

**Comment by gusper** [comment]
Excellent. Thanks.

**Comment by JohnnyCrazy** [comment]
Spotify Beta is now over. Will remove the beta-implementation once I get the rewrite done.
