### ISSUE TITLE
[Auth] Unable to use custom callback without server port parameter

### ISSUE THREAD

**Issue by JimmyAppelt** [JohnnyCrazy/SpotifyAPI-NET#150]
What do you think about merging the property's `redirectUrl` with the `listeningPort` on the creation of the WebAPIFactory ?

I'm unable to use a custom URL without port
 ```C#
WebAPIFactory webApiFactory = new WebAPIFactory(
                "http://mydomain.com/spotify/oauth:80",
                "26d287105e31491889f3cd293d85bfea",
                Scope.UserReadPrivate | Scope.UserReadEmail | Scope.PlaylistReadPrivate | Scope.UserLibraryRead |
                Scope.UserReadPrivate | Scope.UserFollowRead | Scope.UserReadBirthdate | Scope.UserTopRead | Scope.PlaylistReadCollaborative |
                Scope.UserReadRecentlyPlayed | Scope.UserReadPlaybackState | Scope.UserModifyPlaybackState);
```

Could be used like this then, as it doesn't require to use a listening port parameter

 ```C#
WebAPIFactory webApiFactory = new WebAPIFactory(
                "http://mydomain.com/spotify/oauth",
                "26d287105e31491889f3cd293d85bfea",
                Scope.UserReadPrivate | Scope.UserReadEmail | Scope.PlaylistReadPrivate | Scope.UserLibraryRead |
                Scope.UserReadPrivate | Scope.UserFollowRead | Scope.UserReadBirthdate | Scope.UserTopRead | Scope.PlaylistReadCollaborative |
                Scope.UserReadRecentlyPlayed | Scope.UserReadPlaybackState | Scope.UserModifyPlaybackState);
```

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/Auth/WebApiFactory.cs#L24

**Comment by JohnnyCrazy** [comment]
So, on which port should it listen on in your second example? 80?

**Comment by JimmyAppelt** [comment]
Is it not possible to redirect to a url without listening port ? Like redirecting it directly to http://mydomain.com/spotify/oauth

**Comment by JimmyAppelt** [comment]
But ether way, it's just a proposal. I'll have to use the `AutorizationCodeAuth `anyway myself, since the `ImplicitGrantAuth` will not be able to refresh the token.

**Comment by JohnnyCrazy** [comment]
`http://mydomain.com/spotify/oauth` should be treated the same as `http://mydomain.com/spotify/oauth:80`. Is there anything wrong with using

```
WebAPIFactory webApiFactory = new WebAPIFactory(
               "http://mydomain.com/spotify/oauth",
                80
               "26d287105e31491889f3cd293d85bfea",
               Scope.UserReadPrivate | Scope.UserReadEmail | Scope.PlaylistReadPrivate | Scope.UserLibraryRead |
               Scope.UserReadPrivate | Scope.UserFollowRead | Scope.UserReadBirthdate | Scope.UserTopRead | Scope.PlaylistReadCollaborative |
               Scope.UserReadRecentlyPlayed | Scope.UserReadPlaybackState | Scope.UserModifyPlaybackState);
```

Or is some stuff not working then?

**Comment by JimmyAppelt** [comment]
Indeed I tried that (technically it should work fine since 80 is the default http port, but for some reason the callback url is not working.

Perhaps it's my .htaccess file that's messing with the redirect.

http://jimmyappelt.be/spotify/oauth/
http://jimmyappelt.be/spotify/oauth:80

**Comment by JohnnyCrazy** [comment]
Ohhhh wait, the schema is simply wrong. It has to be `http://jimmyappelt.be:80/spotify/oauth`. Guess we didn't think of HTTP Paths back when we did the factory.

Maybe we can use some internal `URI` class to generate the correct one, including the path and port

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy oww of coarse, how did I overlooked that :) Perhaps the `UriBuilder` is a good option.
