### ISSUE TITLE
API not working!!!

### ISSUE THREAD

**Issue by Deitchy** [JohnnyCrazy/SpotifyAPI-NET#154]
I have used this API and built a project on it, and it stopped working!!
i also sent you a message on facebook, please contact me!

**Comment by JimmyAppelt** [comment]
Is it really necessary to post `6 x !` ?

Are you aware of the spotify authentication changes ?

**Comment by JohnnyCrazy** [comment]
`[...] and it stopped working!!`

Like I wrote in the E-Mail 10 minutes ago, if you're not able to report a specific error, you should stop reyling on open-source projects.
