### ISSUE TITLE
status.Track.IsAd does not works

### ISSUE THREAD

**Issue by SomeOneMore** [JohnnyCrazy/SpotifyAPI-NET#159]
Hi.
Anyone can confirm if there is any trouble with the status.Track.IsAd?
it returns allways false...
I don't know from when. Just saw yesterday night.
Thanks in advance.
BR

**Comment by SomeOneMore** [comment]
The ads with tittle Spotify are not recognized as ad; other ads, with title and subtitle are well recognized.

**Comment by JimmyAppelt** [comment]
An ad gets recognized by track type or it's length ... not the title itself. Did you checked the value's of these when they didn't get recognized ?

**Comment by SomeOneMore** [comment]
Sorry, seems my problem.
Closing and sorry again.
