### ISSUE TITLE
New documentation-site

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#16]
We got a new WIP documentation site.

It's available here: [Spotify-API .NET Docs](http://johnnycrazy.github.io/SpotifyAPI-NET/)
They're built with mkdocs, the branch for the "raw" docs is `docs`
Travis-CI automatically builts them on push and pushes the new changes to the `gh-pages`-branch

It's pretty much empty by now, but I will fill it the next weeks.
If you have any ideas or suggestions, feel free to post them :+1:

**Comment by eltoncezar** [comment]
I think a changelog or an upgrade guide would be nice. I lost some time upgrading to version 2.0 :)

**Comment by JohnnyCrazy** [comment]
I will see if I can get something on the docs-page :)
