### ISSUE TITLE
OnTrackChange event does not fire after ads

### ISSUE THREAD

**Issue by ghost** [JohnnyCrazy/SpotifyAPI-NET#160]
I see the OnTrackChange event stops firing after ads.
If no ads are shown all works fine, but once one ad arrives, the event is not more fired.

**Comment by D3thw0lf** [comment]
I don't know if this belongs to this issue but I guess it fits best here:

For some reason the random Songs (ex. after finishing a playlist, spotify is playing a "random" song you can vote up or down) are counted as advertising (just the first one). I hope you know what I wanted to say here ^^'


Using SpotifyLocalAPI.
Client Version: 1.0.75.483.g7ff4a0dc (Windows Store-Version) // untested with Win32 Client
Lib Version: v2.18.1

**Comment by JohnnyCrazy** [comment]
You could try it with the new release, should be working now
