### ISSUE TITLE
Documentation "SpotifyAPI-NET Examples" are broken

### ISSUE THREAD

**Issue by gabernardone** [JohnnyCrazy/SpotifyAPI-NET#162]
The page "Exemples" are broken

![image](https://user-images.githubusercontent.com/12052755/28174374-b8ae35dc-67c7-11e7-8b61-b20af88adef1.png)

**Comment by JohnnyCrazy** [comment]
Well, it's not broken, just empty 😛 

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Docs/docs/SpotifyWebAPI/examples.md

**Comment by gabernardone** [comment]
Oh, this explains evertything kkk 
Tks!!
