### ISSUE TITLE
Authentication results in System.ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by gabernardone** [JohnnyCrazy/SpotifyAPI-NET#164]
I'm following the documentation, however, shortly after opening a tab in chrome Visual Studio throws an exception

> System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=O índice estava fora do intervalo. Ele deve ser não-negativo e menor que o tamanho da coleção.

In Chrome the following message appears

![image](https://user-images.githubusercontent.com/12052755/28217920-47bf42d2-688d-11e7-9853-b128b23a93b8.png)

Code:

```
class Program
    {
        private static SpotifyWebAPI _spotify;


        static void Main()
        {
            MainAsync();
        }

        static async void MainAsync()
        {
               _spotify = new SpotifyWebAPI();
            WebAPIFactory webApiFactory = new WebAPIFactory(
                 "localhost/Auth/OpenSession",
                 22655,
                 "5c363123b6XXXXXXXXXXX",
                 Scope.UserReadPrivate,
                 TimeSpan.FromSeconds(20)
            );

            try
            {
                //This will open the user's browser and returns once
                //the user is authorized.
                _spotify = await webApiFactory.GetWebApi();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadKey();
            }

            if (_spotify == null)
                return;
        }
    }
```

**Comment by JohnnyCrazy** [comment]
The interal HTTP-Server is very limited and doesn't support HTTP Paths, use `localhost` instead `localhost/Auth/OpenSession`.

**Comment by gabernardone** [comment]
Thks Johnny, this works. But how am I going to use this in production? Kkk Could not use localhost forever.
