### ISSUE TITLE
How to add more than one Scope in WebFactory?

### ISSUE THREAD

**Issue by gabernardone** [JohnnyCrazy/SpotifyAPI-NET#168]
How can I add all the scopes I need on the WebFactory object?
Do I need to create one for each scope?

![image](https://user-images.githubusercontent.com/12052755/28285462-3295d968-6b0b-11e7-8af3-3e78262de527.png)

**Comment by JohnnyCrazy** [comment]
1. Those questions belong to the gitter channel
2. Exactly this usecase is in the example, so have a look at it please.
