### ISSUE TITLE
UWP Support?

### ISSUE THREAD

**Issue by johnfg10** [JohnnyCrazy/SpotifyAPI-NET#169]
Hey,
is there any current plans for UWP support? currently when i attempted to install it i got the error posted below

Install-Package : Package SpotifyAPI-NET 2.15.1 is not compatible with uap10.0.10586 
(UAP,Version=v10.0.10586). Package SpotifyAPI-NET 2.15.1 supports: net 
(.NETFramework,Version=v0.0)
At line:1 char:1
+ Install-Package SpotifyAPI-NET -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.Power 

thanks
johnfg10

**Comment by JohnnyCrazy** [comment]
You can try out the core-3 Branch, but it's not updated and WIP

**Comment by johnfg10** [comment]
Hmm i will try that is there any plan for a separate UWP lib?

**Comment by JohnnyCrazy** [comment]
There is no short-time plan, no.
