### ISSUE TITLE
SetSynchronizingObject(ISynchronizeInvoke obj) in WPF

### ISSUE THREAD

**Issue by lukasmoeller** [JohnnyCrazy/SpotifyAPI-NET#17]
Hello,

do you have any idea how I can use the SetSynchronizingObject (ISynchronizeInvoke obj) in wpf

thx

**Comment by JohnnyCrazy** [comment]
Hey,

I'm just a beginner in WPF-Development, but it seems like WPF-Windows don't implement **

[Quote from Stackoverflow](stackoverflow.com/questions/6764537/wpf-window-doesnt-implement-isynchronizeinvoke-invokerequired-error):
>Under the hood Windows Forms and WPF are very different.
>
>ISynchronizeInvoke is a Windows Form concept built upon Win32 API that doesn't apply to WPF. In WPF, we use the Dispatcher for communicating between threads.

But maybe you can implement the ISynchronizeInvoke on your own? But I don't know much about it
