### ISSUE TITLE
Using SpotifyAPI-NET in Windows Service

### ISSUE THREAD

**Issue by JoergBe** [JohnnyCrazy/SpotifyAPI-NET#172]
Hi,

when I am using this API in a windows service, it tries to open the spotify login screen in a browser window by using the ImplicitGrantAuth or the AutorizationCodeAuth. This doesn't work in a windows service... When I use ClientCredentialsAuth, I don't have access to the user related information. Is there a possibility to avoid the Login Screen in ImplicitGrantAuth or AutorizationCodeAuth? Setting ShowDialog to false does not work.

Best regards,
Jörg

**Comment by JohnnyCrazy** [comment]
Hi @JoergBe ,

You will need some kind of backend service which will handle the AutorizationCodeAuth, a small NodeJS server or whatever. Then it's up to you how to connect your local app with the backend. For example, a user could first go to your webpage, login, and authorize spotify. Then, he needs to copy a displayed code to the windows service. This service can make calls with this code and so on...
