### ISSUE TITLE
Spotify v1.0.62.508.g2c497f24 has breaking changes

### ISSUE THREAD

**Issue by DanielGilbert** [JohnnyCrazy/SpotifyAPI-NET#173]
Looks like the newest Spotify version v1.0.62.508.g2c497f24 introduces a breaking change for this library.

"https" isn't working any longer as a protocol endpoint for spotilocal.com/127.0.0.1

However, I successfully connected via "http://test1234.spotilocal.com:4381" - as you can see, also the port has changed.
I'm not sure if this endpoint is only available for backwards compatibility, though.

**Comment by JohnnyCrazy** [comment]
Seems like my spotify client is stuck on `1.0.60.492.gbb40dab8`

Are you on windows @DanielGilbert ?

**Comment by JohnnyCrazy** [comment]
Seems like [spotify is doing staged rollouts](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/How-can-I-update-Spotify-aplication/m-p/294314#M1940), so sadly I can't confirm this yet.

`spotilocal.com` is not resolved on my version

**Comment by DanielGilbert** [comment]
Hi. :) 

Yeah, I'm also stuck on that version, but I colleague of mine got the update. Which also led me to the conclusion that it might be a buggy update and got withdrawn.

I could zip my test version that I have and provide it to you - in which way whatsoever. Btw, the change I suggest also works with your/our version - looks like they re-enabled http some versions ago, and are now deprecating the https version.

I guess this might have caused too much trouble with self-signed certificates etc.

**Comment by JohnnyCrazy** [comment]
I guess the best idea is, to make the IP/Domain and port configurable, but supply some default values. This way everyone can adapt their projects if there is such a change.

Maybe I can get this done tomorrow

**Comment by JohnnyCrazy** [comment]
Added with `2.16.0`, you can now use `SpotifyLocalAPIConfig` to configure `TimerInterval`, `Port`, and `HostUrl`

[Link to docs](https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyLocalAPI/#configuration)
