### ISSUE TITLE
Spotify unable to connect

### ISSUE THREAD

**Issue by crossfire151** [JohnnyCrazy/SpotifyAPI-NET#175]
`if (!SpotifyLocalAPI.IsSpotifyRunning())
            {
                AppErrorText.Text = "Spotify isn't running!";
                AppErrorText.Visible = true;
                AppErrorText.ForeColor = Color.DarkRed;
                SpotifyControls.Visible = false;
                return;
            }
            if (!SpotifyLocalAPI.IsSpotifyWebHelperRunning())
            {
                AppErrorText.Text = "SpotifyWebHelper isn't running!";
                AppErrorText.Visible = true;
                AppErrorText.ForeColor = Color.DarkRed;
                SpotifyControls.Visible = false;
                return;
            }

            bool successful = _spotify.Connect();
            if (successful)
            {
                AppErrorText.Text = "Connected!";
                AppErrorText.Visible = false;
                SpotifyConnectBtn.Enabled = false;
                UpdateInfos();
                _spotify.ListenForEvents = true;
            }
            else
            {
//Unable to connect at this line.\\
                DialogResult res = MessageBox.Show(@"Couldn't connect to the spotify client. Retry?", @"Spotify", MessageBoxButtons.YesNo);
                if (res == DialogResult.Yes)
                    Connect();
            }`

API fails to connect error at: "Unable to connect at this line".

**Comment by JimmyAppelt** [comment]
If you experience a problem in a method it's better to post the complete method, also the method declaration. Is the method called `Connect` ?

**Comment by JimmyAppelt** [comment]
Closing it's an issue that can be replicated.

**Comment by JohnnyCrazy** [comment]
Like @JimmyAppelt said, we need some more infos. Maybe related to #173 , which spotify version are you running @crossfire151 ?

**Comment by crossfire151** [comment]
`
public void Connect()
        {
            if (!SpotifyLocalAPI.IsSpotifyRunning())
            {
                AppErrorText.Text = "Spotify isn't running!";
                AppErrorText.Visible = true;
                AppErrorText.ForeColor = Color.DarkRed;
                SpotifyControls.Visible = false;
                return;
            }
            if (!SpotifyLocalAPI.IsSpotifyWebHelperRunning())
            {
                AppErrorText.Text = "SpotifyWebHelper isn't running!";
                AppErrorText.Visible = true;
                AppErrorText.ForeColor = Color.DarkRed;
                SpotifyControls.Visible = false;
                return;
            }

            bool successful = _spotify.Connect();
            if (successful)
            {
                AppErrorText.Text = "Connected!";
                AppErrorText.Visible = false;
                SpotifyConnectBtn.Enabled = false;
                UpdateInfos();
                _spotify.ListenForEvents = true;
            }
            else
            {
                DialogResult res = MessageBox.Show(@"Couldn't connect to the spotify client. Retry?", @"Spotify", MessageBoxButtons.YesNo);
                if (res == DialogResult.Yes)
                {
                Connect();
                }
                else if (res == DialogResult.No)
            {
                    if (System.Windows.Forms.Application.MessageLoop)
                    {
                        System.Windows.Forms.Application.Exit();
                    }
                    else
                    {
                        System.Environment.Exit(1);
                    }
                }    
            }
            
        }
`
This is copied from the example from this API (SpotifyAPI.Example, LocalControl.cs). All that is changed is the AppErrorText.Text changed from MessageBox.

Spotify Version: 1.0.65.508.g2c497f24
