### ISSUE TITLE
Can not connect to spotify on version 1.0.62.508.g2c497f24

### ISSUE THREAD

**Issue by SomeOneMore** [JohnnyCrazy/SpotifyAPI-NET#176]
After update to this version, i'm unable to connect to Spotify.

**Comment by JohnnyCrazy** [comment]
Try changing the port and host to the old values 'https://127.0.0.1' and `4371` via `SpotifyLocalAPIConfig`

**Comment by SomeOneMore** [comment]
Where to change this, please?

**Comment by JohnnyCrazy** [comment]
Have a look at the changelog and release notes?

https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyLocalAPI/#configuration

**Comment by SomeOneMore** [comment]
mmm, i have not SpotifyLocalAPIConfig. trying on Vb...
_spotify = New SpotifyLocalAPI(New SpotifyLocalAPIConfig()

**Comment by SomeOneMore** [comment]
How to use with vb.net please?

**Comment by SomeOneMore** [comment]
Question:
i need to modify the spotifyAPI.dll for connect to the new port and url.
where to modify?
i've changed in SpotifyLocalAPIconfig.cs:

        ```
        //public string HostUrl { get; set; } = "http://127.0.0.1";
        public string HostUrl { get; set; } = "https://127.0.0.1";

        //public int Port { get; set; } = 4381;
        public int Port { get; set; } = 4371;
```
but does not work.
Where to touch?
