### ISSUE TITLE
Installing api with unity 

### ISSUE THREAD

**Issue by dimsomeguy** [JohnnyCrazy/SpotifyAPI-NET#178]
So I might just be being dumb but I am attempting to install your API in to my unity project. (currently making a music visualizer and wanted to add spotify support so I could play my playlists though it). every time i attempt to install your API though VS15's nuget package installer I get an error saying the following. 

> Could not install package 'Newtonsoft.Json 8.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Unity Subset v3.5' but the package does not contain any assembly references or content files that are compatible with that framework.

I'm still pretty new to using outside API's with c# in unity and this hasn't really happened before. Is there any solution you know of? as I haven't seen anyone else even attempting to install this package in to a unity project before and it seems to be taking a problem with it.

**Comment by FireFlame74** [comment]
Unity runs on an older .NET Framework (2.0 or in this case 3.5), but this API is designed for 4.5
SpotifyAPI-NET/SpotifyAPI/SpotifyAPI.csproj: `<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>`

**Comment by dimsomeguy** [comment]
Is there any way of getting the api to work with v3.5 or will I be better off attempting to find a different api?

**Comment by nkssnim** [comment]
Unity 2017.1 has an option to run on .NET 4.6. Open up the player settings in your project and under "Scripting Runtime Version", select "Experimental (.NET 4.6 Equivalent)".

**Comment by dimsomeguy** [comment]
Currently no, I'm still getting the same error as before. From what I have read on the unity documentation for the .NET 4.6 version, it's only applied at run time. So I guess when I open NuGet manager in vs the code is still being recognized as v3.5. I am about to send it over to the unity devs as a bug hopefully I hear back from them and this isn't just me being dumb.

**Comment by FireFlame74** [comment]
@dimsomeguy Another solution might be to create a dll from the API and use it in Unity.

**Comment by nkssnim** [comment]
@dimsomeguy that is strange because 4.6 mode in unity is what i use to get this api working

**Comment by dimsomeguy** [comment]
@nkssnim Did you do it in vs? it could be just me vs having trouble picking up the difference. I might open up a new project in the morning set it to 4.6 before creating and scripts and then try adding in the api. If that doesn't work then idk.

**Comment by nkssnim** [comment]
@dimsomeguy changing it in Unity will make VS automatically target .NET Framework 4.6 when you open the solution from inside Unity.

**Comment by JohnnyCrazy** [comment]
Hi,

I think Unity support should be available with 3.0, have a look at #276 for more infos and please report back if it's not working
