### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by crossfire151** [JohnnyCrazy/SpotifyAPI-NET#179]
I found issues with sometimes not being able to communicate with spotilocal.com

For those who have projects that only use this API locally I found connecting via:
http://localhost:4380

This seams to work better,
Just thought I would drop it here in case anyone else is having issues with spotilocal.com :)

**Comment by JohnnyCrazy** [comment]
Added to the docs, so people can find it easier - Thanks! 👍
