### ISSUE TITLE
Access violation at Adverts

### ISSUE THREAD

**Issue by iUltimateLP** [JohnnyCrazy/SpotifyAPI-NET#18]
Hey Johnny,
all works perfectly in that example application, but when my Spotify runs into an advert / imported song, i get an access violation in the example app, looking like this: 
In a System.NullReferenceException Exception of type 'mscorlib.dll "has occurred, but this was not handled in user code.

Additional information: Object reference not set to an object instance.

If a handler is available for this exception, the program may continue to run safely.
(translated by Google Translator, because my Visual Studio is same as me, in german :D)

**Comment by JohnnyCrazy** [comment]
Hey @iUltimateLP 

Sorry I'm replying that late. Does it still occur with the new spotify client? They made some improvements to their API, so maybe it's solved

**Comment by iUltimateLP** [comment]
I already forgot about that, but I fixed it, by adding an If mh.isAdRunning() before showing the album cover, that literally fixed my problem but thanks for replying!

**Comment by JohnnyCrazy** [comment]
Alright :+1:
