### ISSUE TITLE
only valid bearer authentication supported

### ISSUE THREAD

**Issue by adahox** [JohnnyCrazy/SpotifyAPI-NET#181]
i've created an console project and imported the library to project.

right now i'm trying seach some music/artist but the Exception returns to me "only valid bearer authentication supported"
whats happening? 

follow my litle code. i inserted all project because its short and readable.

      using SpotifyAPI.Web.Auth;
      using System;
      using System.Collections.Generic;
      using System.Linq;
      using System.Text;
      using System.Threading.Tasks;
      using SpotifyAPI.Web;
      using SpotifyAPI.Web.Enums;
      using SpotifyAPI.Web.Models;

     namespace ConsoleApp1
    {
         class Program
        {
            private static SpotifyWebAPI _spotify;
            private static SpotifyWebAPI _spotify2;
            private static SearchItem item;
            
           public static async void Main2()
           {

            WebAPIFactory webApiFactory = new WebAPIFactory(
                 "http://localhost",
                 8000,
                 "heres-my-id",
                 Scope.UserReadPrivate,
                 TimeSpan.FromSeconds(20)
            );

            try
            {
                //This will open the user's browser and returns once
                //the user is authorized.
                _spotify = await webApiFactory.GetWebApi();
            }
            catch (Exception ex)
            {
                //MessageBox.Show(ex.Message);
                Console.WriteLine(ex.Message);
                Console.ReadLine();
            }

            if (_spotify == null)
                return;
        }
        private static SearchItem searchArtist(string artist)
        {
            item = _spotify2.SearchItems(artist, SearchType.All);

            if (item.HasError())
            {
                Console.WriteLine("Error Status: " + item.Error.Status);
                Console.WriteLine("Error Msg: " + item.Error.Message);
                Console.ReadLine();
               
            }
            return item;
        }
        public static void Main(string[] args)
        {
            Main2();
            String input;

            _spotify2 = new SpotifyWebAPI();

            //SeveralArtists artists = _spotify.GetRelatedArtists("1KpCi9BOfviCVhmpI4G2sY");
            //Console.WriteLine("artista : " + artists.Artists[0].Name);
           
            do
            {
                Console.Clear();

                Console.WriteLine("Digite sua Busca: ");
                Console.WriteLine("");
                input = Console.ReadLine();

                Console.WriteLine("Procurando pelo Artista: " + input);
                Console.WriteLine("espere um pouco...");

                SearchItem result = searchArtist(input);

                Console.WriteLine("");
                Console.WriteLine("");
                Console.WriteLine("--------------------------------------------");

                if (result.Albums.Total == 0)
                    Console.WriteLine("Não existe albums com este nome!");
                else
                {
                    Console.WriteLine("");
                    Console.WriteLine("Total de albums : " + result.Albums.Total);
                }

                if (result.Artists.Total == 0) 
                    Console.WriteLine("Não existe Artistas com este nome!");
                else
                {
                    Console.WriteLine("");
                    Console.WriteLine("Total de Artists : " + result.Artists.Total);
                }

                if (result.Playlists.Total == 0)
                    Console.WriteLine("Não existe Playlists com este nome!");
                else
                {
                    Console.WriteLine("");
                    Console.WriteLine("Total de Playlists : " + result.Playlists.Total);
                }

                Console.ReadLine();

            } while (input != null);

                
               
            

        }
    }
}

**Comment by JohnnyCrazy** [comment]
Why are you creating a `_spotify2`? You need to use the object returned by `await webApiFactory.GetWebApi();`, it's `_spotify` in your case. This object will have the correct auth headers set

**Comment by JohnnyCrazy** [comment]
And please use our [gitter chat](https://gitter.im/SpotifyAPI-NET/Lobby?source=orgpage) for basic questions
