### ISSUE TITLE
Suggestion: Artwork with Web API

### ISSUE THREAD

**Issue by mmartain** [JohnnyCrazy/SpotifyAPI-NET#182]
I don't know if its possible or i'm just looking over it, but with the local API you can get the album artwork. Is there a way this could be implemented also in the web api? I have a bunch of spotify id's and i want to download artwork for them. I can easily search the track and get all the info but it seems the artwork url is not exposed?

Thanks! Great lib btw!

**Comment by JimmyAppelt** [comment]
Did you check `SimpleAlbum` ? 
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/Models/SimpleAlbum.cs#L25

**Comment by mmartain** [comment]
Clearly i did not... my bad! Great!
