### ISSUE TITLE
GetAlbumArtUrl dosn't work

### ISSUE THREAD

**Issue by MarcPhi** [JohnnyCrazy/SpotifyAPI-NET#186]
the output url on album covers seems to be wrong (GetAlbumArt also dosn't work)

**Comment by JohnnyCrazy** [comment]
Example app still works fine, are you 100% sure?

![](https://i.imgur.com/LmTxbMR.png)

**Comment by MarcPhi** [comment]
ex:
test = status.Track.GetAlbumArtUrl(640)

outputs me "http://o.scdn.co/0/33080534f9716c159af3cc491162a3e8745e6d84" but this url does not seem to exist(tested on several songs)

**Comment by JohnnyCrazy** [comment]
I need some track id to reproduce this

**Comment by MarcPhi** [comment]
output url http://o.scdn.co/0/f869cc4caa36adb2558fda786fa92ca55d3427ea
played track https://open.spotify.com/track/2EZAQ2b1ZG3WjnYzTtgwfj

**Comment by JohnnyCrazy** [comment]
The correct URL, which is also returned by the current version, is http://o.scdn.co/640/f869cc4caa36adb2558fda786fa92ca55d3427ea

How can this `status.Track.GetAlbumArtUrl(640)` even work, it should be `status.Track.GetAlbumArtUrl(AlbumArtSize.Size640)`

**Comment by MarcPhi** [comment]
thanks for helping that worked
i guess `status.Track.GetAlbumArtUrl(640)` worked because "size" is defined as "AlbumArtSize" and vb tries to convert it
