### ISSUE TITLE
SpotifyLocalAPI.isSpotifyInstalled

### ISSUE THREAD

**Issue by jwallet** [JohnnyCrazy/SpotifyAPI-NET#187]
Will be nice to add a method to check if spotify is installed/exists
`return File.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "spotify\\spotify.exe"));`

**Comment by JohnnyCrazy** [comment]
Go for it, happy to merge a PR 👍

**Comment by JohnnyCrazy** [comment]
Implemented by #193
