### ISSUE TITLE
Support for users top tracks?

### ISSUE THREAD

**Issue by CaptainMorgs** [JohnnyCrazy/SpotifyAPI-NET#188]
I can't seem to find a way to get a user's top tracks like this endpoint: /v1/me/top/{type}
Am I missing something or are you planning to add this?

Thanks.

**Comment by JohnnyCrazy** [comment]
It's there, just not mentioned in the docs:

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/SpotifyWebAPI.cs#L1224

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/SpotifyWebAPI.cs#L1194

**Comment by JohnnyCrazy** [comment]
Done - 05721ef
