### ISSUE TITLE
Support for porxy configuration

### ISSUE THREAD

**Issue by philippk80** [JohnnyCrazy/SpotifyAPI-NET#192]
Hello,

great work by the way.

In my point of view a proxy-configuration would be great. 
Think of applications behind a corporate proxy or something like this.

A nice place for implementation could be the WebAPIFactory.

Best regards,

Phil

**Comment by aleab** [comment]
@JohnnyCrazy, any update on this?
If you are not working on it, I could start, if you don't mind.

**Comment by JohnnyCrazy** [comment]
Not started yet, so sure, go for it :+1: 😉

**Comment by JohnnyCrazy** [comment]
Implemented by #224
