### ISSUE TITLE
Error 503 and lost connection

### ISSUE THREAD

**Issue by juanruiz85** [JohnnyCrazy/SpotifyAPI-NET#196]
Hi

first i want that you know that i am new with c# and about this of programming stuff

I am trying to make a scheduler with your api  but this keep losing the connection each time that I leave it without use for some time

i tried to force the connection but i got this error

i hope can help me, thank you

here pics

app

![error](https://user-images.githubusercontent.com/6697786/32630654-ac4565e0-c55a-11e7-9c10-49e8cd61484e.PNG)

the debug

![error spotify api](https://user-images.githubusercontent.com/6697786/32630653-ac296f84-c55a-11e7-9bb8-fce8c429d8f4.PNG)

**Comment by JohnnyCrazy** [comment]
I guess this is something on your side, works fine here

**Comment by juanruiz85** [comment]
Hi

here my code, here i am trying to verify that the app have connection with spotify but i am not sure if i am doing good

my code:

        //function for do play or pause and verifying the connection before
        //this code now is a mess because always give me error or stop working without reason
        private void Procesos(string Proceso, String Hora)
        {
            if (Proceso == "play")
            {
                bool successful = _spotify.Connect();
                if (successful)
                {
                    //call the click button action from playbtn
                    playBtn_Click(new object(), new EventArgs());
                    listBox1.Items.Add("Play - Conectado a " + Hora);
                }
                else
                {
                    Connect();
                    playBtn_Click(new object(), new EventArgs());
                    listBox1.Items.Add("Play - ReConectado a " + Hora);
                }
            }
            if (Proceso == "pause")
            {
                bool successful = _spotify.Connect();
                if (successful)
                {
                    //call the click button action from pausebtn
                    pauseBtn_Click(new object(), new EventArgs());
                    listBox1.Items.Add("Pausa - Conectado a " + Hora);
                }
                else
                {
                    Connect();
                    //call the click button action from pausebtn
                    pauseBtn_Click(new object(), new EventArgs());
                    listBox1.Items.Add("Pausa - ReConectado a " + Hora);
                }
            }
        }

**Comment by juanruiz85** [comment]
This code is where i call the function procesos

CODE: 

```
        private void timer1_Tick(object sender, EventArgs e)
        {
            Temporizador();
        }

        //Process for play and stop the music
        private void Temporizador()
        {
            //Pauses
            if (DateTime.Now.ToString("HH:mm") == "14:55")
            {
                Procesos("pause", "14:55");
            }
            if (DateTime.Now.ToString("HH:mm") == "16:00")
            {
                Procesos("pause", "16:00");
            }
            if (DateTime.Now.ToString("HH:mm") == "05:00")
            {
                Procesos("pause", "05:00");
            }
            if (DateTime.Now.ToString("HH:mm") == "21:50")
            {
                Procesos("pause", "21:50");
            }

            //Plays
            if (DateTime.Now.ToString("HH:mm") == "10:40")
            {
                Procesos("play", "10:40");
            }
            if (DateTime.Now.ToString("HH:mm") == "15:10")
            {
                Procesos("play", "15:10");
            }
            if (DateTime.Now.ToString("HH:mm") == "18:00")
            {
                Procesos("play", "18:00");
            }
            if (DateTime.Now.ToString("HH:mm") == "22:10")
            {
                Procesos("play", "22:10");
            }
            label9.Text = DateTime.Now.ToString("HH:mm:ss");
        }
```

**Comment by juanruiz85** [comment]
do you have a way for verify is the api is connect to Spotify?

i tried to use this
bool successful = _spotify.Connect();
if (successful)

but sometimes although I not did click to connect button this show that I am connect to Spotify

**Comment by aleab** [comment]
Normally you should call `Connect` only once in the whole application lifetime. To verify the connection you can use `GetStatus`; if it returns something meaningful, you are *connected*.

**Comment by JohnnyCrazy** [comment]
Yes, try to connect just once
