### ISSUE TITLE
Some playlists show error when loading tracks 

### ISSUE THREAD

**Issue by freezepro** [JohnnyCrazy/SpotifyAPI-NET#197]
Hey, Johnny Crazy. This is really good job, you do 

Added this thing into your sample and in some cases(only one playlist I mentioned so far it doesnt load tracks)
Paging<PlaylistTrack> savedTracks = _spotify.GetPlaylistTracks(_profile.Id, pl.Id);
                if (savedTracks.Error != null)
                    continue;

Erorr returns 404/Not Found 
playlistID = 37i9dQZF1DX1WhyP6stXXl, client ID = 31pz2sxf0gmokfm5x2g0yxx86
No matter if it private or public list, tried both for this one. Other private lisrs are loading fine.

**Comment by freezepro** [comment]
Looks like that is playlist I follow, somehow I added it into my playlists

**Comment by JohnnyCrazy** [comment]
You need to use the ProfileID of the playlist owner, not yours.

**Comment by freezepro** [comment]
Great, works
