### ISSUE TITLE
Timeout exception

### ISSUE THREAD

**Issue by freezepro** [JohnnyCrazy/SpotifyAPI-NET#198]
Hello, I am getting this exception pretty frequently

ERROR No valid response received for the last 20 secondsSTACK at SpotifyAPI.Web.Auth.WebAPIFactory.GetWebApi() 

any ideas?

**Comment by juanruiz85** [comment]
when you pressed the button pop up a internet windows?

if this windows show up and you not close before of 20 second will show that error ( Edge and IE give me that error) with firefox i not had issues

or maybe your internet setting is blocking something

![web api ok](https://user-images.githubusercontent.com/6697786/32951652-f052583e-cb67-11e7-9096-ee42a95a79e0.PNG)

**Comment by freezepro** [comment]
Lately I was thinking it is port issue, however I changed to less common used port and also trying to do 2 ports, but still doesn't work. 

Edge and IE give me that error //I  dont know as it's not on my desk. suppose it had to work at every browser

**Comment by freezepro** [comment]
what about wrapping things into some webviewer control ? so calling only webkit/chromium? 

e.g https://bitbucket.org/chromiumembedded/cef
any tips if that's easy to change?

**Comment by freezepro** [comment]
Fixed that using https://bitbucket.org/chromiumembedded/cef
