### ISSUE TITLE
Pagination for get-playlists by user in WebAPI

### ISSUE THREAD

**Issue by etiennepierrot** [JohnnyCrazy/SpotifyAPI-NET#20]
I have missing or it's impossible to browse pagination for this call?
They are something behind that that i miss?

Otherwise, i can make a PR.

**Comment by JohnnyCrazy** [comment]
Hey,

You are right, there is no pagination for this call, you have to use `getPlaylistTracks`

See [here](https://developer.spotify.com/web-api/get-playlist/), the `next`-field points to `/tracks`, so you will have to use the `getPlaylistTracks`-Method

**Comment by JohnnyCrazy** [comment]
Any further questions or can I close it?
