### ISSUE TITLE
Error: 400 - Only valid bearer authentication supported

### ISSUE THREAD

**Issue by costagontijo** [JohnnyCrazy/SpotifyAPI-NET#200]
I get this error always when do any request.

Exemple:

            SpotifyAPI.Web.SpotifyWebAPI api = new SpotifyAPI.Web.SpotifyWebAPI();
            api.AccessToken = "tokenhere";
            SpotifyAPI.Web.Models.PrivateProfile profile = api.GetPrivateProfile();

**Comment by JohnnyCrazy** [comment]
You are probably not using the correct token, did you follow the authentication guide on their API Docs?

**Comment by juanruiz85** [comment]
i tried and work without issues

![getting token spotify](https://user-images.githubusercontent.com/6697786/33102195-dc9bcb30-ced8-11e7-978d-5bffbee90077.PNG)

**Comment by costagontijo** [comment]
Thank you for reply

I'm using the Spotify-Android-SDK https://github.com/spotify/android-sdk for authenticate.

First I call a spotify login window (android activity):

        private void OpenSpotifyLoginWindow()
        {
            SpotifySdk.AuthenticationRequest request = new SpotifySdk.AuthenticationRequest.Builder(CLIENT_ID, SpotifySdk.AuthenticationResponse.Type.Token, REDIRECT_URI)
                    .SetScopes(new string[] { "user-read-private", "playlist-read", "playlist-read-private", "streaming" })
                    .Build();

            SpotifySdk.AuthenticationClient.OpenLoginActivity(this, REQUEST_CODE, request);
        }

Second, after the user confirm authorization, the app receives the token.

Finnaly I use this token to call Web API:

            SpotifyAPI.Web.SpotifyWebAPI api = new SpotifyAPI.Web.SpotifyWebAPI();
            api.AccessToken = "myAccessToken";
            SpotifyAPI.Web.Models.PrivateProfile profile = api.GetPrivateProfile();

**Comment by JohnnyCrazy** [comment]
Did you also set `TokenType`?

```c#
api.TokenType = "Bearer";
api.AccessToken = "...";
```
