### ISSUE TITLE
how to know the current playlist?

### ISSUE THREAD

**Issue by SomeOneMore** [JohnnyCrazy/SpotifyAPI-NET#201]
How to know what is the current playlist is playing?
When i send a playurl and the track is finished, i need to continue where spotify was before the playurl.
Thanks in advance.

**Comment by JohnnyCrazy** [comment]
You can use the Web-API for that, it's in the `context` object https://beta.developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/
