### ISSUE TITLE
redirectUri problem

### ISSUE THREAD

**Issue by syncromindproj** [JohnnyCrazy/SpotifyAPI-NET#202]
Hello, 
I have some problems with the redirectUri. In my application I'm setting the redirectUri as: http://localhost:59788/Home/OAuth and in the whitelist I put the same value. The process never finish and I don't know which would be the exactly problem.
I also specify the port in the webApiFactory but without success.
What do you think I am doing wrong?

**Comment by JohnnyCrazy** [comment]
We need some code and the exact redirect value in your Spotify "My Apps" section, else we can't really help much
