### ISSUE TITLE
Use multiple scopes?

### ISSUE THREAD

**Issue by CaptainMorgs** [JohnnyCrazy/SpotifyAPI-NET#207]
According to the spotify api documentation you can use multiple scopes https://developer.spotify.com/web-api/using-scopes/ 

But when doing authentication with ImplicitGrantAuth, the WebAPIFactory only takes one argument for scope. Am I missing something here?

Thanks!

**Comment by JohnnyCrazy** [comment]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Example/WebControl.cs#L110-L112

**Comment by CaptainMorgs** [comment]
Thanks!
