### ISSUE TITLE
Spotify API .NET - Null Paging List

### ISSUE THREAD

**Issue by Vlocks** [JohnnyCrazy/SpotifyAPI-NET#21]
I have the following code:

        String userID = playlistInfo.getUserID(playlistURL);
        String playlistID = playlistInfo.getPlaylistID(playlistURL);

        Paging<PlaylistTrack> pagingList = webAPI.GetPlaylistTracks(userID, playlistID);

        var trackList = pagingList.Items;            

        foreach (PlaylistTrack trackInfo in trackList) 
        {
            lstSongs.Items.Add(trackInfo.Track.Artists.ToString() + " - " + trackInfo.Track.Name.ToString());
        }

When I enter a valid URL, the webAPI.GetPlaylistTracks should've return a list with various items, but, instead, it returns null. I have no idea what's wrong, so that's why I came here. Does anyone have any idea?

I've checked every line of the code, but I can't find anything that could be the problem.

Thanks

(sorry for bad english)

**Comment by JohnnyCrazy** [comment]
What are These lines doing
````
String userID = playlistInfo.getUserID(playlistURL);
    String playlistID = playlistInfo.getPlaylistID(playlistURL);
````
And can you post the user id + playlistid

**Comment by Vlocks** [comment]
Oh, sorry, I forgot those lines. They are instances for the class PlaylistInformations, which code is below

Code:

public string getUserID(string url) 
        {
            string[] userID = url.Split(':');

            return userID[2].ToString() ; 
        }

        public string getPlaylistID(string url)
        {
            string[] userID = url.Split(':');

            return userID[4].ToString();
        }

**Comment by JohnnyCrazy** [comment]
I just tested a public playlist, worked fine. Did you make sure the playlist is public OR the user granted the required scopes?

Can you try running this:
````c#
Paging<PlaylistTrack> pagingList = spotify.GetPlaylistTracks(userID, playlistID);
if (pagingList.HasError())
{
    Error error = pagingList.ErrorResponse;
    Debug.WriteLine(error.Status + ":" + error.Message);
}
````

**Comment by Vlocks** [comment]
Actually, I'm not using any scopes. Should I? :/

**Comment by Vlocks** [comment]
I ran the code you posted, and it returned Error 400 "Only valid bearer authentication supported" . So I do need authenticating

**Comment by JohnnyCrazy** [comment]
Yea,propably the playlist is private

**Comment by JohnnyCrazy** [comment]
Since this is propably resolved, I will close this :)
