### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by juanruiz85** [JohnnyCrazy/SpotifyAPI-NET#210]
Hello
I am testing the new version of your API
I like to use the local application API but now I can not use the latest version, I do not know the reason but now I can not connect but if i used the old version of your api work witout issues
my version of the spotify is 1.0.70.388.g8e1ed5af and in your code I saw this 1.0.50.41368.gbd68dbef
could you help me please?
Thank you

**Comment by aleab** [comment]
Are you using the latest nuget package or the version from master? If it's the latter, I'm having trouble as well; I think #209 broke the `Query` method.

**Comment by JohnnyCrazy** [comment]
Should be fixed in master - Generally speaking, use the github/nuget releases/tags, master is not considered stable.
