### ISSUE TITLE
LocalApi Set SpotifyVolume

### ISSUE THREAD

**Issue by battlezad** [JohnnyCrazy/SpotifyAPI-NET#211]
Hi,
I'm having problems with setting spotify volume. It does not set volume at all when  executed in exe. In Visual Studio debug mode it works fine.

My code:
private  void button1_Click_1(object sender, EventArgs e)
{
  if (button1.Text.Equals("[M] MUTE"))
  {
          button1.Text = "[M] UNMUTE";
          _spotify.SetSpotifyVolume(0.0f);        
  }
  else
  {
       button1.Text = "[M] MUTE";
       _spotify.SetSpotifyVolume(100.0f);
   }
}

What could be wrong?

**Comment by JohnnyCrazy** [comment]
Works fine here, are you sure your method is getting called?

**Comment by battlezad** [comment]
Yes, it is called and other buttons works fine, play, next etc.

What info I can tell you to track this?

**Comment by battlezad** [comment]
Hmm.. I think running exe in admin mode is the key.
