### ISSUE TITLE
Get charts support e.g. Global Top 50

### ISSUE THREAD

**Issue by CaptainMorgs** [JohnnyCrazy/SpotifyAPI-NET#213]
Is there any way to get the charts of most popular tracks? Currently I am using https://spotifycharts.com/regional and downloading the CSV which seems sub-optimal.

Thanks!

**Comment by JohnnyCrazy** [comment]
[This is currently not possible with the web API](https://github.com/spotify/web-api/issues/33)

Why is the CSV sub-optimal?
