### ISSUE TITLE
No AlbumResource when playing local files

### ISSUE THREAD

**Issue by coczero** [JohnnyCrazy/SpotifyAPI-NET#214]
If I play local files in Spotify the AlbumResource of the StatusResponse is always null even if the track I'm playing has album information in Spotify.

**Comment by JohnnyCrazy** [comment]
Yes, because it's nö official Spotify Tracks

**Comment by coczero** [comment]
I know, but wouldnt it be possible to get that info?
You can get the Artist and Track name from the response so why not the album?

**Comment by JohnnyCrazy** [comment]
Because Spotify doesnt provide it, so there is nothing we can Change...

**Comment by coczero** [comment]
Okay, thats too bad.
Thanks
