### ISSUE TITLE
OnTrackEnd event?

### ISSUE THREAD

**Issue by jbr98** [JohnnyCrazy/SpotifyAPI-NET#215]
Is there any way to implement an OnTrackEnd event? Currently playing a single track that is not part of a playlist will not automatically auto play a new song afterwards on the spotify client and so will not trigger the OnTrackChange event. With an OnTrackEnd event I would be able to fix this problem.

**Comment by JohnnyCrazy** [comment]
You can do this yourself by listening for the `OnTrackTimeChange`-event in a very small intervall (for example 20ms). Then you can calculate the remaining time using `totalTrackTime - currentTrackTime` and if this value is less than e.g 1 second, trigger your code.
