### ISSUE TITLE
GetAlbumArtUrl not working as it should

### ISSUE THREAD

**Issue by crossfire151** [JohnnyCrazy/SpotifyAPI-NET#216]
Hi,

The following returns (404) File not found.
`Dim ArtURL As String = _spotify.GetStatus.Track.GetAlbumArtUrl(AlbumArtSize.Size160)` (Dim _spotify As New SpotifyLocalAPI)

is this a bug or has this changed?

Thanks in advance,

Crossfire151

**Comment by JohnnyCrazy** [comment]
Which spotify track did you retrieve? Example app still works on my side
