### ISSUE TITLE
Date time parse issue

### ISSUE THREAD

**Issue by sridhar19091986** [JohnnyCrazy/SpotifyAPI-NET#217]
Getting negative int value when i try to convert to unix time 
public static int ToUnixTimeMillisecondsPoly(this DateTime time)
        {
            return (int)time.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds;
        }
please change to double, something like below.
public static double ToUnixTimeMillisecondsPoly(this DateTime time)
        {
            return time.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds;
        }

**Comment by JohnnyCrazy** [comment]
Damn, that's beginner mistake 😛 

Fixed in master, thanks!
