### ISSUE TITLE
Something wrong with version 1.0.74.380

### ISSUE THREAD

**Issue by ghost** [JohnnyCrazy/SpotifyAPI-NET#218]
With this version problems started.

**Comment by Gruhlum** [comment]
You have to be more specific.
An error that occures for me is that sometimes when the track changes OnTrackChange returns a new song that is not null, but the values are.

**Comment by aleab** [comment]
@SomeOneMore what kind of problems? Can they be replicated in the example application in this repo?

@Gruhlum does that happen with podcasts or with normal songs? If it's podcasts, then it's expected behaviour.

**Comment by Gruhlum** [comment]
@aleab normal songs. And no specific ones, the same song can work one time and the next it's broken again.

**Comment by aleab** [comment]
@Gruhlum I think it's better if you create another issue until @SomeOneMore gives more info on theirs.

**Comment by JohnnyCrazy** [comment]
Example app still works for me, and I don't understand the issue at all...

**Comment by Gruhlum** [comment]
Yes the problem seems to be fixed now.
