### ISSUE TITLE
PlayURL() doesn't trigger OnTrackChange event since spotify update 1.0.74

### ISSUE THREAD

**Issue by Gruhlum** [JohnnyCrazy/SpotifyAPI-NET#220]
This problem only happens with the new spotify version and can be reproduced in the example project:

Add
`Debug.WriteLine(e.NewTrack.TrackResource.Name + " - " + DateTime.Now.Minute + ":" + DateTime.Now.Second);`
to
`private void _spotify_OnTrackChange(object sender, TrackChangeEventArgs e)`

(Note: The problem occurs ~50% of the time)
Start the example project and connect to spotify. Now click the button "PlayURL". The new song will play but the timeLabel won't update correctly because OnTrackChange didn't fire as you can see in the output log.

**Comment by JohnnyCrazy** [comment]
Should work now, sorry for the late response
