### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by gilmishal** [JohnnyCrazy/SpotifyAPI-NET#221]
Are there any plans on supporting .net standard?

**Comment by Cr1TiKa7** [comment]
You can easily do it by yourself.
You just need to replace the old project file with a new one. All explained here:
http://blogs.microsoft.co.il/iblogger/2017/04/05/easily-supporting-multiple-target-frameworks-tfms-with-vs2017-and-nuget/

**Comment by JohnnyCrazy** [comment]
Not really supported, WIP in `core-3` branch and maybe come in the future. You can also have a look at #223
