### ISSUE TITLE
Set desktop client playback position

### ISSUE THREAD

**Issue by M1S2** [JohnnyCrazy/SpotifyAPI-NET#225]
I'm using your API to control my Spotify desktop client. Play and pause a song just works fine.

Now I want to change the playing position of the currently playing song. So I only want to say something like "SetPlayingPosition(64)" to play the current song from position "01:04". It seems that the SpotifyLocalAPI didn't support this feature.

To play and pause a song your API uses a message with the following format: http://127.0.0.1:4381/remote/pause.json?pause=true&ref=&cors=&_=1520448230&oauth=oauth&csrf=csrf

I tried to find a summary of possible commands in this format, but I didn't find anything.

Is there something like http://127.0.0.1:4381/remote/seek.json... that I can use to seek to a specific position?

The SeekPlayback method of the library doesn't work because I don't have Spotify Premium.

**Comment by JohnnyCrazy** [comment]
Not possible with the local API
