### ISSUE TITLE
SnapshotId missing from FullPlaylist

### ISSUE THREAD

**Issue by lukaswagner** [JohnnyCrazy/SpotifyAPI-NET#226]
The [FullPlaylist class](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/Models/FullPlaylist.cs) is missing the SnapshotId field, which it should contain according to the [API Object Model](https://developer.spotify.com/web-api/object-model/#playlist-object-full).

Should I provide a pull request adding it or is this intended?

**Comment by JohnnyCrazy** [comment]
Damn, yea, it's in `SimplePlaylist`, seems like I forgot to put it into the Full one 😅 

PR would be much appreciated 👍

**Comment by JohnnyCrazy** [comment]
Fixed by #227
