### ISSUE TITLE
Enhancement: Expose "added_by" for tracks in a playlist

### ISSUE THREAD

**Issue by sagizod** [JohnnyCrazy/SpotifyAPI-NET#229]
Hi,

I would like to request an enhancement to the FullPlaylist model to expose the "added_by" property for each track. This would be useful for collaborative playlists.

Thanks!

**Comment by JohnnyCrazy** [comment]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/3c25f49a943f32b8c30e32d2be4b6c8492c6eef6/SpotifyAPI/Web/Models/FullPlaylist.cs#L42-L43

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/3c25f49a943f32b8c30e32d2be4b6c8492c6eef6/SpotifyAPI/Web/Models/GeneralModels.cs#L51-L64

What's missing?
