### ISSUE TITLE
GetUsersRecentlyPlayedTracksAsync paging with before/after does not work

### ISSUE THREAD

**Issue by SparrowBrain** [JohnnyCrazy/SpotifyAPI-NET#232]
When providing before/after DateTime in GetUsersRecentlyPlayedTracksAsync() the method returns page.Items == null.

This is because the Util.ToUnixTimeMilliSecondsPoly() returns a timestamp with decimal point.

**Comment by SparrowBrain** [comment]
I have made a change in Util.cs:
`return (long)time.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds;`

I'm not sure how to create a Pull Request since it looks like I cannot push the branch.

**Comment by JohnnyCrazy** [comment]
Hi @SparrowBrain 

I sadly didn't test this change, nice catch!
You first need to fork the repo to your own account. Then you can push your branch and create a PR in this/my repo.

Would gladly accept the PR 👍

**Comment by SparrowBrain** [comment]
PR: https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/233

I'm a bit concerned about potentially making a braking change.

**Comment by JohnnyCrazy** [comment]
Fixed by #233
