### ISSUE TITLE
AddToQueue method plays the specific track directly

### ISSUE THREAD

**Issue by Wampe** [JohnnyCrazy/SpotifyAPI-NET#24]
Hi,

when I call the method with a Spotify-Uri the actual track (currently playing in the application and stored in the queue) gets stopped and the specified track behind the uri starts playing (+ queue gets cleared). Is this the right behavior?

When I add a track to the queue in the Spotify application via context menu it is get set behind the current track and all "next titles" remains.

Best Regards

**Comment by JohnnyCrazy** [comment]
Hi,

This method is quite experimental.
It worked when I tested it months ago, but then suddenly it behave strange and just played the song. Spotify might changed something on their side (maybe need to update parameters or sth).

When I have more, I will look at it and check if we can fix it :+1: 
(Marked it as obsolete for now, so there is no further obscurity)

**Comment by JohnnyCrazy** [comment]
Spotify Connect Endpoints are implemented in [2.14.0](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.14.0), which also has some kind of queuing AFAIK
