### ISSUE TITLE
Made a project using Spotify-API-NET

### ISSUE THREAD

**Issue by CaptainMorgs** [JohnnyCrazy/SpotifyAPI-NET#240]
My project can be found here https://github.com/CaptainMorgs/spotify-oculus-release

Thanks you for making this, it made my life a lot easier!

Apologies if this is the wrong way to contact you.

**Comment by JohnnyCrazy** [comment]
Cool project! Added it to the project site! (35b531ec2bda6863118c2b61b8a9f572c062459e)
