### ISSUE TITLE
spotify track isAd() fails

### ISSUE THREAD

**Issue by jwallet** [JohnnyCrazy/SpotifyAPI-NET#241]
hello

why does it checks if the length is 0, this validation fails when you switch between radio station or an album because there is a delay between the switch ? a normal song starts and it's detected as an ad... you should remove that part from the isAd() validation and checks only for the type == "ad".

**Comment by JohnnyCrazy** [comment]
It's checking on the total track length, not the current playback length. I just checked and after switching radios/albums, the `Length` of the track is always `>0`. Are you sure that error can occur? If so, I need more steps to reproduce this bug.

**Comment by jwallet** [comment]
i use the event `OnTrackChanged` to see if the next track is an ad (using isAd()).
- i play a song from my current playlist (like sublime what ive got)
- i search on spotify for a random artist, for this case: "Led Zeppelin"
- i click on the first album (while spotify is still playing Sublime)
- the debugger shows that the event has been triggered, the next song is : title ="", album ="", artist ="", tracktype="normal", length=0 (spotify is actually switching from Sublime song to play Led Zeppelin album (a 1-2 seconds without sound))
- then the debugger triggers again the event and it finds the first song from LedZep album.
so, the first event should not trigger at all, but to handle it at the moment i just check trackType == "ad", some apps might never detects that this event trigger was triggered twice

**Comment by JohnnyCrazy** [comment]
I think I found the issue.

Could you test the following build, it won't change `isAd()` but it will fix `OnTrackChange`:

https://ci.appveyor.com/project/JohnnyCrazy/spotifyapi-net/build/2.0.290/artifacts

**Comment by jwallet** [comment]
it's flawless 👍

**Comment by jwallet** [comment]
looks like some playlist does not trigger onTrackChanged , like `peaceful piano` on spotify the first song is `where's my love`

**Comment by jwallet** [comment]
if I want to release my new build, do you suggest me to wait for the api next release or to grab this test build instead

**Comment by JohnnyCrazy** [comment]
I will release a new build tomorrow,sorry for the Delay!

**Comment by JohnnyCrazy** [comment]
Should be working in 2.19.0!
