### ISSUE TITLE
local api Spotify mute/unmute can't be used if NAudio is already instancied

### ISSUE THREAD

**Issue by jwallet** [JohnnyCrazy/SpotifyAPI-NET#242]
Hi

just to let you know that any methods using naudio can't be used if the project using this api is already using it and has an instance of it running, so maybe add a message to the throw error to let the dev know to use its own naudio instance and find the process by himself, or provide a method that returns the spotify process id or session audio end point device id in the list

**Comment by JohnnyCrazy** [comment]
This API is not hooking into any NAudio stuff, it's just relying on the windows API, which can be seen here:

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/35b531ec2bda6863118c2b61b8a9f572c062459e/SpotifyAPI/Local/VolumeMixerControl.cs

**Comment by jwallet** [comment]
`ex.Message = "Unable to cast object of type 'NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject' to type 'MMDeviceEnumerator'."`

looks like NAudio is the source of the issue

**Comment by jwallet** [comment]
by the way, thanks a lot the this api, it's a time saver

**Comment by JohnnyCrazy** [comment]
Are you 100% sure this is related to this API? I would need some steps to reproduce this, but I doubt I can help here, NAudio is not of my internal stuff.

Thanks for your kind words :) 👍

**Comment by jwallet** [comment]
no i'm not 100% sure, but i always stay connected to the volume mixer using naudio, so that's why i guess no more than one library can use the volume mixer at the same time (windows api is probably used by naudio as well). you can close this issue if you want

**Comment by jwallet** [comment]
also, i changed my mind about muting spotify while it plays an ad, because i experimented the same as #160 , it did not trigger the OnTrackChanged event after the ad. I did not have a chance to try the test build you uploaded in #241, cause ads show randomly. The next build might solve that first issue

**Comment by JohnnyCrazy** [comment]
Report back if there is anything which is not working like expected :thumsup:
