### ISSUE TITLE
Handling and Testing 429 Responses

### ISSUE THREAD

**Issue by NaturalFigurehead** [JohnnyCrazy/SpotifyAPI-NET#246]
I want to confirm that there is nothing built into the library that handles 429s and retries? If not I was wondering if anyone has a snippet that they use when handling 429s and then retrying.

Also part of my problem is that I'm having a hard time testing my handling of 429s from Spotify. Sometimes they will appear in my production environment, but rather intermittently. And when I try to recreate them on my dev machine they never occur even if they are still happening in production. Does anyone have advice on this sort of testing?

**Comment by Noggog** [comment]
Created a pull request adding this logic to SpotifyWebAPI https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/282
