### ISSUE TITLE
Local Api methods not working (might be noob question)

### ISSUE THREAD

**Issue by Jalu1** [JohnnyCrazy/SpotifyAPI-NET#247]
I am simply trying to play music using the basic local API commands. I have followed the documentation, but cannot seem to get anything to happen. Why? My code:``

    using UnityEngine;
    using SpotifyAPI.Local; //Base Namespace
    using SpotifyAPI.Local.Enums; //Enums
    using SpotifyAPI.Local.Models; //Models for the JSON-responses
    using SpotifyAPI.Web;
    using SpotifyAPI.Web.Auth;
    using SpotifyAPI.Web.Models;
    using SpotifyAPI.Web.Enums;

    public class SpotifyStuff : MonoBehaviour
    {
    private static SpotifyWebAPI spotifyWeb = new SpotifyWebAPI();
    private static SpotifyLocalAPI spotifyLocal = new SpotifyLocalAPI();
    public async System.Threading.Tasks.Task<bool> Setup()
    {
        if (!SpotifyLocalAPI.IsSpotifyRunning())
        { 
            print("Spotify Not Running!"); //Make sure the spotify client is running
            SpotifyLocalAPI.RunSpotify();
        }
        if (!SpotifyLocalAPI.IsSpotifyWebHelperRunning())
        {
            print("WebHelper Not Running!"); //Make sure the WebHelper is running
            SpotifyLocalAPI.RunSpotifyWebHelper();
        }
        if (!spotifyLocal.Connect())
            print("Connection Failed!"); //We need to call Connect before fetching infos, this will handle Auth         stuff

        StatusResponse status = spotifyLocal.GetStatus(); //status contains infos
        
        WebAPIFactory webApiFactory = new WebAPIFactory(
      "http://localhost",
      8000,
      "XXXXXXXXXXXXXXXX",
      Scope.UserReadPrivate,
      System.TimeSpan.FromSeconds(20)
    );

        try
        {
            //This will open the user's browser and returns once
            //the user is authorized.
            spotifyWeb = await webApiFactory.GetWebApi();
            return true;
        }
        catch (System.Exception ex)
        {
            print(ex.Message);
            return false;
        }
        
    }
    public async System.Threading.Tasks.Task<bool> Play(string url)
    {
        try
        {
            await spotifyLocal.PlayURL(url, "Toto IV");
            return true;
        }
        catch(System.Exception e)
        {
            print(e.Message);
            return false;
        }
    }

    async void Start()
    {
        var foo = Setup();
        print(foo);
        print("potato" );
        await Play("2374M0fQpWi3dLnB54qaLX");
        await spotifyLocal.Pause();
        print("potato");
        //...
    }

    void Update()
    {

    }

    void OnGUI()
    {

    }
}``

**Comment by JohnnyCrazy** [comment]
Hi, sorry for the late response.

What is not working? Do you have any results?

```
    await Play("2374M0fQpWi3dLnB54qaLX");
    await spotifyLocal.Pause();
```
You're also starting to play a song and instantly pause, intended?
