### ISSUE TITLE
Unusual response while trying to generate auth token.

### ISSUE THREAD

**Issue by uncvrd** [JohnnyCrazy/SpotifyAPI-NET#248]
Hello! Been struggling to get this library to work properly in my project. I'm currently trying to set up authentication using the following code:

```
private static SpotifyWebAPI _spotify;
public async Task<ActionResult> QuickCreate1(QuickCreateViewModel model)
{
    WebAPIFactory webApiFactory = new WebAPIFactory(
    "http://localhost/callback",
    51952,
    "fa6430fc389d47ad8678d34459552fc4",
    Scope.UserReadPrivate,
    TimeSpan.FromSeconds(20)
    );
    try
    {
        //This will open the user's browser and returns once
        //the user is authorized.
        _spotify = await webApiFactory.GetWebApi();
    }
    catch (Exception ex)
    {
        Debug.WriteLine(ex.Message);
    }

    if (_spotify == null)
        return RedirectToAction("Index", "Home");

    return RedirectToAction("Index", "Home");
}
```

When I run my app, I have a button that triggers the `QuickCreate1` task. In my Spotify Dev console, I have the following as my callback url: `http://localhost:51952/callback`

Clicking on the button opens a new tab, and both tabs hang. The original tab hangs on `http://localhost:51952/` 

and the new tab hangs as 

`https://accounts.spotify.com/authorize/?client_id=fa6430fc389d47ad8678d34459552fc4&response_type=token&redirect_uri=http://localhost:51952/callback&state=XSS&scope=user-read-private&show_dialog=False` 

And my Output console on Visual Studio shows:
```
An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in SpotifyAPI.dll
An attempt was made to access a socket in a way forbidden by its access permissions
```

Have you seen anything like this before? What else can I provide to debug? Thanks!

**Comment by uncvrd** [comment]
Okay update, I think I discovered that this doesn't work while in debug mode? When I use browser link in Visual Studio, the async method returns to my callback url (now localhost:51952/home/SpotifyReturn) with this url:

`http://localhost:51952/home/SpotifyReturn#access_token=MYACCESSTOKENHERE&token_type=Bearer&expires_in=3600&state=XSS`

However, I was under the impression that the the auth tab would close and the callback would be instantiated on my original tab, but that tab is a blank `http://localhost:51952/Home/QuickCreate1`

What am I missing?

**Comment by JohnnyCrazy** [comment]
Hi @uncvrd , sorry for the late response

It seems like you are already running a HTTP-Server yourself (seems like ASP.NET?). If so, you don't have to use the internal HTTP-Server, it's mainly for testing purposes and client applications.

Basically you have generate a URI to your webserver, redirect the client to it and then fetch the tokens returned by the spotify API. I think you can get the URI by using the `AuthorizationCodeAuth` class, but I will write an example once I'm at home :wink:
