### ISSUE TITLE
ResumePlayback "Malformed json"

### ISSUE THREAD

**Issue by h-philip** [JohnnyCrazy/SpotifyAPI-NET#249]
Hey, when I'm trying to call the ResumePlayback method with contextUri and offset,  I'm getting an error object with the message "Malformed json". I tried it with example contextUri string and offset int from spotify developer portal (where it worked). I think the offset value is sent as `"offset" : 5` and not `"offset" : { "position" : 5 }` but I'm not sure.

**Comment by JohnnyCrazy** [comment]
Next release will include the fix, should be today

Thanks for reporting 👍
