### ISSUE TITLE
Spotify Web authentification fails

### ISSUE THREAD

**Issue by Mrnikbobjeff** [JohnnyCrazy/SpotifyAPI-NET#25]
When i try to connect and authenticate an app several times in a short period of time the hhtpserver does not recognise the answer and waits on a never comming response. This issue is always fixed after a restart. I reproduced this bug on 4 different computers, running Windows 10 x64, Windows 8.1 x64, Windows 7 x64 and x32. This happens with every spotify application, even the example application provided here. After some debugging I believe that the error resides in the SimpleHttpServer Listen method

**Comment by JohnnyCrazy** [comment]
Could you elaborate how to reproduce this? And why do you need to auth in a short period of time, normally you only need to do this once started (and prop. after 30min)? Did you check if the HTTPServer is running?
