### ISSUE TITLE
Problem with local API

### ISSUE THREAD

**Issue by RobertRoxenhall** [JohnnyCrazy/SpotifyAPI-NET#253]
Hi,

Currently having major problems with the local API. It doesn't appear to work at all. Had an application that worked last summer that now gives me no data at all (except version number). I don't get any track information, I can't pause or play or do anything at all.

Thought it had something to do with the new horrible windows store version of spotify, so I uninstalled that and force-installed a version of spotify I used last summer. But I still don't get anything.

Is there something I've missed somewhere? Have something changed? Is there any way I can test the local API or see if there's something wrong with the JSON data?

**Comment by RobertRoxenhall** [comment]
![image](https://user-images.githubusercontent.com/22895727/42906066-3c2b8b68-8ada-11e8-81ef-47f484210bd3.png)

**Comment by MarcoPNS** [comment]
Already fixed. Check out commit 1cae73b

**Comment by RobertRoxenhall** [comment]
This should then work with the lastest windows store version of spotify?

**Comment by JohnnyCrazy** [comment]
Yes, after it's released. Or you use the CI artifacts [here](https://ci.appveyor.com/project/JohnnyCrazy/spotifyapi-net/build/2.0.301/artifacts)

**Comment by RobertRoxenhall** [comment]
Wow! You're a real life-saver!

Thank you.
