### ISSUE TITLE
Track is null - local api

### ISSUE THREAD

**Issue by jasniec** [JohnnyCrazy/SpotifyAPI-NET#255]
Hi,
I've used this api (local version) in two dekstop apps.
I didn't change their's code for more than a week. 
In the meantime it was spotify desktop app update.

Now, where's the problem:
I can connect to spotify successfully, status is not null, but Track property is null (also playing is set to false) - it happens when I have spotify open and play song.
Also changeTrack event is not reacting to spotify's song change.

ClientVersion property has value "1.0.85.259.g4ab01679".

My friend found this article: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/
Maybe this will help

looking forward for reply
jasniec

**Comment by Inzaniity** [comment]
#254 Explains why the local API does not work.
