### ISSUE TITLE
GetPlayingTrack.Item.DurationMs stops app

### ISSUE THREAD

**Issue by StepIg** [JohnnyCrazy/SpotifyAPI-NET#257]
Hello
I have calls to `GetPlayingTrack.Item.DurationMs` and `GetPlayingTrack.ProgressMs` and works ok, but when call them, app stops in these instructions and freeze the app during this time.
Is there any way to avoid this?
Thanks in advance.

**Comment by JohnnyCrazy** [comment]
Use the `async` variants. It won't freeze the main context.

**Comment by StepIg** [comment]
@JohnnyCrazy 
I don't see async variant for GetPlayingTrack
Are you talking about other method?

**Comment by JohnnyCrazy** [comment]
Oh, for some reason I forgot to add the `async` versions of the player methods. 

I added them in 73976e0
