### ISSUE TITLE
Error whith 32 bit nirsoft dll

### ISSUE THREAD

**Issue by Mrnikbobjeff** [JohnnyCrazy/SpotifyAPI-NET#26]
When trying to use the nirsoft dll under the build settings "Release" and "Any Cpu" you get an exception as soon as SpotifyApi gets loaded because it tries to load a 32 bit dll in a 64 bit process. Thus, you need to include the 64 bit version as well and add a check to determine wether the current process is 64 or 32 bit

**Comment by JohnnyCrazy** [comment]
Hi,

AFAIK there is only one nircmd.dll available [here](http://www.nirsoft.net/cmp/nircmd.html)  
Just copy it to your project output and it should work. (It's a C++ DLL, so adding a reference won't work)

**Comment by Mrnikbobjeff** [comment]
Sorry that it took this long to come back to you. The link to the 64 bit nir cmd is http://www.nirsoft.net/utils/nircmd.html , they changed the section to utils

**Comment by JohnnyCrazy** [comment]
But that is the .exe file, not the DLL?

**Comment by Mrnikbobjeff** [comment]
I completely did not realise this. I am really sorry for causing this inconvenience.

**Comment by JohnnyCrazy** [comment]
No Problem :)
