### ISSUE TITLE
AddPlaylistTrack and AddPlaylistTracks states invalid track URI

### ISSUE THREAD

**Issue by Eriejar** [JohnnyCrazy/SpotifyAPI-NET#262]
Currently trying to use the AddPlaylistTrack and AddPlaylistTracks but the function always returns status 400, invalid track uri for the every single uri that I try to pass in. I checked in google if the uris are valid so I don't believe that is the issue. For reference, here is one working URI that is not passing. 2oUmr2Kaxup6iOglqK0FK3

The error message is specifically 
"Invalid track uri: 2oUmr2Kaxup6iOglqK0FK3"

**Comment by jscholes** [comment]
`2oUmr2Kaxup6iOglqK0FK3` isn't a valid URI, it's a track ID.  The URI would be `spotify:track:2oUmr2Kaxup6iOglqK0FK3`

**Comment by Eriejar** [comment]
Oh ok thanks for the heads up! I followed what it said in the documentation for the format so that confused me a bit. 
Also, it looks like I got it to work but it only inputs 100 songs into an album? Do I need to manually split the array or did I miss a setting that I need to set?
