### ISSUE TITLE
using a external http server problem

### ISSUE THREAD

**Issue by StepIg** [JohnnyCrazy/SpotifyAPI-NET#267]
Hi
im using an external http server. all goes ok. i reach server in the desired ip on callback, got test response from the index.html in the http server but nothing happens and i can't connect to spotify.
any idea?
thanks in advance.

**Comment by jscholes** [comment]
After authorizing, are you exchanging the code delivered to your server by Spotify in the callback URL for an access token?  If yes, how are you communicating that back to your application?

**Comment by Noggog** [comment]
Heya.  I'm also interested in question 3.  I'd like to be able to refresh tokens without opening a browser that's just going to have to be closed by the user.

**Comment by StepIg** [comment]
@Noggog 
For the refresh token process you don't need browser for all. The process only call a endpoint to get the refresh token as response.
About the external httpserver, i will take a look. I think somewhere can be found the address for callback...
Sorry but i can't help more...

**Comment by JohnnyCrazy** [comment]
If you have more to discuss, feel free to reopen the ticket.

Generally, implementing Spotify's OAuth flows with an already existing webserver is super easy if you carefully follow the steps in https://developer.spotify.com/documentation/general/guides/authorization-guide/

I would advise not to use this library for the authentication part, but rather for the part after it: Making the actual requests with an access token
