### ISSUE TITLE
TrackChangeEvent

### ISSUE THREAD

**Issue by Crotex** [JohnnyCrazy/SpotifyAPI-NET#268]
Hi there,

I previously had a program running on the LocalAPI and now I obviously had to switch to the WebAPI. Everything works pretty well, beside that once a song is over or the user skips it the software still displays the song playing when the software launched. Is there something similar to the TrackChangeEvent of the LocalAPI or how should I handle this?

Thanks in advance!

**Comment by jscholes** [comment]
This currently isn't possible to replicate using the web API because Spotify don't provide any mechanisms to track playback state changes in realtime.  Please follow https://github.com/spotify/web-api/issues/492 for updates.

**Comment by StepIg** [comment]
@Crotex 

You can use timers for comparing previous and current times and previous and current track info in order to know changes in position and tracks playing.

You can move your code from events to timers taking needed info about tracks time, etc... from the webAPI. 

For me all is running ok.

**Comment by Crotex** [comment]
@StepIg 

That's basically how I solved it. I have a timer checking every second if the song playing now is different than the previous one and if so the layout changes accordingly.

**Comment by jscholes** [comment]
@Crotex:
> I have a timer checking every second if the song playing now is different than the previous one and if so the layout changes accordingly.

It's worth noting that Spotify impose certain rate limits on the API (i.e. how often you're application is permitted to call an endpoint).  At 60 requests per minute to check the currently-playing track, this approach will quickly become infeasible if the app is intended to be used by multiple users.  If you'll be the only user of the app then you'll hopefully be fine.

**Comment by StepIg** [comment]
@jscholes 
That means there is impossible to have the change track control now? :-S

**Comment by jscholes** [comment]
If you are making a request to the Spotify API once every second, that's 60 requests per minute for a single user.  With just a couple more users, the rate of requests baloons dramatically up to 180 per minute.  So yes, I am saying that there is currently no way to process track changes in anything approaching realtime if your app will be used by more than 2 people.  Spotify don't publish exact rate limits in their documentation, but 180 requests to a single endpoint per minute is almost certainly too much.  Have a look at the discussion on the issue I linked above for more on this.

**Comment by Crotex** [comment]
@jscholes 

Thanks for the information. I wasn't sure whether there is such a thing but i guess my application will be for private use only for now. 
I'll definitely follow the [issue](https://github.com/spotify/web-api/issues/492) you linked above :)

**Comment by StepIg** [comment]
One solution can be start Spotify on web (open.spotify.com) and watch class playback-bar__progress-time.
