### ISSUE TITLE
ResumePlayback Issues - Documentation Error and Question

### ISSUE THREAD

**Issue by MartinHarran** [JohnnyCrazy/SpotifyAPI-NET#269]
First of all, the documentation in player.md gives the following usage example for ResumePlayback:

> ErrorResponse error = _spotify.ResumePlayback(uris: new List<string> { "spotify:track:4iV5W9uYEdYUVa79Axb7Rh" });

That, however, throws an "ambiguous call" error as the final parameter (offset) is required.

Secondly, I want to resume a paused player exactly where it is paused in a playlist but cannot for the life of me figure out how to do that. Am I missing something obvious or is that not supported?

**Comment by h-philip** [comment]
I think `_spotify.ResumePlaybackAsync(offset: "")` should do it.

**Comment by MartinHarran** [comment]
Thanks, @h-philip, that's exactly what I wanted - I reckoned I was probably missing something obvious :)
