### ISSUE TITLE
Error	38	The type or namespace name 'SpotifyAPI' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by DieterKoblenz** [JohnnyCrazy/SpotifyAPI-NET#27]
Error	38	The type or namespace name 'SpotifyAPI' could not be found (are you missing a using directive or an assembly reference?)

This is the error when I just have "using SpotifyAPI.Local;" in my code. I installed the package via nuPackage and referenced the compiled dll file I downloaded here.

**Comment by DieterKoblenz** [comment]
Never mind, I didnt check the log properly before sending in this issue. My target framework was .net 4.0 instead of 4.5

**Comment by JohnnyCrazy** [comment]
Just a quick question, the compiled dll should be inside the NuGet Package, did you have to add it manually?

**Comment by DieterKoblenz** [comment]
No, it includes the compiled dll! I tried to reference it manually when it didn't work.

**Comment by JohnnyCrazy** [comment]
Alright, thought I didn't add the dll to the package :P
