### ISSUE TITLE
System.ComponentModel.Win32Exception: 'The system cannot find the file specified'

### ISSUE THREAD

**Issue by Chris-Barber** [JohnnyCrazy/SpotifyAPI-NET#273]
I am getting this error in a .net core console app but it does not specify what file is missing.

`WebAPIFactory webApiFactory = new WebAPIFactory(
       "http://localhost",
       8000,
       "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
       Scope.PlaylistModifyPrivate,
       TimeSpan.FromSeconds(20)
  );

            try
            {
                //This will open the user's browser and returns once
                //the user is authorized.
                var spotify = await webApiFactory.GetWebApi();

                FullPlaylist playlist = spotify.CreatePlaylist("6m6cfxc309lh53bvj7e5umqqq", "This is my new Playlist");
                if (!playlist.HasError())
                    Console.WriteLine("Playlist-URI: " + playlist.Uri);

                var playlists = spotify.GetUserPlaylists("6m6cfxc309lh53bvj7e5umqqq", 20);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }`

The error is thrown on this line:
var spotify = await webApiFactory.GetWebApi();

Does this mean a dependency is missing maybe?

**Comment by JohnnyCrazy** [comment]
.NET Core is not supported yet, but should be soonish.
