### ISSUE TITLE
Connecting to Web - Error 404

### ISSUE THREAD

**Issue by xTheChosen0ne** [JohnnyCrazy/SpotifyAPI-NET#279]
Hey guys, how can I properly connect with SpotifyAPI.Web ?
I want to use the recommended ImplicitGrantAuth, and that was what I wrote:
`Dim auth As SpotifyAPI.Web.Auth.ImplictGrantAuth = New SpotifyAPI.Web.Auth.ImplictGrantAuth(clientID, "http://localhost:8000", "http://localhost:8000", SpotifyAPI.Web.Enums.Scope.UserReadPrivate)
        auth.Start()
        auth.OpenBrowser()`

Yes, in the Spotify Developer Center, I added "http://localhost:8000" to the Redirect URIs.
While trying to connect, the open Browser just says "404 - Not Found"

What can I do?

**Comment by JohnnyCrazy** [comment]
Any logs?

**Comment by JohnnyCrazy** [comment]
Did you start the app as admin? There must be some output of the HTTPServer in your app logs or somewhere.

**Comment by the-powl** [comment]
Same here,
I tried to implement the Example Project and when the browser opens it just says "404 - Not Found"

the Console says:

>  22:13:47.841 INF >> [WebServer] Web server prefix 'http://localhost:4000/' added.
>  22:13:47.882 INF >> [WebServer] Finished Loading Web Server.
>  22:13:47.929 INF >> [WebServer] Started HTTP Listener
>  22:13:48.354 DBG >> [WebServer] Start of Request 9772b704 - Source ::1:60237 - GET: /
>  22:13:48.358 DBG >> [WebServer] Web API Module::WebApiModule.<.ctor>b__2_0
>  22:13:48.361 TRC >> [WebServer] Result: False
>  22:13:48.368 DBG >> [WebServer] Resource Files Module::ResourceFilesModule.<.ctor>b__2_1
>  22:13:48.369 DBG >> Resource System: index.html
>  22:13:48.369 TRC >> [WebServer] Result: False
>  22:13:48.369 ERR >> No module generated a response. Sending 404 - Not Found
>  22:13:48.386 DBG >> [WebServer] End of Request 9772b704

**Comment by JohnnyCrazy** [comment]
I think I'm able to reproduce it, but need some time finding the bug

**Comment by JohnnyCrazy** [comment]
Please try again with Version 3.0.2 once it's on nuget

Or use the provided dlls here, make sure you use the correct framework folder:
https://ci.appveyor.com/project/JohnnyCrazy/spotifyapi-net/build/2.0.322/artifacts
