### ISSUE TITLE
ImplicitGrantAuth - JSON error

### ISSUE THREAD

**Issue by xTheChosen0ne** [JohnnyCrazy/SpotifyAPI-NET#283]
Hey guys, after #279 closed and the API is updated, I neither can't connect properly.

I want to use the recommended ImplicitGrantAuth, and that was what I wrote:
`Dim auth As SpotifyAPI.Web.Auth.ImplictGrantAuth = New SpotifyAPI.Web.Auth.ImplictGrantAuth(clientID, "http://localhost:8000", "http://localhost:8000", SpotifyAPI.Web.Enums.Scope.UserReadPrivate)
        auth.Start()
        auth.OpenBrowser()`

In the Spotify Developer Center, I added "http://localhost:8000" to the Redirect URIs.

Since Version 3.0.2 is out, the browser opens a different window (3 tabs: JSON, Raw Data, Header) after trying to connect. While _raw data_ is showing "OK - This window can be closed now", _JSON_ shows up the error "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data".
I anyway tried different SpotifyWebAPI-Methods: Obviously I can't get any information about tracks or albums.

**Comment by JohnnyCrazy** [comment]
There shouldn't be 3 windows and IDK why that happens in your case...I would need to see some screenshots or similar.

Is that your whole Auth code? A full example should look like this:

```cs
        static void Main(string[] args)
        {
            ImplictGrantAuth auth = new ImplictGrantAuth(clientID, "http://localhost:4002", "http://localhost:4002");

            auth.AuthReceived += AuthOnAuthReceived;
            auth.Start();
            auth.OpenBrowser();

            Console.ReadLine();
            auth.Stop(0);
        }

        private static void AuthOnAuthReceived(object sender, Token payload)
        {
            SpotifyWebAPI api = new SpotifyWebAPI
            {
                TokenType = payload.TokenType,
                AccessToken = payload.AccessToken
            };
            PrivateProfile profile = api.GetPrivateProfile();
            Console.WriteLine(profile.DisplayName);
        }
```

**Comment by JohnnyCrazy** [comment]
Please reopen if you have more infos and it still doesn't work.
