### ISSUE TITLE
Warn: seems Spotify has changed playlists parameters order

### ISSUE THREAD

**Issue by StepIg** [JohnnyCrazy/SpotifyAPI-NET#285]
Seems Spotify has changed parameters order.

**Comment by JohnnyCrazy** [comment]
Can you elaborate?

**Comment by JohnnyCrazy** [comment]
Maybe it's related to this change?

https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

**Comment by JohnnyCrazy** [comment]
However, this doesnt seem to be a problem with the library itself? If so, please reopen
