### ISSUE TITLE
Spotify Connect

### ISSUE THREAD

**Issue by DieterKoblenz** [JohnnyCrazy/SpotifyAPI-NET#29]
I use spotify in my kitchen and control it there using this .NET api but I also play a lot of music in the living room which I can easily transfer from the kitchen using Spotify Connect. Is it possible to hook into connect and force the local running spotify client to take over the music stream?

(Work around I use now is to select the next song in the kitchen, spotify takes over then.)

**Comment by JohnnyCrazy** [comment]
Sadly, the local spotify API doesn't feature any spotify-connect interfaces. So nothing I can do here :/
