### ISSUE TITLE
Problem with .NET Framework

### ISSUE THREAD

**Issue by nkleinert** [JohnnyCrazy/SpotifyAPI-NET#291]
Hey, I created a normal form application and wanted to test your library.
However, I always get the following error with .NET Framework (tested were 4.6.1 and 4.7.1):

> System.IO.FileNotFoundException: "Die Datei oder Assembly "Unosquare.Labs.EmbedIO, Version=1.16.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden."

**Comment by JohnnyCrazy** [comment]
How did you install the lib?

**Comment by nkleinert** [comment]
I installed these:
![Nuget](https://i.imgur.com/Q7RuNxi.png)

**Comment by JohnnyCrazy** [comment]
Mh, I just created a new 4.6.1 projected, added Spotify.Web and Spotify.Web.Auth (it will auto install the dependencies) and it compiled successfully

**Comment by JohnnyCrazy** [comment]
Also, in your image, `EmbedIO` is listed, so I'm not sure what's happening there

**Comment by nkleinert** [comment]
That's really weird. I deleted all references again and then reinstalled all packages in the Nuget Manager. Now it works. Thanks for your quick reaction! 👍

**Comment by JohnnyCrazy** [comment]
👍 

Sometimes, cleaning the solution also helps.

**Comment by fragilethoughts** [comment]
Got the same exception but only with 4.7.1 after switching to 4.6.1 it worked. Annoyance.
