### ISSUE TITLE
Code never hits AuthOnAuthReceived

### ISSUE THREAD

**Issue by kneekey23** [JohnnyCrazy/SpotifyAPI-NET#296]
Hi Johnny, 

been at this all day, lol as you can see from a previous issue. So I pulled your code from the example and my code never hits the AuthOnAuthReceived function which i believe it needs to to get the actual access token. The code that comes back in the query doesn't seem to work in terms of giving me the access I need. my client id and client secret are being pulled in from AWS secrets manager without an issue. I can step through and see that they are there.

`  public void AuthorizeSpotify() {

            AuthorizationCodeAuth auth = new AuthorizationCodeAuth(clientId, clientSecret, "https://localhost:5001", "https://localhost:5001", Scope.Streaming | Scope.UserReadBirthdate | Scope.UserModifyPlaybackState | Scope.UserReadEmail | Scope.UserReadPrivate | Scope.UserReadPlaybackState | Scope.UserReadCurrentlyPlaying | Scope.UserReadRecentlyPlayed);
            auth.AuthReceived += AuthOnAuthReceived;
            auth.Start();
            auth.OpenBrowser();
            auth.Stop(0);
        }
`

`
private async void AuthOnAuthReceived(object sender, AuthorizationCode payload) {

            AuthorizationCodeAuth auth = (AuthorizationCodeAuth) sender;
            auth.Stop();
            token = await auth.ExchangeCode(payload.Code);
            spotify = new SpotifyWebAPI
            {
                AccessToken = token.AccessToken,
                TokenType = token.TokenType
            };
            PrintUsefulData(spotify);
        }
`

When my front end triggers the first method, here is the url string I receive back:
https://localhost:5001/?code=AQACfDUpM-V9PAxMttgPZ4eTV43XjhKIdB3tihgMvLxIZnuURZeVBsjTtS_T4mOPNdgsqVmrKUFXBT4cQjipoQpfM6iKMPyw_qcDH9ZvBoiJ29tRpk4LJLhdcwfcOKVVRzni9LU6XBYhpGf9eploP5zFtYWUzZcvxr4KrxUv0cx-Qc39X6wGwK4WL8dfzpcHSWfEh7NEnlHxqdFvX8GW8q5jThThcq1KRVuJ5p2L7v1WJKJavEmA2-l7BgNdAOmqB40Fiu2MrIxCvvjwbIHJ-GEl_GrWn8k3lo506GjSb7Y6plQYo3yoszC5xpfY1H2LqNiweke2e_zIuPOdxkslhxrp_wDirKT9QrBDajZ2OBGhKKFSHL8oUfchedFT5_UYpW7pgjnDAXQ8g5eEVLq1mxjDi667skqzZCmLkP9WIt8&state=3eed7400

but it never hits the other method and i know that code ^ is unauthorized. What am i doing wrong?!

**Comment by JohnnyCrazy** [comment]
Hi,

You're stopping the server directly after opening the Browser, remove this line and it should work

**Comment by kneekey23** [comment]
Ya I actually started without that line initially coming to that same realization but it never worked so I put it in trying to replicate your example exactly.  Any other ideas?

**Comment by JohnnyCrazy** [comment]
Is the example without any modifications working ? Which .net version is the project on?

**Comment by kneekey23** [comment]
I haven't tried that project by itself, only the code within my existing project. I am running .NET Core 2.1, should i downgrade to 2.0?

**Comment by JohnnyCrazy** [comment]
Is the browser showing anything when that first endpoint is hit?

**Comment by kneekey23** [comment]
Should your code samples be in a controller?

**Comment by kneekey23** [comment]
ya the browser shows the spotify screen, i click login and it redirects me nicely back to my app with the code in the query string.

**Comment by kneekey23** [comment]
when you give it the server uri, is it supposed to be a different port from the one you are running the app on? I tried making the redirect my port that im running on which is 5001 and the server one 4002 but that didn't work but im just curious if i was on the right track?
the last screen brings my app back and loads up the homepage

**Comment by JohnnyCrazy** [comment]
Sorry for the delayed response.

Well, you have two different options:

1. Use the library-internal HTTP Server to fetch the Code. It has to listen on a different port than your App. Then, the event will be called and you can call `auth.ExchangeCode(...)`

2. Use your own apps http server. I recommend this, since it is quite easy to create a controlle which fetches the code. Then, you also just have 1 HTTP Server on one port. Fetch the token via a controller, and also use it with `auth.ExchangeCode`. Done

**Comment by JohnnyCrazy** [comment]
Did you get it working @kneekey23 ?

**Comment by kneekey23** [comment]
I did thank you!

--
Nicole Klein 
714.925.5830

**Comment by Mos455** [comment]
Hi,

I'm also having the same issue, I don't quite understand the second suggested solution. Could you elaborate more on how to implement this please?

Thanks.

**Comment by bvanrijn** [comment]
My problem was that I had the NoScript extension enabled for localhost, meaning the inline script it uses to pass the token back was never executed.
