### ISSUE TITLE
Changes in the playlist URIs

### ISSUE THREAD

**Issue by OmiCron07** [JohnnyCrazy/SpotifyAPI-NET#301]
No need anymore to specify the playlist's owner : https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

**Comment by JohnnyCrazy** [comment]
The links says it has been rolled back?

**Comment by OmiCron07** [comment]
Yes, but it is live now, they just not updated the blog post. Check the API, the URIs have changed and the pages' footer all show something like that : `NOTE: looking for PUT https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}? Read the blog post.`

I quickly tested it and I confirm the new URIs are working.

**Comment by JohnnyCrazy** [comment]
What a nice communication on their side...

Thanks, I will have a look at it 👍

**Comment by JohnnyCrazy** [comment]
https://developer.spotify.com/community/news/2019/01/15/update-changes-to-playlist-uris/

They will roll it out on 28.02, I created the branch `playlist_change_28_02_19` which will be released once the rollout is done.

**Comment by OmiCron07** [comment]
Is has been merged?

**Comment by JohnnyCrazy** [comment]
Yup, it has now, will be released tomorrow with a new version @OmiCron07
