### ISSUE TITLE
ImplicintGrantAuth - Error 404

### ISSUE THREAD

**Issue by xTheChosen0ne** [JohnnyCrazy/SpotifyAPI-NET#304]
In #283 I had some problems with converting the proper Auth Code by @JohnnyCrazy  from C# into VB.NET. But I think I handled it now. This is my Code now:

```
Private Shared Sub WebConnect()
   Dim auth As SpotifyAPI.Web.Auth.ImplictGrantAuth = New SpotifyAPI.Web.Auth.ImplictGrantAuth(clientID, "http://localhost:4002", "http://localhost:4002")
   AddHandler auth.AuthReceived, AddressOf AuthOnAuthReceived

   auth.Start()
   auth.OpenBrowser()
   Console.ReadLine()
   auth.Stop(0)
End Sub

Private Shared Sub AuthOnAuthReceived(ByVal sender As Object, ByVal payload As SpotifyAPI.Web.Models.Token)
   Dim api = New SpotifyAPI.Web.SpotifyWebAPI With {
       .TokenType = payload.TokenType,
       .AccessToken = payload.AccessToken
   }
   Dim profile As SpotifyAPI.Web.Models.PrivateProfile = api.GetPrivateProfile
   Console.WriteLine(profile.DisplayName)
End Sub
```

Unfortunately, I still have problems with this Auth. I added "http://localhost:4002" to the Redirect URIs in the Spotify Developer Center already. After starting WebConnect(), my browser says "Connection Failed". When I change the parameter from auth.Stop(0) to authStop() or authStop(1000), the opened site just tells me "404 - Not Found".

Whats wrong with my code?

EDIT: The AuthOnAuthReceived-Event doesn't get triggered. Why?

**Comment by borrrden** [comment]
It looks like perhaps the callback has changed on the Spotify side?  Looks like the codebase is expecting the `/auth` endpoint, and what is getting sent from the Spotify side is the root endpoint with the parameters directly (i.e. `http://localhost:4002/#?<params>`)

**Comment by JohnnyCrazy** [comment]
Ist the server starting correctly? Any output in the debug console? Can you teach localhost:4002? 

The redirect URI is without /auth, /auth is just used to get the parameters to the server

**Comment by borrrden** [comment]
Yes the server appears to start correctly.  Here is the output:

```
 20:10:43.659 INF >> [WebServer] Web server prefix 'http://localhost:4002/' added.
Hello
 20:10:43.683 INF >> [WebServer] Finished Loading Web Server.
 20:10:43.710 INF >> [WebServer] Started HTTP Listener
 20:10:44.462 DBG >> [WebServer] Start of Request 351fa863 - Source ::1:57942 - GET: / - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
 20:10:44.467 DBG >> [WebServer] Web API Module::WebApiModule.<.ctor>b__2_0
 20:10:44.497 TRC >> [WebServer] Result: False
 20:10:44.514 DBG >> [WebServer] Resource Files Module::ResourceFilesModule.<.ctor>b__2_1
 20:10:44.517 DBG >> Resource System: index.html
 20:10:44.517 TRC >> [WebServer] Result: False
 20:10:44.517 ERR >> No module generated a response. Sending 404 - Not Found
 20:10:44.521 DBG >> [WebServer] End of Request 351fa863
```

The requested URL that generated this 404 was `http://localhost:4002/#access_token=<token>&token_type=Bearer&expires_in=3600&state=771f02b2`

Note that the `AuthorizationCodeAuth` works given similar parameters.

**Comment by JohnnyCrazy** [comment]
.net version and spotifyAPI nuget version?

**Comment by borrrden** [comment]
.NET Core 2.0 application on Windows.  spotifyAPI version is 3.1.0 (both regular and auth).

**Comment by xTheChosen0ne** [comment]
@borrrden Thank you borrrden for answering for me.

Does somebody has a temporirily workaround for the auth before the problem is fixed?

**Comment by xTheChosen0ne** [comment]
@JohnnyCrazy What can I do now?

**Comment by OneBobone** [comment]
Was this ever solved?

**Comment by JohnnyCrazy** [comment]
Well, does it work for you? @OneBobone

**Comment by OneBobone** [comment]
I get this error: " Type 'SpotifyAPI.Web.Auth.ImplictGrantAuth' is not defined."

I am really looking for some (any) very simple code to get me started in vb.net
- authorization
- check a track

Soon I need more advanced authorization to download a playlist, which is ultimately what I need.

**Comment by xTheChosen0ne** [comment]
> 
> 
> Was this ever solved?

I somehow figuered out to authorize to the API. But I didn't worked on this project for months and I am not sure if the solution is still working. As soon I am back in my city I'll send you the code for you trying it out.

**Comment by OneBobone** [comment]
Just a friendly reminder that I would appreciate this very much.

**Comment by OneBobone** [comment]
@xTheChosen0ne I think I got your code to work. 
:-)
Would be very valuable to compare the rest. Thanks!

**Comment by OneBobone** [comment]
But getting endless "waiting for host"

**Comment by OneBobone** [comment]
Thank you! That worked.
If I may, I would appreciate the discussion in a non closed forum:
https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/333
