### ISSUE TITLE
Working Auth Code?

### ISSUE THREAD

**Issue by xTheChosen0ne** [JohnnyCrazy/SpotifyAPI-NET#305]
Does anybody has an working Authorization Code for me?
Doesn't matter which Auth but ImplicitGrantAuth doesn't work for me (#304 ).

I just want to have access to the spotify music informations.

Doesn't matter if the code is in C# but I would prefer VB.NET-Code because I use this in my project as well.

Greets.

**Comment by xTheChosen0ne** [comment]
> Hope this helps.

It works!! Finally! Big big thank you.
But a question left. I get a window like this:
[https://nofile.io/f/d7mBxfG9QyH/1.PNG](url)
[https://nofile.io/f/oabh3tyA3H5/2.PNG](url)
[https://nofile.io/f/cCCUmGVRVrZ/3.PNG](url)

**Comment by OneBobone** [comment]
May I ask you what your vb.net code looks like. I am having very large problems getting started as well.
Many thanks,
Bob
