### ISSUE TITLE
is there any way to activate/deactivate fade?

### ISSUE THREAD

**Issue by StepIg** [JohnnyCrazy/SpotifyAPI-NET#307]
I found about shuffle and repeat, but not about fade.

**Comment by jscholes** [comment]
This is not available and, while I don't work for Spotify, I doubt that it ever will be.

**Comment by JohnnyCrazy** [comment]
Spotify mostly implements stuff because some stakeholder or partner has a need for it. Settings like these normally are not required for their use cases --> probably won't come.

If you still want to try your luck: https://github.com/spotify/web-api/issues
