### ISSUE TITLE
Playlist Paging: Not all elements accessable

### ISSUE THREAD

**Issue by xTheChosen0ne** [JohnnyCrazy/SpotifyAPI-NET#308]
Hey,
when I try to get all my tracks from my Spotify-Playlist (which has more than 100 elements), only the first 100 elements are accessable.

```
Dim dieSpotifyplaylist = spotifyWebApi.GetPlaylist(...)

For Each spotifyTrack In dieSpotifyplaylist.Tracks.Items
     If FuegeSpotifyTrackHinzu(spotifyTrack.Track.Id) = True Then
             hinzugefuegteIDs.Add(spotifyTrack.Track.Id)
Next
MessageBox.Show(dieSpotifyplaylist.Tracks.Total) ' <--- SHOWS REAL NUMBER OF ELEMENTS
MessageBox.Show(dieSpotifyplaylist.Tracks.Items.Count) '<--- ALWAYS SHOWS 100, I ONLY CAN GET INFORMATION OF THOSE 100 TRACKS
```

**Comment by JohnnyCrazy** [comment]
Please consult the official spotify API docs first. It clearly says such call returns a maximum of 100 tracks. If you want the rest, use the offset parameter.

Also, use `GetPlaylistTracks`

**Comment by xTheChosen0ne** [comment]
> 
> 
> Please consult the official spotify API docs first. It clearly says such call returns a maximum of 100 tracks. If you want the rest, use the offset parameter.
> 
> Also, use `GetPlaylistTracks`

Thank you and sorry for not consulting the API docs before.

Before I start another unnecessary issue: If I want to get Artists of an track or of an album.. without changing ANYTHING in my code, sometimes it works and sometimes it throws an System.NullReferenceException. This is weird

**Comment by Gruhlum** [comment]
>If I want to get Artists of an track or of an album.. without changing ANYTHING in my code, sometimes it works and sometimes it throws an System.NullReferenceException.

There could be many reasons for this, you should check:
1. is the input(TrackID, AlbumID) valid
2. Is the returned Track null
3. Is the returned Track.Artists null

My guess is that you use the wrong id for GetTrack().

This is the URL: spotify:track:123456789
and this is the id: 123456789

some functions use the URL and some the id, make sure you use the right one.

**Comment by xTheChosen0ne** [comment]
> 
> 
> > If I want to get Artists of an track or of an album.. without changing ANYTHING in my code, sometimes it works and sometimes it throws an System.NullReferenceException.
> 
> There could be many reasons for this, you should check:
> 
>     1. is the input(TrackID, AlbumID) valid
> 
>     2. Is the returned Track null
> 
>     3. Is the returned Track.Artists null
> 
> 
> My guess is that you use the wrong id for GetTrack().
> 
> This is the URL: spotify:track:123456789
> and this is the id: 123456789
> 
> some functions use the URL and some the id, make sure you use the right one.

Thank you for that suggestion. I also thought about that, but I gave the program always the same ID! With running the program several times, without changing the ID, sometimes "Track.Artists" is null, and sometimes it isn't. In fact, it isn't (There shouldn't be a SpotifyTrack without at least one artist)

**Comment by xTheChosen0ne** [comment]
> 
> 
> try this:
> 
> ```
> FullTrack track = spotify.GetTrack("id");
> if (track.HasError())
>     {
>         Debug.WriteLine(track.Error.Status + " - " + track.Error.Message);
>     }                
> ```

I did it. That's the error now which is causing this problem:
**429 - API rate limit exceeded**
