### ISSUE TITLE
Queue empty state

### ISSUE THREAD

**Issue by Wampe** [JohnnyCrazy/SpotifyAPI-NET#31]
Hi,

it´s not really an issue. It´s more a feature request. After the current (new) update of the Spotify application my queue was empty. So when it is empty and I try to get any kind of information by (eq.) _spotfy.GetStatus().Track then it is null. 
It would be great to have a property or a method that give a state of the queue.

**Comment by JohnnyCrazy** [comment]
Sadly, I can't implement this as long as https://github.com/spotify/web-api/issues/15 is not implemented

The SpotifyLocalAPI doesn't feature queue-control, so we will have to wait for the SpotifyWebAPI

**Comment by JohnnyCrazy** [comment]
Spotify Connect Endpoints are implemented in [2.14.0](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.14.0)
