### ISSUE TITLE
Nuget package needs to be updated

### ISSUE THREAD

**Issue by JeffreyO** [JohnnyCrazy/SpotifyAPI-NET#310]
The current version at Nuget is broken and needs to be updated.

**Comment by JohnnyCrazy** [comment]
How is it broken?

**Comment by JeffreyO** [comment]
In this project (https://github.com/LPardue/SpotifyStatusApplet) version 2.19.0 can't connect to SpotifyWebHelper. It only started doing this recently.

**Comment by JeffreyO** [comment]
Is the Spotify Local API no longer available? How would I go about porting the local API over to the Web API?

**Comment by JohnnyCrazy** [comment]
Please have a look at #254 , TLDR: Local API has been discontinued by spotify

Please use the new nuget packages SpotifyAPI.Web and SpotifyAPI.Web.Auth

**Comment by JeffreyO** [comment]
> Please have a look at #254 , TLDR: Local API has been discontinued by spotify
> 
> Use the new nuget packages SpotifyAPI.Web and SpotifyAPI.Web.Auth

Do SpotifyAPI.Web and Web.Auth work offline? There are people using Spotify Premium without an internet connection.

**Comment by JohnnyCrazy** [comment]
Sadly no

**Comment by JohnnyCrazy** [comment]
If you have more questions, feel free to ask them here or in a seperate issue :)
