### ISSUE TITLE
Get popular artists by genre (pop, rock, etc..) and/or country

### ISSUE THREAD

**Issue by ColorTwist** [JohnnyCrazy/SpotifyAPI-NET#311]
Very cool SpotifyAPI-NET!
Definitely donate if i use it.

I searched over examples in the git, but could not find the answer.
Would it be possible to get popular artists by genre and country?
For example: a list of X popular artists in ROCK genre from United States.

**Comment by Gruhlum** [comment]
You could use GetCategoryPlaylists("Rock", "US") then collect the songs of the first couple playlists and sort them by popularity.

**Comment by ColorTwist** [comment]
Interesting! thanks.

Just before i get into it what data does it return (artist, album, track?) and who actually "recommend" the result, users?

**Comment by JohnnyCrazy** [comment]
https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

**Comment by ColorTwist** [comment]
Great, checking that out. thanks!
