### ISSUE TITLE
Why does SpotifyLocalAPI.Connect return false?

### ISSUE THREAD

**Issue by Julinator** [JohnnyCrazy/SpotifyAPI-NET#313]
First of all, I have Spotify, the SpotifyAPI-NET package AND the Newtonsoft.Json package all on the latest version.
Now I wrote some VERY basic to get started testing:

    class Program
    {
        static void Main(string[] args)
        {
            SpotifyLocalAPI _spotify = new SpotifyLocalAPI();

            if (SpotifyLocalAPI.IsSpotifyRunning())
            {
                Console.WriteLine("[+] Spotify is running!");

                if (_spotify.Connect())
                {
                    Console.WriteLine("[+] Spotify connected!");
                }
                else
                {
                    Console.WriteLine("[X] Spotify can't connect!");
                }
            }
            else
            {
                Console.WriteLine("[X] Spotify is NOT running!");
            }

            Console.ReadLine();
        }
    }

This Just detects if spotify is running, and tries to connect while writing in the console wether it works or not.
Since the Examples I've found seemed to Connect without doing any extra configuration I expected this code to work, however the output looks like this:

    [+] Spotify is running!
    [X] Spotify can't connect!

So am I doing it wrong or what can I try o fix it?

I was also wondering if there is any intended case, where spotify is running but the Connect() method returns false?

I have been searching on both Google and the issue tracker for a long time but weren't able to find a solution, so thanks for any help.

-Julian-

**Comment by JohnnyCrazy** [comment]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/254#issuecomment-415757405

**Comment by Julinator** [comment]
Oh, sorry for not finding this ... that's sad :(
well thanks anyways
