### ISSUE TITLE
Add interface for SpotifyWebAPI to make it testable inside other apps. 

### ISSUE THREAD

**Issue by mweylandcliq** [JohnnyCrazy/SpotifyAPI-NET#314]
As a developer I would like to have an interface I can implement to to allow for unit testing without concrete implementation of a SpotifyWebAPI class.

**Comment by JohnnyCrazy** [comment]
Can't you mock the responses like in https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web.Tests/SpotifyWebAPITest.cs ?

**Comment by JohnnyCrazy** [comment]
Well, it would be another layer of abstraction and I don't like the idea of typing over every endpoint-method again 😅 

So probably won't come anytime soon, maybe with a mayor rewrite and some point far in the future
