### ISSUE TITLE
TypeLoadException when using trying to start an ImplicitGrantAuth

### ISSUE THREAD

**Issue by mystborn** [JohnnyCrazy/SpotifyAPI-NET#316]
This is the exception that it's throwing:
System.TypeLoadException: 'Could not load type 'Unosquare.Net.HttpListenerContext' from assembly 'Unosquare.Labs.EmbedIO, Version=1.15.0.0, Culture=neutral, PublicKeyToken=null'.'

**Comment by JohnnyCrazy** [comment]
Which .net version are you running in your project?

**Comment by mystborn** [comment]
I tried it on .net core 2.1 and .net framework 4.7.1. Same result in both cases. However when cloning the project the sample project works.

**Comment by AgainstTheNight** [comment]
I'm having the exact same issue. Can't seem to figure it out.

**Comment by JohnnyCrazy** [comment]
Hi,

It seems like there was an issue with the EmbedIO Version matching, could you please try 3.1.2? https://www.nuget.org/packages/SpotifyAPI.Web/3.1.2

Thanks,


/cc @AgainstTheNight @mystborn
