### ISSUE TITLE
ImplictGrantAuth instead of ImplicitGrantAuth

### ISSUE THREAD

**Issue by nunocunha** [JohnnyCrazy/SpotifyAPI-NET#320]
Copying the [example from the implicit grant auth](https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyWebAPI/auth/#implicitgrantauth), gives the following error because there's a type on ImplictGrantAuth (there's a missing `I` between the `C` and `T` in the word Implicit). There's also a typo on the controller.

`The type or namespace name 'ImplicitGrantAuth' could not be found (are you missing a using directive or an assembly reference?)`

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/f31af2395c2dddeab8352964099427bf6b4a54fe/SpotifyAPI.Web.Auth/ImplictGrantAuth.cs#L19 https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/f31af2395c2dddeab8352964099427bf6b4a54fe/SpotifyAPI.Web.Auth/ImplictGrantAuth.cs#L33

**Comment by jwallet** [comment]
Aut`h`orizationCodeAuth got changed to AutorizationCodeAuth too ?
