### ISSUE TITLE
Getting no Artist from GetPlayingTrack();

### ISSUE THREAD

**Issue by remplerus** [JohnnyCrazy/SpotifyAPI-NET#321]
Hey, I tried to get the artists from the song currently playing to display it on my screen but I only get this:

> Demons - System.Collections.Generic.List`1[SpotifyAPI.Web.Models.SimpleArtist]

Did I do something wrong?
just wrote this

`PlaybackContext songname = api.GetPlayingTrack();
            if(songname.Item != null)
            {
                song = songname.Item.Name + " - " + songname.Item.Artists;
                return song;
            }`

EDIT: Ok, now I found out, that its in a count of the artists Item but I cant get the Artist.Name without getting all the counts. Is there a way round to get the artists from another method?

**Comment by Thomi7** [comment]
Hey, you are using the List "Artists" wrong. You have to itterate through the List and add each Name to a string. 

It could look like this:
`PlaybackContext playbackContext = Api.GetPlayback();
            if (playbackContext.Item != null)
            {
                string songName = playbackContext.Item.Name;
                string artists = "";
                for (int i = 0; i < playbackContext.Item.Artists.Count; i++)
                {
                    if (i == playbackContext.Item.Artists.Count - 1) artists += playbackContext.Item.Artists[i].Name;
                    else artists += playbackContext.Item.Artists[i].Name + " - ";
                }
            }`

**Comment by Gruhlum** [comment]
you can use songname.Item.Artists.First() or songname.Item.Artists[0] for a easy solution(check for null!) , if a song has multiple artists and you want to display them you need to iterate through them.
