### ISSUE TITLE
Current playing playlist

### ISSUE THREAD

**Issue by Thomi7** [JohnnyCrazy/SpotifyAPI-NET#322]
Hey, Im currently working on an application which should restore the volume, track and the playlist which Spotify played before the shutdown of Windows. So the problem is that Windows kills the application on shutdown, giving Spotify not enough or no time to save the "settings". There are a lot of requests to the developers to fix this issue (and I think its really not that big of an issue; just reacting to some Exit Event and saying Windows to wait for it like for example Word does would work perfectly fine) but unfortunately no one fixed it yet. 

Right now my application saves the volume, track and some other player stuff like shuffle in a Json file, when Windows shuts down, and then restores all of these "settings" on startup of Spotify. As mentioned in the title, my problem is that I found no way in this API and no article about it on the official Spotify Web API page which is about reading or setting the playlist which is currently playing. 

Im not familar with the code behind this API, so I just used the great Tutorials and got it to work, but how I understand it is that the API sends URLs over a local HTTP server and the Spotify app reacts to it. So is there any way given to get the current playlist and then set it again?

**Comment by Gruhlum** [comment]
Yes it's possible:
 https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/

`PlaybackContext playback = spotify.GetPlayingTrack();`
playback.Context.uri gives you: spotify:user:NAME:playlist:PLAYLISTID

now if you want to play it back:

spotify.ResumePlayback(contextUri: "spotify:user:NAME:playlist:PLAYLISTID");

**Comment by Thomi7** [comment]
Ok, thank you for your approach! Ill try it out when I have time for it.

**Comment by JohnnyCrazy** [comment]
Feel free to reopen if you have questions @Thomi7

**Comment by novatorem** [comment]
On a similar note, is it possible to play a song then continue with the playlist the user is already listening to?

I have this set up, where it would find a song to play according to the song, then play it. The issue is, after that song is done playing, it'll just stop playback.

```
string recommendedURI = _spotify.GetRecommendations(trackSeed: new List<string> { songID }).Tracks[0].Uri;
                ErrorResponse err = _spotify.ResumePlayback(uris: new List<string> { recommendedURI }, offset: "");
```
