### ISSUE TITLE
Can't get Playlists' tracks

### ISSUE THREAD

**Issue by oxodao** [JohnnyCrazy/SpotifyAPI-NET#326]
Hi,

When trying to use the GetPlaylistTracks method I get a null object instead of "Paging<PlaylistTrack>"

I'm quite sure about my parameters since it is working when I call GetPlaylist with the same userid and same playlist id.

```
FullPlaylist pl = Client.GetPlaylist(Profile.Id, p.Id);
foreach(PlaylistTrack pt in pl.Tracks.Items)
{
    Console.WriteLine(pt.Track.Name);
}

Paging<PlaylistTrack> tracks = Client.GetPlaylistTracks(Profile.Id, p.Id, "description,uri");
foreach(var a in tracks.Items) // Crash here on track.Items because tracks is null
{
    Console.WriteLine(a.Track.Name);
}
```

The first one would give me enough informations for what I want though I can't get the pagination thing with it...

**Comment by JohnnyCrazy** [comment]
Did you check for an error? Also, `Profile.Id` is not always the owner of the playlist...you need to use the owner object inside of the playlist, should be `p.Owner.Id`

**Comment by oxodao** [comment]
How would I check? This is my first real project in C# and WPF so I'm not quite sure, I would have thought it would throw an exception.

The playlist belong to logged in user since I'm gathering those from my current user and these are on my account so they should not belong to anyone else.

**Comment by JohnnyCrazy** [comment]
`a.Error`

**Comment by oxodao** [comment]
I guess you meant track.Error, since the code crashes before I even declared a.
In this case it is Null.
I said in the first post that tracks was null but it isn't, it's tracks.item that is...
[Debugger screenshot](https://image.noelshack.com/fichiers/2019/11/7/1552856982-aze.png)

**Comment by JohnnyCrazy** [comment]
`Paging<PlaylistTrack> tracks = Client.GetPlaylistTracks(Profile.Id, p.Id, "description,uri");`

Could you try removing the `"description,uri"` part?

**Comment by oxodao** [comment]
That does the trick. Any clue why it wasn't working with this ?

**Comment by JohnnyCrazy** [comment]
You're trying to only get the `description` and `uri` fields, which do not exist on the `Paging<PlaylistTrack>` object. If you just want the track names for example, you can use `items(name)`. However, I would advise to just not use fields. They save some bytes on the wire but in the end you have bugs like these

**Comment by oxodao** [comment]
Yeah I will no longer use them. Thanks anyway :)

The description and uri field are the one in exemple in the documentation that's why I used them :/
