### ISSUE TITLE
Code to Refresh Token

### ISSUE THREAD

**Issue by MorGuux** [JohnnyCrazy/SpotifyAPI-NET#327]
Hi,
I've got the library to work, getting playback data from the user, but i'm struggling to find some code that refreshes the token.

I'm using the AuthorizationCodeAuth code from the example to get the access token, which is then saved to a json file locally.

What I want to know, is what code I need to use, just to refresh the access token. I know you need to use the refresh token (which is in the saved json) to request a new access token.

Do you need the AuthReceived event and openbrowser and start and all that, to refresh, as it opens the browser and does that stuff, but that's not needed just to refresh the token.

I get that the auth.RefreshToken method is part of the Auth, but i'm unsure what code I need just for refreshing.

**Comment by MorGuux** [comment]
Is this all the code necessary?

`            AuthorizationCodeAuth auth = new AuthorizationCodeAuth(clientid, secretid, "http://localhost:4002", "http://localhost:4002", Scope.UserReadPlaybackState);
            Token token = await auth.RefreshToken(Settings.token.RefreshToken);`

**Comment by JohnnyCrazy** [comment]
With `AuthorizationCodeAuth `, yes, you don't need a browser again and you can use the code snippet you provided

**Comment by MorGuux** [comment]
Cheers mate ;)
