### ISSUE TITLE
Image height/width can be null

### ISSUE THREAD

**Issue by silamon** [JohnnyCrazy/SpotifyAPI-NET#328]
According to the [docs](https://developer.spotify.com/documentation/web-api/reference/object-model/#image-object): The image height and/or width can be `null` or is not returned if unknown.  

Any result with unknown image widths or heights cannot be parsed correctly: Newtonsoft.Json.JsonSerializationException: Error converting value {`null`} to type '`System.Int32`'.

You can view an example of this behavior [here](https://developer.spotify.com/console/get-playlist/?playlist_id=37i9dQZF1DWTG97QsiXgEX&user_id=spotify).

**Comment by silamon** [comment]
I'm going to close this already. It's my own fault. 
I created a custom `IClient` and forgot to set the `JsonSerializerSettings`.

**Comment by JohnnyCrazy** [comment]
Out of interest, how is your IClient different than the default one? Different HTTP client? :)

**Comment by silamon** [comment]
I'm using the default `SpotifyWebClient`. But for unit testing, I've created a custom `IClient` that loads a local JSON file instead of doing a http call.

**Comment by JohnnyCrazy** [comment]
Ah, nice 👍
