### ISSUE TITLE
vb.net starting basics: empty track.name

### ISSUE THREAD

**Issue by OneBobone** [JohnnyCrazy/SpotifyAPI-NET#329]
Would you know of any vb.net code that could be a starting point?
Any examples? Google has not identified any...
Would be fantastic!

**Comment by OneBobone** [comment]
Well, I tried Getting Started / First step.

Translated the code with http://converter.telerik.com.
It looked coherent, but I got this error back:

> Reference required to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' containing the base class 'System.Object'. Add one to your project.
> 

Any idea why this error comes up?

`Imports SpotifyAPI.Web
Imports SpotifyAPI.Web.Auth
Imports SpotifyAPI.Web.Enums
Imports SpotifyAPI.Web.Models

Class SurroundingClass
    Private Shared _spotify As SpotifyWebAPI

    Public Shared Sub Main(ByVal args As String())
        '_spotify = New SpotifyWebAPI() With {
        '    .UseAuth = False
        '}
        'Dim track As FullTrack = _spotify.GetTrack("3Hvu1pq89D4R0lyPBoujSv")
        'Console.WriteLine(track.Name)
    End Sub
End Class`

**Comment by OneBobone** [comment]
So, I got a step further by referencing netstandard, but to no avail...

> Namespace or type specified in the Imports 'netstandard' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.
Reference to a non-shared member requires an object reference.--

`Code as above without comments`

**Comment by OneBobone** [comment]
OK. After upgrading to new Newtonsoft, etc... I am not getting any error messages.
On the other hand, the string "track.Name" is empty. 
No result?

**Comment by JohnnyCrazy** [comment]
Unauthenticated calls `UseAuth = False` are deprecated since 2017 by Spotify. (https://developer.spotify.com/community/news/2017/01/27/removing-unauthenticated-calls-to-the-web-api/). Will have to update the docs.

Use one of the provided authentication flows (https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyWebAPI/auth/) or provide the access token in a custom way

**Comment by JohnnyCrazy** [comment]
Also, please check `track.HasError()` and `track.Error` before fetching any fields...This error would have told you that you're anauthenticated.

**Comment by OneBobone** [comment]
Ok. yes pls update the docs.
