### ISSUE TITLE
Problem: Simple vb.net examples - Browser stuck waiting for "localhost"

### ISSUE THREAD

**Issue by OneBobone** [JohnnyCrazy/SpotifyAPI-NET#333]
It is evident that many are having problems getting started in vb.net with SpotifyAPI-NET.

There are too many variables: writing correct code, having the right libraries installed and having the right versions of these. On top of which is setting up Spotify dev as necessary and correcting previous typos that forum code snippets have replicated.

A very valuable suggestion to reduce complexity:
- make a copy of the start-up examples that you already have, but now in a vb.net version that you KNOW works.

Alternative:
- write your current C# examples in a such a way that you KNOW that a code translator will succeed in writing correct code (telerik / carlosag). It does not seem to work today. Perhaps due to elegant and compact coding?

Thankyou for (hopefully) a great .NET wrapper!
:-)

**Comment by JohnnyCrazy** [comment]
Hi,

I don't have interest in developing or maintaining a VB.NET Example. However, I'm up for PRs.

> writing correct code

Well, you have the C# code and VisualStudio does a great Job of showing you what methods and classes are available. It's up to the developer to write correct code.

> right libraries installed and having the right versions of these
 
Also an IDE thing. NuGet makes it simple and works out of the box in VisualStudio. The nuspec files specify which versions are needed and are also referenced on nuget itself.

> make a copy of the start-up examples that you already have, but now in a vb.net version that you KNOW works.

Like I said, I'm currently not familiar with VB.NET and I don't want to be in the future. If someone creates a PR, I will merge it.

> write your current C# examples in a such a way that you KNOW that a code translator will succeed in writing correct code (telerik / carlosag). It does not seem to work today. Perhaps due to elegant and compact coding?

I KNOW that this library can be used in VB.NET since at compile step, it will be compiled to CIL, which can be read and understand by any compatible language, including C#/VB.NET/F#.

**Comment by OneBobone** [comment]
@JohnnyCrazy no interest in the small suggestion above?

**Comment by OneBobone** [comment]
I have, with a large effort managed to get something to work thanks to @xTheChosen0ne.
Suggestion:
- If it is possible (I am not C# capable), re-write the Auth-methods by splitting them up in a clearer main and a event sub. This part is not translated correctly:
```
auth.AuthReceived += async (sender, payload) =>
    {
        auth.Stop(); // `sender` is also the auth instance
        SpotifyWebAPI api = new SpotifyWebAPI() {TokenType = payload.TokenType, AccessToken = payload.AccessToken};
        // Do requests with API client
    };
```
Thereby code converters can do a good enough job.

**Comment by OneBobone** [comment]
Thanks to @xTheChosen0ne, we now have a piece of code that works! Hooray!
But, (seee below the code)
```
    Private Shared spotifytrackliste As New List(Of Track)
    Public Shared spotifyWebApi As SpotifyAPI.Web.SpotifyWebAPI
    Private Shared clientID As String = "[HERE YOUR CLIENT ID]"
    Private Shared secretID As String = "[HERE YOUR SECRET ID]"
    Public Shared auth As SpotifyAPI.Web.Auth.AuthorizationCodeAuth

    Public Shared Sub WebConnect()
        auth = New SpotifyAPI.Web.Auth.AuthorizationCodeAuth(clientID, secretID, "http://localhost:8000", "http://localhost:8000", (Scope.PlaylistReadPrivate Or Scope.UserLibraryRead Or
                                                                 Scope.UserReadPrivate Or Scope.UserLibraryModify Or Scope.UserFollowRead Or Scope.UserFollowModify Or
                                                                 Scope.PlaylistModifyPrivate Or Scope.PlaylistModifyPublic Or Scope.UserModifyPlaybackState Or Scope.UserReadPlaybackState))
        auth.Start()
        auth.OpenBrowser()
        AddHandler auth.AuthReceived, AddressOf Auth_OnResponseReceivedEvent
    End Sub

    Public Shared Sub Auth_OnResponseReceivedEvent(ByVal sender As Object, ByVal payload As SpotifyAPI.Web.Auth.AuthorizationCode)
        Dim authCode As SpotifyAPI.Web.Auth.AuthorizationCode = payload
        Dim token As SpotifyAPI.Web.Models.Token = auth.ExchangeCode(authCode.Code).Result

        If (auth IsNot Nothing) Then
            spotifyWebApi = New SpotifyAPI.Web.SpotifyWebAPI With {
                .TokenType = token.TokenType,
                .AccessToken = token.AccessToken,
                .RetryErrorCodes = {429},
                .UseAutoRetry = True,
                .TooManyRequestsConsumesARetry = True,
                .RetryTimes = 100
            }
        End If
    End Sub

```
I am a bit curious to your journey. 
- what do you acheve in the last part of your code?
- You did not get the `ImplicitGrantAuth `method to work?

I managed to get your code to work on one machine but not on another:

```
Sub Main(ByVal Parms As Object)
    Try
        Dim auth As SpotifyAPI.Web.Auth.ImplicitGrantAuth = New SpotifyAPI.Web.Auth.ImplicitGrantAuth("clientID", "http://localhost:4002", "http://localhost:4002")
        AddHandler auth.AuthReceived, AddressOf AuthOnAuthReceived
        auth.Start()
        auth.OpenBrowser()
        Console.ReadLine()
        auth.Stop(0)
    Catch ex As Exception
        hs.writelog("Main", ex.tostring)
    End Try
End Sub

Sub AuthOnAuthReceived(ByVal sender As Object, ByVal payload As SpotifyAPI.Web.Models.Token)
  Try
        Dim _spotify = New SpotifyAPI.Web.SpotifyWebAPI With {.TokenType = payload.TokenType, .AccessToken = payload.AccessToken}
        hs.writelog("AuthOnAuthReceived", "_spotify")
        Dim profile As SpotifyAPI.Web.Models.PrivateProfile = _spotify.GetPrivateProfile
        hs.writelog("AuthOnAuthReceived", "profile")
        Dim track As FullTrack = _spotify.GetTrack("3R8lr1Y1kPgXEbnXkcMMlT") ' spotify:track:3R8lr1Y1kPgXEbnXkcMMlT
        Dim userPlaylists As Paging(Of SimplePlaylist) = _spotify.GetUserPlaylists("Bobone") '("1122095781")
        Dim myPlaylist As FullPlaylist = _spotify.GetPlaylist("3FvsM5XtjWJ6yi9AY3uvtj")

        For Each spotifyList In userPlaylists.Items
            'Debug.Print(spotifyList.Name)
        Next

        For Each spotifyTrack In myPlaylist .Tracks.Items
            'Debug.Print(spotifyTrack.Track.Name & vbCrLf)
        Next

        Debug.Print(myPlaylist.Tracks.Total & vbCrLf) 
        Debug.Print(myPlaylist.Tracks.Items.Count & vbCrLf)
    Catch ex As Exception
        hs.writelog("AuthOnAuthReceived", ex.tostring)
        End Try
    Environment.Exit(0)
End Sub
```
My production machine is and has to be different. I will be running the code in a HomeSeer3 environment, which is mostly up to date .NET. Lacking libraries have been added separately. The environment is not as debug friendly as a VS IDE. I can basically write data to a log and read errors.
The process is cumbersome but works for many other similar cases.

What happens is:

- code runs down to and including auth.Stop(0)
- the Google browser fires up and the authentication string looks correct
- https://accounts.spotify.com/authorize/?client_id=982b1c42409240cf8c4a86622176ab28&response_type=token&redirect_uri=http://localhost:4002&state=b9625d58&scope=&show_dialog=False
- it gets stuck waiting for local host
- AuthOnAuthReceived never fires
- no errors are reported

Comments:

- the firewall is shut down
- manual Spotify login has been done and password stored in some Spotify "cookie process". :-)
- what kind of logs can I look at for guidance?
- if i use the following interface on the same browser tab, it works:
https://rawgit.com/delight-im/exportify/master/exportify.html

**Comment by JohnnyCrazy** [comment]
Sorry for the late response here.

If you have problems with `localhost`, check if `127.0.0.1` is working for you. Some machines don't map localhost to 127.0.0.1.

If you have more questions, feel free to reopen/create another issue
