### ISSUE TITLE
Endless Waiting for Localhost

### ISSUE THREAD

**Issue by OneBobone** [JohnnyCrazy/SpotifyAPI-NET#337]
Still having trouble with the authentication procedure... It works on one machine, but not on my target machine:
- Chrome gets stuck with "Waiting for local host".
- no other apparent error reporting

http://localhost:4002 in both code and Spotify dev.
What is it waiting for?
Is the Console important? I am running w/o a visible console.
Using port 80 and 800 as webservers.

**Comment by JohnnyCrazy** [comment]
How can anyone help if you don't show some code, nor an Output...?

**Comment by OneBobone** [comment]
I would appreciate your help!
So, this code works on my "developer machine":
```
Sub Main(ByVal Parms As Object)
    Try
        Dim auth As SpotifyAPI.Web.Auth.ImplicitGrantAuth = New SpotifyAPI.Web.Auth.ImplicitGrantAuth("clientID", "http://localhost:4002", "http://localhost:4002")
        AddHandler auth.AuthReceived, AddressOf AuthOnAuthReceived
        auth.Start()
        auth.OpenBrowser()
        Console.ReadLine()
        auth.Stop(0)
    Catch ex As Exception
        hs.writelog("Main", ex.tostring)
    End Try
End Sub

Sub AuthOnAuthReceived(ByVal sender As Object, ByVal payload As SpotifyAPI.Web.Models.Token)
        Try
        Dim _spotify = New SpotifyAPI.Web.SpotifyWebAPI With {.TokenType = payload.TokenType, .AccessToken = payload.AccessToken}
        hs.writelog("AuthOnAuthReceived", "_spotify")
        Dim profile As SpotifyAPI.Web.Models.PrivateProfile = _spotify.GetPrivateProfile
        hs.writelog("AuthOnAuthReceived", "profile")
        Dim track As FullTrack = _spotify.GetTrack("3R8lr1Y1kPgXEbnXkcMMlT") ' spotify:track:3R8lr1Y1kPgXEbnXkcMMlT
        Dim userPlaylists As Paging(Of SimplePlaylist) = _spotify.GetUserPlaylists("Bobone") '("1122095781")
        Dim myPlaylist As FullPlaylist = _spotify.GetPlaylist("3FvsM5XtjWJ6yi9AY3uvtj")

        For Each spotifyList In userPlaylists.Items
            'Debug.Print(spotifyList.Name)
        Next

        For Each spotifyTrack In myPlaylist .Tracks.Items
            'Debug.Print(spotifyTrack.Track.Name & vbCrLf)
        Next

        Debug.Print(myPlaylist .Tracks.Total & vbCrLf) 
        Debug.Print(myPlaylist .Tracks.Items.Count & vbCrLf)
    Catch ex As Exception
        hs.writelog("AuthOnAuthReceived", ex.tostring)
        End Try
    Environment.Exit(0)
End Sub
```
My production machine is and has to be different. I will be running the code in a HomeSeer3 environment, which is mostly up to date .NET. Lacking libraries have been added separately. The environment is not as debug friendly as a VS IDE. I can basically write data to a log and read errors.
The process is cumbersome but works for many other similar cases.

What happens is:
- code runs down to and including auth.Stop(0)
- the Google browser fires up and the correct autentication string is used
- it gets stuck waiting for local host
- AuthOnAuthReceived never fires
- no errors are reported

Comments:
- the firewall is shut down
- manual Spotify login has been done and password stored in some Spotify "cookie process". :-)
- what kind of logs can I look at for guidance?

**Comment by OneBobone** [comment]
Moving discussion to https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/333
