### ISSUE TITLE
Authentication Example: api is null

### ISSUE THREAD

**Issue by ColinPollard** [JohnnyCrazy/SpotifyAPI-NET#338]
Noob question: I've been trying to implement a project using the spotifyapi.web.example example code. In the example, all of the main functionality is called from AuthOnAuthReceived, which calls printusefuldata with the parameter api. 
Within AuthOnAuthReceived, it creates a new SpotifyWebAPI, as a local variable, which I have changed to be a global. In debugging, api is set to a valid value, until the method returns to main, in which it is null. This isn't a problem for the example, however I would like to be able to wrap authentication into its own method, and use api in the entire program, rather than just AuthOnAuthReceived. I assume this is due to the multithreading, but I haven't been able to figure it out yet. Any help is appreciated.

**Comment by JohnnyCrazy** [comment]
Any code...?

**Comment by ColinPollard** [comment]
Sorry, I thought I attached this earlier. This is being used in a web app, and so the first method that runs is the void page load. This method works fine, and all of the authentication with spotify appears to work. The place that doesn't work is when we later on try to use the variable api, which is defined within the AuthOnAuthReceived Method.

`using SpotifyAPI.Web;
using SpotifyAPI.Web.Auth;
using SpotifyAPI.Web.Enums;
using SpotifyAPI.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace SpotifyWebApp
{
    public partial class SpotifyForm : System.Web.UI.Page
    {

        private static string _clientId = ""; //"";
        private static string _secretId = ""; //"";
        private static bool end = false;
        private static SpotifyWebAPI api; //Here is the global api variable, that is being set to null outside of the authonauth
        string searchTrack;
        private static Device SelectedDevice = null;




        protected void Page_Load(object sender1, EventArgs e)
        {
            Authenticate(); //This runs first, and has no problem opening spotify's authentication page, etc
        }

        protected void ListBox1_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        protected void SubmitButton_Click(object sender, EventArgs e) //This happens after the authentication has completely finished (web page okay to closed)
        {
            SelectDevice(0); // This throws a null api exception

            searchTrack = SearchTracks.Text;
            Paging<FullTrack> results = SearchTrack(searchTrack);
            playTrack(results.Items[0]);
        }
        
        
        public void AuthOnAuthReceived(object sender, AuthorizationCode payload)
        {
            AuthorizationCodeAuth auth = (AuthorizationCodeAuth)sender;
            auth.Stop();

            Token token = auth.ExchangeCode(payload.Code).Result;
            api = new SpotifyWebAPI //This is the place where we are attempting to set api as a global variable, but outside of this method, it does not appear to work
            {
                AccessToken = token.AccessToken,
                TokenType = token.TokenType
            };
            SelectDevice(0); //Calling anything on api within this method works fine
        }

        
        public void Authenticate()
        {
            Environment.SetEnvironmentVariable("SPOTIFY_CLIENT_ID", "1f943e38b30c4a378c284f1ba0bafbf9");
            Environment.SetEnvironmentVariable("SPOTIFY_SECRET_ID", "7c100ccbb9714e13948a788b943636e8");

            _clientId = string.IsNullOrEmpty(_clientId)
                ? Environment.GetEnvironmentVariable("SPOTIFY_CLIENT_ID")
                : _clientId;

            _secretId = string.IsNullOrEmpty(_secretId)
                ? Environment.GetEnvironmentVariable("SPOTIFY_SECRET_ID")
                : _secretId;

            AuthorizationCodeAuth auth = new AuthorizationCodeAuth(_clientId, _secretId, "http://localhost:4002", "http://localhost:4002",
                Scope.PlaylistReadPrivate | Scope.PlaylistReadCollaborative | Scope.AppRemoteControl | Scope.PlaylistModifyPrivate | Scope.PlaylistModifyPublic | Scope.UserReadPrivate | Scope.UserReadEmail | Scope.Streaming
                 | Scope.UserModifyPlaybackState | Scope.UserReadPlaybackState | Scope.UserReadRecentlyPlayed);
            auth.AuthReceived += AuthOnAuthReceived;
            auth.Start();
            auth.OpenBrowser();
        }
        

        private List<String> SearchTrackToString(Paging<FullTrack> Tracks)
        {
            List<String> output = new List<String>();
            int i = 0;
            do
            {
                Tracks.Items.ForEach(FullTrack =>
                {
                    output.Add(i + $"- {FullTrack.Name}");
                    i++;
                });
                Tracks = api.GetNextPageAsync(Tracks).Result;
            } while (Tracks.HasNextPage());

            return output;
        }

        private Paging<FullTrack> SearchTrack(string song)
        {

            song = song.Replace(" ", "+");
            SearchItem item = api.SearchItems(song, SearchType.Track);
            Paging<FullTrack> Tracks = item.Tracks;

            return Tracks;
        }

        private List<String> PrintDevices()
        {
            List<String> output = new List<String>();
            AvailableDevices devices = api.GetDevices();
            devices.Devices.ForEach(device => output.Add(device.Name));
      
            return output;
        }

        private Device SelectDevice(int input)
        {
            AvailableDevices devices = api.GetDevices();
            Device selectedDevice = devices.Devices[input];

            return selectedDevice;
        }

        private ErrorResponse playTrack(FullTrack input)
        {
            if (SelectedDevice == null)
            {
                throw new Exception("No Device Selected");
            }
            ErrorResponse error = api.ResumePlayback(SelectedDevice.Id, null, uris: new List<string> {input.Uri.ToString()}, "", 0);
            return error;
        }

        protected void SelectDeviceList_SelectedIndexChanged(object sender, EventArgs e)
        {

        }
    }
}`

**Comment by JohnnyCrazy** [comment]
Do you click the Submit Button after or before you did the whole auth part?

**Comment by JohnnyCrazy** [comment]
Basically, it has nothing to do with the API itself but rather with your HTTP/Web Framework or in general C#. Put watches on the variable, debug how and when this variable is set and find out why it is null at that point.
