### ISSUE TITLE
Chrome "Silent mode"?

### ISSUE THREAD

**Issue by OneBobone** [JohnnyCrazy/SpotifyAPI-NET#339]
Hi, Thx for a nice wrapper!

Two questions:
1) Is it possible to avoid getting Chrome to display a page? 
2) Automatically shut down when finished?

Bob

**Comment by Salzian** [comment]
Sounds like you're working in the context of ASP.NET.

In that case your problem is not linked to this wrapper. Please head over here for a solution for your problem: https://stackoverflow.com/questions/716494/stop-visual-studio-from-launching-a-new-browser-window-when-starting-debug

The first two answers will solve your problem.

**Comment by OneBobone** [comment]
Thank you very much for answering, I really appreciate it.
I am running in two different vb.Net environments with the same resulting Chrome windows/tabs. One is Visual Studio and the other is HS3. Both with the latest .NET framework.
My concern is not when I am debugging but when running the application, so I would need some sort of switch outside of VS.

I thereby understand that you do not have this issue?

**Comment by H4mm3rb0y** [comment]
Hey guys,
I had the same problem that my app always opened an tab that stayed open even after finishing the auth-process. This behavior was fixed by manually adding both NET APIs to my solution an not using the nuget-package. The program is still opening a tab, but its closed immediately.

**Comment by OneBobone** [comment]
Thanks for helping to move this forward!
That's interesting. On one machine with VS I installed the nuget-pakage.
On the other (production), I did not.
Both have these systems.
Could the choice of dll affect this?

**Comment by Gruhlum** [comment]
Are you talking about the browser page that opens during the auth process with the "You can close this now" message? Because that got fixed relatively recent (#334 ) I don't think there is an easy way to remove it completely.

**Comment by OneBobone** [comment]
Yes! 
I want to close "You can close this now".
:-)
My workaround is to identify the Chrome process and kill it, but I was hoping that it never needed to get opened as it takes CPU at a critical moment.

**Comment by JohnnyCrazy** [comment]
This should be implemented in current master. Will try to release a new official version tomorrow evening. Sorry for the delay

⁣BlueMail for Android herunterladen ​

**Comment by JohnnyCrazy** [comment]
4.0.1 was just released.

Regarding "silent mode": The best thing for desktop applications is to use `AuthorizationCodeAuth` and request clients to create a ClientID and ClientSecret here: https://developer.spotify.com/dashboard/applications/

With this approach, you just have to auth them once. Then store the `access_code ` and `refresh_token`. With this, you can always fetch a new `access_token` without a browser opening at all :)

**Comment by ColorTwist** [comment]
What exactly is the` 'access_code' `  is it `'payload.Code'`?
