### ISSUE TITLE
How to use GetFollowedArtists

### ISSUE THREAD

**Issue by gahujipo** [JohnnyCrazy/SpotifyAPI-NET#340]
I tried to output followed artists which a user follows. I took this example to start from: 
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web.Example/Program.cs

I've seen that the output of user's playlists can be achieved by using Paging:
```C#
Paging<SimplePlaylist> playlists = await api.GetUserPlaylistsAsync(profile.Id);
```
But it seem to me that, when doing
```C#
var followedArtistSync = api.GetFollowedArtists(FollowType.Artist); 
```
followedArtistSync.Artist contains a property of the type CursorPaging<FullArtist> and followedArtistSync.Artist.Items contain only the first 20 elements (obviously because of the default paging size of 20). But how to get the next page and/or using Paging here? 

My try with the async method here was: 
```C#
Paging<FollowedArtists> followedArtistsAsync = await api.GetFollowedArtistsAsync(FollowType.Artist);
```
 but that fails with the following error: 
```
Cannot implicitly convert type 'SpotifyAPI.Web.Models.FollowedArtists' to 'SpotifyAPI.Web.Models.Paging<SpotifyAPI.Web.Models.FollowedArtists>'
```

My current progress in that is: 

```C#
var followedArtistSync = api.GetFollowedArtists(FollowType.Artist); 
followedArtistSync.Artists.Items.ForEach(artist =>
{
    Console.WriteLine($"- {artist.Name}");
});
```

What am I missing here?

**Comment by JohnnyCrazy** [comment]
I justed pushed a new version, 4.1.0. You will be able to do the following (no error checking included):

```cs
var followedArtists = await api.GetFollowedArtistsAsync(FollowType.Artist);
while(true)
{
    Console.WriteLine(string.Join("\n", followedArtists.Artists.Items.Select((a) => a.Name)));
    followedArtists = await api.GetNextPageAsync<FollowedArtists, FullArtist>(followedArtists.Artists);
    if(!followedArtists.Artists.HasNext())
    {
        Console.WriteLine(string.Join("\n", followedArtists.Artists.Items.Select((a) => a.Name)));
        break;
    }
}
```

Important line is `await api.GetNextPageAsync<FollowedArtists, FullArtist>(followedArtists.Artists);`. Basically spotify doesn't return the cursor object directly, but wrapped inside an object under the key `artists`. So we have to tell the wrapper that it's really a `FollowedArtists` object, instead of `CursorPaging<FullArtist>`. Weird design by Spotify IMO.

Can you check if this works for you?

**Comment by gahujipo** [comment]
Yes, this works for me. 
Didn't realize earlier that they use another type of paging here. Cool way to implement that in your library by the way! 👍
