### ISSUE TITLE
Nuget - Update to latest version?

### ISSUE THREAD

**Issue by scgough** [JohnnyCrazy/SpotifyAPI-NET#341]
Hi! 
First of all - I love this API wrapper! Nice work.

Could the Nuget package be updated to the latest release please? The current version on there is 2.19.0 and the later/latest releases have some nice features I'd like to have access to. 

Even better if a new version could be released with the newest 20 commits included. 

Thanks!

**Comment by JohnnyCrazy** [comment]
Latest version is 4.0, have a look at the readme. The old package is deprecated, nuget however does not feature a deprecation tag system...
