### ISSUE TITLE
404 Error when trying to get playing track: Invalid Username

### ISSUE THREAD

**Issue by 0Neji** [JohnnyCrazy/SpotifyAPI-NET#349]
Hi,

I'm trying to do a really simple task, just trying to get my current playing track. This isn't anything fancy so just using `ClientCredentialsAuth`. However, when I do `api.GetPlayingTrack();` it returns a `404` with the error `Invalid username`.

Here's my code (client id and secret removed for privacy but validated):

    [HttpGet]
    [AcceptVerbs("GET")]
    public async Task<string> GetAuthToken()
    {
        string _clientId = "{CLIENT_ID}";

        string _secretId = "{SECRET_ID}";

        CredentialsAuth auth = new CredentialsAuth(_clientId, _secretId);

        Token token = await auth.GetToken();

        SpotifyWebAPI api = new SpotifyWebAPI() { TokenType = token.TokenType, AccessToken = token.AccessToken };

        PlaybackContext playingTrack = api.GetPlayingTrack();

        return "done";
    }

Thanks for any help in advance!

**Comment by JohnnyCrazy** [comment]
Have a look at: https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyWebAPI/auth/#auth-methods

CredentialsAuth doesn't support any user based endpoints. Basically just searching, getting tracks etc.
