### ISSUE TITLE
Push the latest version to nuget

### ISSUE THREAD

**Issue by qubbit** [JohnnyCrazy/SpotifyAPI-NET#35]
I started writing an application for Spotify, but when I wanted to setup Implicit Grant using the local web server, I could not pass the port number to the HTTP server. I can't use port 80 for this app because my critical IIS service uses it. I glanced over the code and it seems like the Github copy allows passing in a port number for the HTTP server, this is not the version that is pushed to nuget. Can you please push the latest to version to nuget?

Thanks

**Comment by JohnnyCrazy** [comment]
Done, updated the [Nuget-Package](https://www.nuget.org/packages/SpotifyAPI-NET/) and published a [new release](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.1)
