### ISSUE TITLE
auth.md outdated

### ISSUE THREAD

**Issue by BluezamX** [JohnnyCrazy/SpotifyAPI-NET#351]
The sample code given for ImplicitGrantAuth is not up to date with the version on NuGet (2.19.0). Start() and Stop() methods have had a name change, and the OpenBrowser() method is non-existant.

**Comment by JohnnyCrazy** [comment]
This Nuget version is deprecated, as listed on https://www.nuget.org/packages/SpotifyAPI-NET/

Use the packages which you can find in the readme

https://www.nuget.org/packages/SpotifyAPI.Web/
https://www.nuget.org/packages/SpotifyAPI.Web.Auth/
