### ISSUE TITLE
SpotifyAPI.Web.Auth version 4.1.1 missing in NuGet

### ISSUE THREAD

**Issue by richardversluis** [JohnnyCrazy/SpotifyAPI-NET#359]
It looks like version 4.1.1 of `SpotifyAPI.Web.Auth` is not pushed to NuGet. I'm hitting a specific "bug" (https://github.com/JohnnyCrazy/SpotifyAPI-NET/commit/94d84e1f9d6066ae79757677fdf1e849c8e0cc15#diff-a03e6800070a0373afa6c28a7ad5641bR58) that looks fixed in [release 4.1.1](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/4.1.1) but not yet available in NuGet. Is this correct?

**Comment by JohnnyCrazy** [comment]
Will be looked into in some hours once I have access to a computer

**Comment by JohnnyCrazy** [comment]
4.1.1 is available on NuGET, although implicit .NET 46(1) support has been dropped in favor of .NET standard 2.0, but I don't think this should cause problems

**Comment by richardversluis** [comment]
Thanks for you fast reply :)

Could it be there went something wrong with packaging? It looks like an old version because the `ImplictGrantAuth` typo is back (#320).

**Comment by JohnnyCrazy** [comment]
Mh, true, I kicked in the automatic generation of 4.1.2, sorry for the inconvenience :/

**Comment by JohnnyCrazy** [comment]
4.1.2 is available via NuGET now :)

@richardversluis can you confirm it works?

**Comment by richardversluis** [comment]
Thanks, works! Much appreciated. The only thing was that I had to bump `EmbedIO` from `2.2.7` to newest available, because of a method not found in `EmbedIO`. The nuspec file needs a version bump to `2.9.1` I think:

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/76dc55352706df4962e99bc489d9d5aa7926eb33/SpotifyAPI.Web.Auth/SpotifyAPI.Web.Auth.nuspec#L22

**Comment by JohnnyCrazy** [comment]
Got it, I think I can swap the nuget pack command to use the cjspro file to generate the dependencies, that way no manual bump is required, gonna look into it
