### ISSUE TITLE
[Feature request] Add support for proxy settings in authorization flows

### ISSUE THREAD

**Issue by dsafa** [JohnnyCrazy/SpotifyAPI-NET#360]
The `SpotifyWebAPI` class has support for `ProxyConfig` but the authorization classes (e.g `AuthorizationCodeAuth`) don't have support for it. It would be awesome if support for proxies could be added to them.

**Comment by JohnnyCrazy** [comment]
Hi,

All Auth flows should have a public `ProxyConfig` property now. Will be released in 4.2.0

Thanks for the issue! If you run into any problems or have further feature requests, please report :)

**Comment by dsafa** [comment]
Awesome. Thanks!
