### ISSUE TITLE
[FEEDBACK] Who uses SpotifyAPI-NET? Do you want something changed?

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#362]
Hey 👋 

I would like to know who maintains an application/project/library, which utilizes this library somehow. If you agree, I would also like to add this project to the [Projects](https://johnnycrazy.github.io/SpotifyAPI-NET/#projects) page. This helps newcomers to see some real-world examples and maybe a better start :)

Also, if you have some time left for the following questions:

1. Are you generally happy with the library? Or is there sth which can be improved?
2. What features would you like to see, if any?

Thanks for your time!

**Comment by Gruhlum** [comment]
I use it. My app basically replaces the spotify client, adds a rating system and automatically plays songs based on those ratings. [Screenshot](https://imgur.com/u4pQbos)
Unfortunately I don't have a public repo because I use AuthorizationCodeAuth and don't know how I would protect my clientSecret, and also my code is quite a mess given I started it 4 or 5 years ago as my first project.

To your other questions:
1. No complains.
2. There are many features I would like to see but they need to be added by Spotify first, like events for track ended, player paused (things we already had before they killed the localAPI), the total times a track has been played globally, information from the "about" page. I doubt they will add new features any time soon though.

**Comment by Tobias1979** [comment]
Hi JohnnyCrazy,
thanks a lot for your efforts on SpotifyAPI.
I have just now started using it and ran into issue that given limit of 50 for GetArtistsAlbums does not fit for me.
Can this be extended?
Best regards
Tobias

**Comment by ta264** [comment]
I'm just looking into using it. It would be great if `SpotifyWebAPI` implemented a complete interface e.g. `ISpotifyWebAPI` so that responses could be easily mocked up for testing.

**Comment by cfernandezGAD** [comment]
Hi, is it posible to use multiple scopes while getting auth?

**Comment by JohnnyCrazy** [comment]
Did you have a look at the example @cfernandezGAD ? 

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web.Example/Program.cs#L31

@ta264 will have a look at possible solutions, thanks!

**Comment by cfernandezGAD** [comment]
Great! @JohnnyCrazy  thank you very much. Sorry for the obvious question, i just couldn't find it in the documentation.

**Comment by catara** [comment]
using it to maintain a library of songs(7'000+ out of 50'000 available at http://customsforge.com) to practice guitar on PS3/Mac/PC in Rocksmith 2014
(Track no, Covers and year retrieval to make more consistent/accurate when loading "Custom" DLCs in the game)
https://github.com/catara/rocksmith-custom-song-toolkit

**Comment by dsafa** [comment]
Here to say great work! Been using it since the start of my project.

1. No complaints from me.
2. Realtime player updates would be nice but it seems Spotify still doesn't want to expose any api 😅

**Comment by JohnnyCrazy** [comment]
Thanks @catara and @dsafa (Also have  installed audio-band, nice job 👍 )

Do you mind if I add your projects to the list at https://johnnycrazy.github.io/SpotifyAPI-NET/#projects ?

**Comment by dsafa** [comment]
@JohnnyCrazy Feel free

**Comment by OneBobone** [comment]
Nice job!

The API is used to maintain playlists and is used in an automation on a daily basis.
The need arose when libspotify changed a few years ago and destroyed playlist updates in my Nuvo MPS4. I have mended it in a HomeSeer automation environment with your API.
No complaints after passing the (unnecessary) hurdles regarding authentication in VB.NET.

**Comment by rollersteaam** [comment]
Can't believe it's been an entire year since I first started using SpotifyAPI-NET. Just a great library in general, and you had a great response to the tragedy caused by Spotify shutting off the local API in like August of last year.

There really aren't any serious complaints from me, this has been a reliable library for a long time. I would say areas where I've had to fill in for a lot of work for the library are in these areas:
1. Detecting when auth has been lost if a user's computer had been asleep for a while.
    - It's not easy for us to detect and deal with failed authorization on requests. If the life cycle could be streamlined so that it _virtually_ appears as never having been lost in almost any state, that could be a really cool addition, probably the most valuable on this list.

2. Detecting when a song has changed on Spotify, and wasn't done through my music player.
    - The workaround being a polling-based solution. Checking every 500ms for instance, and predicting when a song is going to change based on time deltas. When I detect the song change through my polling solution, I emit an event across my application. Ideally it would be sick if that was 'out of the box'.

2. Retrieving the album art as an Image type.
    - There is probably good reasons why you haven't done this here, as System.Drawing is not on NET Standard 2.0, but there is a library that brings Image to NET Standard 2.0 called System.Drawing.Common that you might want to look into.
    - But even in spite of that, Xamarin Forms cannot use that Image type and has to use an ImageSource class to which you can pass in a MemoryStream of the byte[] of the Image.
    - So you could just make a way to retrieve album art in byte[] form. But it's not hard for a user to make, it's just that then the user needs to consider failure states and how to deal with them.

3. Users have to do "manual" pagination.
    - Changing `Paging<T>` to automate that process and abstract it behind maybe an `IEnumerable`, for things such as `SearchItems()` and `GetUserPlaylists()` would be cool. There's a dual reward here because sometimes it's unclear in parts of the API where pagination is actually required (unless I'm just being dumb sometimes). But again, it's just making the code cleaner on the user's end which is apparently a recurring theme in these suggestions lol

So yeah as you can tell, really nothing major at all.

The project I used this on is my app Emotion https://www.r-saam.co.uk/emotion/ Unfortunately I'm planning on trying to go commercial with this, so there is no open source repo. I've had success with this library on both Windows Forms and Xamarin Forms, which shows just how good it is.

**Comment by JohnnyCrazy** [comment]
Thanks for your input and feedback @rollersteaam !

Regarding your points:

1. I agree that authentication is a tricky problem to keep in sync. I will think about a possible solution. Maybe an event callback when authentication has been expired while a call was made.

2. Yup, sadly not in my hands to decide. If you need a way to get live updates for a single user (it's not possible for multiple users), I found an inofficial way. You can shoot me a mail if you want to know more.

3. URL seems enough for the usecase of this wrapper, people can implement libs for converting it.

4. I'm acutally testing this, maybe we can get something like this working:

```
foreach(var track in _spotify.GetPlaylistTracks(...).AsEnumerable()) {
  Console.WriteLine(track.Name)
}
```

**Comment by Inzaniity** [comment]
I've been using your library even before the local api was shut down, and now I finally managed to get to using the webapi. My app, [Songify Slim](https://github.com/Inzaniity/Songify) , is aimed for live streamers to show the current song in text files and also uploads the song information for use with common chat bots. The webAPI stuff is not yet in the release version but in the code.

Right now I just dipped into the webapi stuff. So far no complaints!

**Comment by MagicMau** [comment]
I too am a very happy user of this library for my [EliteG19s app](https://forums.frontier.co.uk/threads/elite-g19s-companion-app-with-simulated-space-traffic-control.226782), a companion app for the game Elite Dangerous. 

I'll look into getting the Spotify specific code in a Github repo as it took me a little while to get the authorization flow working in a Windows Forms app and my trial and error might be useful for others.

But thanks a lot for your hard work! I had almost given up hope when libspotify didn't work for me anymore.

**Comment by orestescm76** [comment]
thanks for this awesome library! very useful for my project
how should i credit you?

**Comment by NADER11NDEU** [comment]
Used it on my arduino project, awesome api mate. Keep it up ! 
https://github.com/NADER11NDEU/ARDUINO-Spotify-Remote-Control

**Comment by JohnnyCrazy** [comment]
@Inzaniity @MagicMau @NADER11NDEU  Thanks guys, added it to the project list

@orestescm76 In the end, https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/LICENSE is a good entry point. A link to this repo and its license itself should be sufficient.

**Comment by orestescm76** [comment]
@JohnnyCrazy in my README.md?
when i have it implemented i'll do it
also inside the program i'll write your name and my personal thank you when i have this implemented

**Comment by novatorem** [comment]
Your wrapper basically carried my application: [https://github.com/novatorem/Melodify](https://github.com/novatorem/Melodify)
Thanks for taking the time to create and maintain it!

> Are you generally happy with the library? Or is there something which can be improved?

Honestly, yeah, it's a nice library to have used. Improvement would just be more examples in the docs to get an faster jump start. Although, when I started using this it didn't have the projects page it does now. If I saw how other people did it, it'd have been easier implementing certain API calls.

**Comment by Afonsof91** [comment]
Just an awesome library!
Can you check why it isn't possible to update a playlist and set an empty description?

**Comment by JohnnyCrazy** [comment]
Could be a bug @Afonsof91, will check tomorrow and open an issue if thats the case. Thanks for the feedback

**Comment by JohnnyCrazy** [comment]
@Afonsof91 It's a known issue upstream at spotify: https://github.com/spotify/web-api/issues/1011

Since it has been unresolved since Sep 2018, you could try bumping it, but nothing I can do here :/

**Comment by Afonsof91** [comment]
Thanks so much.
I'll follow the issue too.

Atentamente,
Fernando Afonso

**Comment by DaniLecx** [comment]
Amazing library ! Do you think you could support Android and iOS with Xamarin?

**Comment by JohnnyCrazy** [comment]
@DaniLecx I'm currently working on V6, will have a look at Xamarin 👍

**Comment by JohnnyCrazy** [comment]
Thanks for all the feedback guys!

Just a heads up, V6 has been released and tackles a lot of issues which have been discussed in the past, like automatic token retrival, automated pagination and better testability. Also, support for all major platforms, including Xamarin @DaniLecx ! If you would give it a try and provide further feedback in #451 , that would be amazing! 🙏 

I will close this issue for now. Still, if you have a cool project you want to see in our [showcase](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/showcase), feel free to send a PR.

Also, ff you have more general feedback/problems/suggestions, feel free to open another issue.
