### ISSUE TITLE
Support for Spotify Bulk API

### ISSUE THREAD

**Issue by daviddassau** [JohnnyCrazy/SpotifyAPI-NET#364]
Hello! I am loving your C#/.NET Spotify wrapper so far!

I was wondering, though, if you by chance added support for the Enhanced Bulk API? I wasn't sure if you decided not to include support for it, since it's not Spotify's main API, and it's only available to labels and distributors.

Thanks in advance!

**Comment by JohnnyCrazy** [comment]
Well, it's hard to create/maintain a functionality which is not provided to non label/distributor people. Looking at the FAQ, they have a very strict policy and I'm not even sure a public API Wrapper for this would be supported by their Terms of Service

FAQ Excerpt:

![image](https://user-images.githubusercontent.com/3109892/62148958-fbf1b280-b2fa-11e9-9212-52ffa5bac7af.png)

So I'm 90% sure it will not be supported ;)

**Comment by daviddassau** [comment]
Ok, thanks anyways!

**Comment by JohnnyCrazy** [comment]
Your welcome, but if there will be any additions to the Web API or another new API, I'm aiming to support it 100%!
