### ISSUE TITLE
ImplicitGrantAuth doesn't close browser tab

### ISSUE THREAD

**Issue by M1S2** [JohnnyCrazy/SpotifyAPI-NET#365]
Hi and thank's for your great project. 
I'm successfully using it to control Spotify from my application.

I'm using the ImplicitGrantAuth flow for authentication. The only thing that is really annoying is the browser tab that stays open in Chrome on authentication. Since release 4.0.1 you've included a JS function that tries to close the tab. This seem not to work for me because the tab stays open.

In the SpotifyAPI.Web.Auth.AuthUtil.OpenBrowser() method you only open the url using the default browser. Is it possible to use EmbedIO or something similar instead to navigate to the url so that Chrome isn't even involved?

**Comment by JohnnyCrazy** [comment]
Hi, the TAB doesn't close because it's a restriction of the browser, it only works in rare cases.

Basically, because the windows was **not** opened by JS, JS is also unable to close it. 

However, you can use `auth.GetUri()` and pass it to whatever browser you want. Maybe an embedded WeView. Up to you, but I didn't experiment with it yet.

**Comment by M1S2** [comment]
Thanks for your reply. 
I tried to use the `System.Net.WebClient.DownloadString()` method with the uri from `auth.GetUri()` but this didn't work. It only downloads the html content of the login form.
I also tried the `System.Windows.Forms.WebBrowser` to navigate to the uri. This also doesn't seem to work because the AuthReceived event isn't fired.
Is it correct that the browser needs to be able to execute java script during login procedure?
Do you know another component that I can use instead of Chrome?

**Comment by JohnnyCrazy** [comment]
* Embedded Chromium
* CefSharp 

Basically "embed browser winforms c#" gives some good hints on google

**Comment by JohnnyCrazy** [comment]
Feel free to comment again if you still need more input
