### ISSUE TITLE
Add total_tracks to SimpleAlbum?

### ISSUE THREAD

**Issue by stevenwdv** [JohnnyCrazy/SpotifyAPI-NET#366]
While making search query, I saw that the album also contains a `total_tracks` (integer) field. For some reason this is [not documented](https://developer.spotify.com/documentation/web-api/reference/object-model/#album-object-simplified), but I think it can still be useful. Can you add support for this? Thanks for making this API!

**Comment by JohnnyCrazy** [comment]
Is it in every result? If so, I'm open for a PR :)

**Comment by stevenwdv** [comment]
I think this might be my first PR on GitHub :)
