### ISSUE TITLE
Clear code suggestion

### ISSUE THREAD

**Issue by stevenwdv** [JohnnyCrazy/SpotifyAPI-NET#368]
Did you know you can set the naming startegy in the JSON serializer so that you don't have to specify `[JsonProperty("...")]` each time?

```csharp
new JsonSerializer
{
    ContractResolver = new CamelCasePropertyNamesContractResolver
    {
        NamingStrategy = new SnakeCaseNamingStrategy()
    }
};
```

Alternatively you can also set it at the top of a class:
```csharp
[JsonObject(NamingStrategyType = typeof(SnakeCaseNamingStrategy))]
class ...
```

**Comment by JohnnyCrazy** [comment]
Yup, found out about it once this was already in place for every model 😅 

For now, it's not a big deal since new fields are added very rarely. But for the next big refactor, we should take it into account.

**Comment by JohnnyCrazy** [comment]
v6 now includes the the correct `SnakeCaseNamingStrategy` for Newtonsoft.JSON.

If you have more feedback/problems/suggestions, feel free to reply here or open another issue!
