### ISSUE TITLE
Following Basic Usage on the documentation page doesn't return the track's name

### ISSUE THREAD

**Issue by FantusDev** [JohnnyCrazy/SpotifyAPI-NET#370]
I'm looking to creating my own application using this API but have had several issues and decided to just follow the documentation until that didn't work either.
I'm using .net 4.7.2 on a WPF application
My code is as follows
```
class Program
    {
        private static SpotifyWebAPI _spotify;

        public static void Main()
        {
            App.Main(); // Run WPF startup code.
            _spotify = new SpotifyWebAPI()
            {
                UseAuth = false, //This will disable Authentication.
            };
            FullTrack track = _spotify.GetTrack("3Hvu1pq89D4R0lyPBoujSv");
            Console.WriteLine("Track: " + track.Name); //Yeay! We just printed a tracks name.
        }
    }
```
I've tried changing around the URI for the _spotify.GetTrack but it still returns just
Track:

**Comment by JohnnyCrazy** [comment]
Sorry, this is due an outdated documentation. Spotify does not allow unauthorized access to the API. I've updated the docs:

https://johnnycrazy.github.io/SpotifyAPI-NET/web/getting_started.html#basic-usage

Also, please have a look at [Error-Handling](https://johnnycrazy.github.io/SpotifyAPI-NET/web/getting_started.html#error-handling). This would've given you some hints why it's not working ;)
