### ISSUE TITLE
Question : can we download a track as mp3 by example, and then play it !

### ISSUE THREAD

**Issue by vd3d** [JohnnyCrazy/SpotifyAPI-NET#371]
Hi,

I wish to browse my playlist and then download my tracks locally. Then I wish to play them with internet connection.

Is it possible ?

For now I have the "PlaylistTrack" and but I don't know how to retrieve the track as a file ?

**Comment by JohnnyCrazy** [comment]
No, not possible, this is just for the spotify web api: https://developer.spotify.com/documentation/web-api/

**Comment by vd3d** [comment]
Thanks,

But so, how to play a track then ?
