### ISSUE TITLE
Could all DateTime.Now properties get changed to DateTime.UtcNow

### ISSUE THREAD

**Issue by nwalser** [JohnnyCrazy/SpotifyAPI-NET#377]
Hello

When saving/reading at database from different servers in the world I get the error that the time reference is not the same from different servers. Therefore sometimes a [token ](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web/Models/Token.cs)is outdated even if he is valid and vice versa because he uses local time in creation and comparison.

Please let me know if this is even possible or if there is a good workaround. (other than always converting from local time to UTC when saving to database)

**Comment by JohnnyCrazy** [comment]
Hi,

That would be a very breaking change, we could consider it for `5.0.0` but I'm not sure if it benefits most of the users.

How do you check if the token is expired?

**Comment by nwalser** [comment]
Hi,

At the moment i am checking the validity of the token with the create date in my database. Not via the function provided within the token class.

But i would actually like to do it the official way.

**Comment by JohnnyCrazy** [comment]
Hi,

I decided to not go for a change in an upcoming release because the benefits don't justify this kind of breaking change. If people really need UTC Timestamps, you can create a wrapper class around token which updates the timestamp to UTC.

**Comment by nwalser** [comment]
Thank you for considering it!

Yes its an easy solve if you create a wrapper class around the token class.
