### ISSUE TITLE
Got a working UWP example using SpotifyAPI-NET, where to put it?

### ISSUE THREAD

**Issue by Saik19922** [JohnnyCrazy/SpotifyAPI-NET#383]
Hey @JohnnyCrazy ,

I've fiddled with your Lib for a bit now and got it to work for UWP - with a couple of con's atleast. But if I'm not mistaken for now it's the appropriate way of doing that for now. I made a repo with my example - if you want to you can link it somewhere in your examples/docs.

Here's the link: https://github.com/Saik19922/UWP_SpotifyAPI-NET_Example

Thanks for your work on the Lib so far, making my life easier ;)

**Comment by JohnnyCrazy** [comment]
Hi @Saik19922 

I will have a look at it in the next days, maybe we can add it as another example in this repo if you're interested in it. Else, we can also put it in the docs :)

**Comment by JohnnyCrazy** [comment]
Sorry for the delay. I invested some more time into UWP with the upcoming release of v6 and the tight security model around localhost/loopback is making it impossible to create a local server for OAUth2 responses. The only way to run a local server is your way, but it is a lot of setup for a simple functionality.

**But**, protocol registrations to the rescue! UWP Apps can easily register so-called protocols, which allows other applications (like browser) to open the app with a specific uri (like `spotifyapi.web.oauth://token/`). This works fairly well and provides a nice ux. Custom protocol uris are also supported by spotify's redirect uris.

![image](https://user-images.githubusercontent.com/3109892/82198706-f7839e00-98fc-11ea-809f-3b74d06bf8a5.png)

You can see a full example here https://github.com/JohnnyCrazy/SpotifyAPI-NET/tree/v6/SpotifyAPI.Web.Examples/Example.UWP (Note it's using v6 of the spotify api, but v5 can be incoporated in the same manner)

@Saik19922
