### ISSUE TITLE
Can't suddenly pull followed playlists?

### ISSUE THREAD

**Issue by mrdobing** [JohnnyCrazy/SpotifyAPI-NET#385]
Is this just my app or has anyone elses app stopped pulling user's followed playlists?
My code hasn't changed and now I've realised none of my followed/friend's playlists are showing up (only my created) with the following:

`Paging<SimplePlaylist> userPlaylists = api.GetUserPlaylists("USERNAME");`

Has spotify changed anything?
I've tested this on ImplicitGrant and CredentialsAuth. Also scope is defaulted to userPrivate which is what it's always been when it worked?

Can someone try reproduce please?

**Comment by JohnnyCrazy** [comment]
Hi,

Do you still have this problem? Did you check for error responses?

**Comment by novatorem** [comment]
I'm trying this out now and can't seem to access the user followed playlists. Did anyone else experience this as well? Any workarounds?
