### ISSUE TITLE
Xamarin macOS: auth with error "invalid_client"

### ISSUE THREAD

**Issue by Suplanus** [JohnnyCrazy/SpotifyAPI-NET#393]
Hi,

I am trying to get the API working on macOS under Xamarin.Forms.
Looks good that the calls are made... But with this code, I get errors by loading the token:

```csharp
CredentialsAuth auth = new CredentialsAuth(clientSecret, clientID);
Token token = await auth.GetToken(); // todo: The token.AccessToken is null
_spotify = new SpotifyWebAPI()
{
    AccessToken = token.AccessToken,
    TokenType = token.TokenType
};
```

Error: "invalid_client"
Description: "Failed to get client"

In other Issues i saw that Xamarin is running, so i think its on my side.
The Application in Spotify exists, check the client id & secret. Redirect URL is empty, i think i dont need this for `CredentialsAuth`.

**Comment by JohnnyCrazy** [comment]
This line

```
CredentialsAuth auth = new CredentialsAuth(clientSecret, clientID);
```

should be

```
CredentialsAuth auth = new CredentialsAuth(clientID, clientSecret);
```

Did you find this order somewhere in the docs?

**Comment by Suplanus** [comment]
🤦‍♂ 
Shame on me... Looking at it but dont saw it...

I checked the docu again, and its my fault.

Thanks for the quick help (staring at it for two hours).
