### ISSUE TITLE
Question regarding refresh token with AuthorizationCode Auth

### ISSUE THREAD

**Issue by BluTree** [JohnnyCrazy/SpotifyAPI-NET#397]
Hello, 
I was trying to refresh the access token while using the Authorization Code Auth method but I don't really see how I do this.
Since there's nothing about this auth on the docs, I am a little lost.

**Comment by JohnnyCrazy** [comment]
Hi @BluTree 

I just updated the docs, sorry for the missing info!

https://johnnycrazy.github.io/SpotifyAPI-NET/auth/authorization_code.html#token-refresh
https://johnnycrazy.github.io/SpotifyAPI-NET/auth/getting_started.html
