### ISSUE TITLE
Missing method (?) - Get Followed Artists

### ISSUE THREAD

**Issue by scream4-me** [JohnnyCrazy/SpotifyAPI-NET#401]
Hi

There is a method that I cannot seem to find in the SpotifyAPI-NET which I need in a project. The method is Get Followed Artists method (https://developer.spotify.com/documentation/web-api/reference/follow/get-followed/). Is it missing or is it just me having problems finding it?

Regards 
/scream4me

**Comment by JohnnyCrazy** [comment]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/f4b3e9fe401b4979a1e6af8635dad9e0b87dfaf8/SpotifyAPI.Web/SpotifyWebAPI.cs#L621-L634

**Comment by scream4-me** [comment]
Hi

Thanks for your quick reply. As I thought, it was there but I missed it. I was looking at the docs at https://johnnycrazy.github.io/SpotifyAPI-NET/web/follow.html and didn't see it.

Keep up the good work with SpotifyAPI-NET!

/scream4me

**Comment by JohnnyCrazy** [comment]
Ah, yea, it's missing there. Gonna add it, thanks :)
