### ISSUE TITLE
Error: 'track_number' is not a member of 'SpotifyAPI.Web.Models.FullTrack'.

### ISSUE THREAD

**Issue by OneBobone** [JohnnyCrazy/SpotifyAPI-NET#402]
Very strange?
It works for tracks in Spotify's web console. E.g. 6ZEYvUSgON3J5Qe1RYi3Jo
and in my api requests immediately preceding the error , I can get name and uri
```
spotifyTrack.Track.Name
spotifyTrack.Track.Uri
### but not:
spotifyTrack.Track.track_number
```

Many thanks for any ideas.

**Comment by OneBobone** [comment]
Solved it:
track_number = tracknumber

**Comment by OneBobone** [comment]
Is the track number comig out of "tracknumber" correct?
I think not! Please check.

**Comment by JohnnyCrazy** [comment]
Is this solved? If not, please post the code, the error is not enough. And also state what are you expecting and what is the real case.

**Comment by OneBobone** [comment]
As far as I understand from their website, the Spotify API spells the variable "track_number".
That does not work with your nice project where you need to spell it "tracknumber" to get any results.
(That the enumeratio of tracks of an Album starts on 0 is also somewhat confusing, but understandable.)

**Comment by JohnnyCrazy** [comment]
Every field in the response models of spotify is converted to PascalCase. So you will have to use `track.TrackNumber`.
