### ISSUE TITLE
Use with Xamarin Media Manger to Stream Song

### ISSUE THREAD

**Issue by aherrick** [JohnnyCrazy/SpotifyAPI-NET#406]
Hello, is it possible that once I obtain the HREF to a Track to use https://github.com/Baseflow/XamarinMediaManager to Stream the track? Would I have to pass access token some how?

Trying to just use Client Credentials (my apps client id and secret)

**Comment by JohnnyCrazy** [comment]
Hi @aherrick 

Sorry for the late response.
It's not possible to receive a raw audio stream with the Web API. There is a streaming SDK for the browser or mobile platforms, but they also don't allow to receive the "raw" stream, only a DRM protected one.
