### ISSUE TITLE
What versions of the api are still working for AuthorizationCodeAuth method

### ISSUE THREAD

**Issue by jwallet** [JohnnyCrazy/SpotifyAPI-NET#411]
Hey there,

Just checking out if older version are still working/supported with `AuthorizationCodeAuth` method ?
I'm using 4.0.0 .Web and .Web.Auth
It used to work a long time without touching the class and now it stopped working, the api is not able to retrieve to current song, always `null`. But the step before still works, I'm still able to authorize the app on my spotify-dev account and get `you can close this page now`

```
public SpotifyAPI(string clientId, string secretId, string redirectUrl = "http://localhost:4002")
{
    _clientId = clientId;
    _secretId = secretId;

    if (!string.IsNullOrEmpty(_clientId) && !string.IsNullOrEmpty(_secretId))
    {
        var auth = new AuthorizationCodeAuth(_clientId, _secretId, redirectUrl, redirectUrl,
            Scope.Streaming | Scope.PlaylistReadCollaborative | Scope.UserReadCurrentlyPlaying | Scope.UserReadRecentlyPlayed | Scope.UserReadPlaybackState);
        auth.AuthReceived += AuthOnAuthReceived;
        auth.Start();
        auth.OpenBrowser();
    }
}
```
```
private async void AuthOnAuthReceived(object sender, AuthorizationCode payload)
{
    _authorizationCodeAuth = (AuthorizationCodeAuth)sender;
    _authorizationCodeAuth.Stop();

    _token = await _authorizationCodeAuth.ExchangeCode(payload.Code);

    // remember when to renew the 60 minutes token (10 minutes upfront)
    _nextTokenRenewal = DateTimeOffset.UtcNow.AddSeconds(_token.ExpiresIn).AddMinutes(-10);
}
```
```
private async Task<SpotifyWebAPI> GetSpotifyWebAPI()
{
    if (_token == null) return null;

    if (DateTimeOffset.UtcNow >= _nextTokenRenewal)
    {
        _token = await _authorizationCodeAuth.RefreshToken(_token.RefreshToken);
    }

    return new SpotifyWebAPI
    {
        AccessToken = _token.AccessToken,
        TokenType = _token.TokenType
    };
}
```
and I use it this way , `Item`, is always `null` while playing a track.
On spotify-dev website, my app `redirectURI` is `http://localhost:4002`
```
var api = await GetSpotifyWebAPI();

if (api == null) return false;

var playback = await api.GetPlaybackAsync();

if (playback.HasError() || playback.Item == null)
{
    // item always null
}
```

SpotifyAPI was the reason I needed to upgrade to recent .NET framework and removed support on Vista. Since 4.2.0 is on .NET Standard 2.0, I don't need to offer support on other platforms or ask user to install more .NET packages to support the SpotifyAPI. I will prefer to remove it at this point and work without it.

**Comment by JohnnyCrazy** [comment]
Is there an error in the response?

**Comment by jwallet** [comment]
no
![image](https://user-images.githubusercontent.com/23088305/72223488-5c894a80-353d-11ea-8ec0-27260ac2a469.png)

**Comment by JohnnyCrazy** [comment]
And the token + type is correct?

**Comment by jwallet** [comment]
looks good to me 
![image](https://user-images.githubusercontent.com/23088305/72223547-0537aa00-353e-11ea-83ea-886bedffb1af.png)

**Comment by JohnnyCrazy** [comment]
So maybe a weird question, but did you actually playback something when doing the request? With the correct account?

I just tested it, I receive the same empty response simpy when nothing is played. Once I opened spotify and played sth, it worked.

**Comment by jwallet** [comment]
Yes Bob Dylan Tangled Up in Blue is playing on Spotify Store App
I'm debugging with Spotify from the Windows Store. Does the Spotify-Dev platform still supports it, or just the Windows App exe and/or WebPlayer open.spotify.com ?

**Comment by jwallet** [comment]
oh shit user isssue I think happens, I think I messed up my login and log into the wrong account, I have `w1zik` and `wizik` accounts. i'm updating soon this response...

**Comment by JohnnyCrazy** [comment]
Yea 90% sure it's that. If nothing is played, an empty object is sent by the API. Thus, the object has default values.

![img](https://i.johnnycrazydev.de/u0fLDJobii01PWRQN4L~0)

**Comment by jwallet** [comment]
that was it
![image](https://user-images.githubusercontent.com/23088305/72223682-a83cf380-353f-11ea-8599-e3b1c5b33151.png)

thanks by the way for that quick support, really appreciated it. I'm disappointed of myself for not finding it before posting hahaha thanks again

**Comment by JohnnyCrazy** [comment]
Your welcome, we all had that happening and we will in the future! :)

If you have any other issues/questions, feel free to open another issue 👍

**Comment by JohnnyCrazy** [comment]
BTW @jwallet , is it okay for you if I gonna add spy-spotify to the list @https://johnnycrazy.github.io/SpotifyAPI-NET/#projects ?

**Comment by jwallet** [comment]
I've seen this list before, when you started gathering projects that uses your API, but I did not added Spytify because it violates the Spotify TOS and it's probably bad for your API to share it. Even if Spytify does not interact directly with Spotify but with the WASAPI just like Audacity does. So, if you want to add it, feel free to do it ;)

**Comment by JohnnyCrazy** [comment]
That's no issue from my side; there is no affiliation between me and spotify so I don't see an issue. Primary focus is where to gather real-world examples and your project is great for that!

Gonna add it with the next commit, thanks!

**Comment by jwallet** [comment]
also, you probably know that nuget gallery references some apps that are using the api
![image](https://user-images.githubusercontent.com/23088305/72223926-3d40ec00-3542-11ea-9274-e101549d46b9.png)
Did you know lidarr uses your API ? kind of nice

**Comment by jwallet** [comment]
> That's no issue from my side; there is no affiliation between me and spotify so I don't see an issue. 

I thought that was one of the reason they removed the local unauthorized api

**Comment by JohnnyCrazy** [comment]
Yea, super cool that lidarr and even the botframework uses it.

I'm not sure why they shut it down since they didn't communicate it at all. But I think the local API was a hassle to maintain and buggy as hell, so this could also be the reason for the shutdown.
