### ISSUE TITLE
 ImplicitGrantAuth giving a 404 in the browser.

### ISSUE THREAD

**Issue by bartdebever** [JohnnyCrazy/SpotifyAPI-NET#414]
ImplicitGrantAuth with the implementation given at [the documentation](https://johnnycrazy.github.io/SpotifyAPI-NET/auth/implicit_grant.html) is currently broken. The URL and token both seem to be tried to parsed improperly. This makes serverless apps like WPF or UWP application not possible.

Is there any fix for this or ETA for a fix?

**Comment by StijnOostdam** [comment]
I am experiencing the same problem. It would be nice to at least give an update on any progress on this issue.

**Comment by JohnnyCrazy** [comment]
Will have a look today - sorry for the late response

**Comment by JohnnyCrazy** [comment]
So what exactly is not working? Just tested it and I was correctly given a token by the callback. Please include errors, used browsers and the version of your SpotifyAPI-NET

**Comment by bartdebever** [comment]
Odd, I recall having tried with the provided example multiple times but it seems to work now.
Either something changed at Spotify or my brain is now functioning.

Thanks for the offer of help either way and the made package.

**Comment by JohnnyCrazy** [comment]
Your welcome and thank you!

Feel free to open another issue if you run into problems :)
