### ISSUE TITLE
Unable to connect to multiple accounts at the same time / in one process

### ISSUE THREAD

**Issue by CobraCalle** [JohnnyCrazy/SpotifyAPI-NET#421]
Hello,

I would like to use this nuget to integrate Spotify into my custom made voice controlled smart home. My solution is implemented in every room (just like the board computer on the Enterprise) and it can detect the user that has spoken a command. So I would like to implement Spotify in that way that it always continues the music from the user that has spoken the command.

To get this working I need to be able to connect with different Spotify accounts (we have a family plan, but I want the last played tracks from the user that has spoken the command, so I need to connect with his account).

This is the plan: 
To be able to automatic refresh the access tokens, the system does only save the refresh tokens for every user and on initialize I would like to get new access tokens for all users... like this:

`            var authorizationCodeAuth = new SpotifyAPI.Web.Auth.AuthorizationCodeAuth(clientId, secretId, "http://localhost:4002", "http://localhost:4002", SpotifyAPI.Web.Enums.Scope.PlaylistReadPrivate | SpotifyAPI.Web.Enums.Scope.PlaylistReadCollaborative | SpotifyAPI.Web.Enums.Scope.AppRemoteControl | SpotifyAPI.Web.Enums.Scope.UserModifyPlaybackState | SpotifyAPI.Web.Enums.Scope.UserReadPlaybackState | SpotifyAPI.Web.Enums.Scope.UserReadRecentlyPlayed);

            var spotifyTokenCarl = authorizationCodeAuth.RefreshToken(refreshTokenCarl.Value).Result;
            var spotifyTokenIrina = authorizationCodeAuth.RefreshToken(refreshTokenIrina.Value).Result;
`
But there is a problem... the second call to "RefrehToken" always crashes with an authentication Exception... when I first refresh "Carl"... refreh for "Irina" will crash and wise versa.

Using an own instance of AuthorizationCodeAuth for every user gives the same result.

So, am I doing something wring, or is this a bug?
How can I build a solution that can run 24/7 and access multiple Spotify accounts in parallel?

Thanks a lot

Carl

**Comment by CobraCalle** [comment]
OK... its getting more strange...

Now I`ve build a command line tool, that handles the refresh of the tokens an hands over the access token etc. to the calling program. The "outer" program, can now (of course) refresh and quire new acess tokens for multiple accounts... but then I had to realize that the authentication is not the problem. Even just using the instances of SpotifyWebAPI in the same process is not possible.

Steps to reproduce:
1. Create SpotifyWebAPI instance for account no 1
2. Create SpotifyWebAPI instance for account no 2
3. Make a call with SpotifyWebAPI instance for account no 1
4. Make a call with SpotifyWebAPI instance for account no 2
Result: Crash!
Switch 3. and 4.: Crash (on step no. 4)

![image](https://user-images.githubusercontent.com/6218368/75267469-92854400-57f6-11ea-96a1-0cc2b961bbfc.png)

**Comment by CobraCalle** [comment]
Even if you create, use and DISPOSE the first SpotifyWebAPI instance, you get an error when using a second instance... so there is something static going on... but I cant find anything... only the instances-field, but that is empty...

**Comment by CobraCalle** [comment]
Finally, I've found a solution / workaround:

1. Aquire / refresh access token for account no. 1 through external process
2. Aquire / refresh access token for account no. 2 through external process
3. Create only one SpotifyWebAPI instance
4. Set AccessToken on SpotifyWebAPI instance every time you want to use it to the access token of the user you want to work with and make the access to the SpotifyWebAPI instance synchronized

So... yes... finally I`ve can got on... but of course it would be great if someone could fix this.

Thanks alot

Carl

**Comment by JohnnyCrazy** [comment]
Hi!

This sounds like a deadlock/race condition bug, not an API bug. Especially if you use constructs like these:

```
XYZ.Result;
XZZ.Result;
```

You should use `await` in these cases. For example, [this blog post explains some aspects](https://medium.com/rubrikkgroup/understanding-async-avoiding-deadlocks-e41f8f2c6f5d)

**Comment by CobraCalle** [comment]
I used .Result in this case because I've built a small test scenario in a console app that does not allow await in the main method. In the real application of cause alle the calls use await and that does not make any difference.

**Comment by CobraCalle** [comment]
@JohnnyCrazy just to be clear... Await those to calls in an async method and then run that asnyc method from the main method (without await of course) results in the same behavior

**Comment by JohnnyCrazy** [comment]
I'm unable to reproduce it then.

1. I got myself 2 different refresh tokens from 2 different accounts
2. Modified the example a little bit and made the main function `public static async Task Main(string[] args)`
3. Both tokens have values and no errors recorded:

![grafik](https://user-images.githubusercontent.com/3109892/76107787-ad676d80-5fd9-11ea-87a3-de0d7cf9e934.png)

**Comment by CobraCalle** [comment]
> I'm unable to reproduce it then.
> 
> 1. I got myself 2 different refresh tokens from 2 different accounts
> 2. Modified the example a little bit and made the main function `public static async Task Main(string[] args)`
> 3. Both tokens have values and no errors recorded:
> 
> ![grafik](https://user-images.githubusercontent.com/3109892/76107787-ad676d80-5fd9-11ea-87a3-de0d7cf9e934.png)

It is a complete miracle for me, why this works for you. Here is my code... should be the same as yours, but after successfully refreshing the toke for the first account I get the following error:

"The SSL connection could not be established, see inner exception."
Inner: "Authentication failed, see inner exception."
Inner: "The message received was unexpected or badly formatted."

Stacktrace (1. inner Exception):
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__4.MoveNext()

![image](https://user-images.githubusercontent.com/6218368/77774245-095a6a80-704b-11ea-9192-d46d62a3b39a.png)

**Comment by JohnnyCrazy** [comment]
> The SSL connection could not be established, see inner exception

This sounds like a real low-level issue. Do you maybe use any proxies or similar in your setup?

**Comment by CobraCalle** [comment]
no proxy, nothing special...
