### ISSUE TITLE
GetPlaylistTracksAsync without userId deprecated

### ISSUE THREAD

**Issue by Nekromancer** [JohnnyCrazy/SpotifyAPI-NET#422]
In code this method is marked as obsolete with warning "Calling GetPlaylistTracks with a userId is deprecated, remove the parameter". But there is no userId here. And there is no `GetPlaylistTracksAsync` overload that is not obsolete. I believe this is a mistake?

```csharp
public Task<Paging<PlaylistTrack>> GetPlaylistTracksAsync(string playlistId, string fields = "", int limit = 100, int offset = 0, string market = "")
```

**Comment by JohnnyCrazy** [comment]
Indeed, that's an issue

The following should not be marked obsolote:
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/f4b3e9fe401b4979a1e6af8635dad9e0b87dfaf8/SpotifyAPI.Web/SpotifyWebAPI.cs#L1493-L1494

Feel free to submit a PR, or I will do it this evening :)
