### ISSUE TITLE
[Feature Request] Add to playback queue

### ISSUE THREAD

**Issue by Cyklan** [JohnnyCrazy/SpotifyAPI-NET#425]
There is a queue endpoint in the Web API.
It's currently still in beta, but it would be nice to have.
https://developer.spotify.com/documentation/web-api/reference/player/add-to-queue/

**Comment by JohnnyCrazy** [comment]
Added in 307d69945e59d28ecbee87a87634bf070e5f2d8c

Released in `5.1.0`
