### ISSUE TITLE
Auth crashes on auth.OpenBrowser();

### ISSUE THREAD

**Issue by shayo** [JohnnyCrazy/SpotifyAPI-NET#428]
I'm trying a super simple test to use your spotify library. However, all authentication options that use auth.OpenBrowser() crash with the error:
System.ComponentModel.Win32Exception: Cannot find the specified file
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr,intptr)
  at at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr,intptr)

I'm trying to use the library in a Xamarin project, targeting Android. (SpotifyAPI.Web version 5.1.0)
Do you have any clue? 
If not, I can work on posting the simple example. Here's the code snippet:
```
ImplicitGrantAuth auth = new ImplicitGrantAuth(
				_clientId,
				"http://localhost:4002",
				"http://localhost:4002",
				Scope.UserReadPrivate
			  );
            auth.AuthReceived += async (sender, payload) =>
            {
                auth.Stop(); // `sender` is also the auth instance
                SpotifyWebAPI api = new SpotifyWebAPI()
                {
                    TokenType = payload.TokenType,
                    AccessToken = payload.AccessToken
                };
                // Do requests with API client
            };
            auth.Start(); // Starts an internal HTTP Server
            auth.OpenBrowser();

```

Full stack below:
System.Diagnostics.Debugger.Mono_UnhandledException_internal() in 
System.Diagnostics.Debugger.Mono_UnhandledException(System.ComponentModel.Win32Exception ex) in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120
Android.Runtime.DynamicMethodNameCounter.44( Parameters) in 
System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo startInfo) in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/System/System.Diagnostics/Process.cs:616
System.Diagnostics.Process.Start() in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2001
System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo startInfo) in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2490
System.Diagnostics.Process.Start(string fileName, string arguments) in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2473
SpotifyAPI.Web.Auth.AuthUtil.OpenBrowser(string url) in 
SpotifyAPI.Web.Auth.SpotifyAuthServer<SpotifyAPI.Web.Models.Token>.OpenBrowser() in 
Plugin.NFC.Spotify..ctor(string clientId, string secretId, string redirectUrl) in /Users/shayo/Downloads/Plugin.NFC-master/src/Plugin.NFC.Sample/Plugin.NFC.Sample/Spotify.cs:53
NFCSample.MainPage.Button_Clicked_Spotify(Xamarin.Forms.Button sender, System.EventArgs e) in /Users/shayo/Downloads/Plugin.NFC-master/src/Plugin.NFC.Sample/Plugin.NFC.Sample/MainPage.xaml.cs:214
Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked() in D:/a/1/s/Xamarin.Forms.Core/Button.cs:185
Xamarin.Forms.ButtonElement.ElementClicked(Xamarin.Forms.Button visualElement, Xamarin.Forms.Button ButtonElementManager) in D:/a/1/s/Xamarin.Forms.Core/ButtonElement.cs:61
Xamarin.Forms.Button.SendClicked() in D:/a/1/s/Xamarin.Forms.Core/Button.cs:171
Xamarin.Forms.Platform.Android.ButtonElementManager.OnClick(Xamarin.Forms.Button element, Xamarin.Forms.Button buttonController, Xamarin.Forms.Platform.Android.FastRenderers.ButtonRenderer v) in D:/a/1/s/Xamarin.Forms.Platform.Android/ButtonElementManager.cs:25
Xamarin.Forms.Platform.Android.FastRenderers.ButtonRenderer.Android.Views.View.IOnClickListener.OnClick(Xamarin.Forms.Platform.Android.FastRenderers.ButtonRenderer v) in D:/a/1/s/Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs:71
Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v) in 
Android.Runtime.DynamicMethodNameCounter.44() in

**Comment by shayo** [comment]
Ah ha.
Looks like the internal implementation doesn't really support Android (?)
It tries to execute 
else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
      {
        Process.Start("xdg-open", url);
      }
which fails.
I assume this needs to be properly implemented in Xamarin Forms using webView?

**Comment by JohnnyCrazy** [comment]
You can try to get the URL 

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/58be8bb8819e0c4b7aa12dc4ccd82cea68de7c67/SpotifyAPI.Web.Auth/SpotifyAuthServer.cs#L56

 and open your Browser manually using Xamarin methods. Webview, intent etc.

**Comment by shayo** [comment]
Yep. Webview + webview.Navigated callback is the simplest solution.

**Comment by shayo** [comment]
It would be nice if you could add an example to the repo / extend the Auth class to support webview somehow (maybe via modal window).
