### ISSUE TITLE
Implement Podcast API

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#433]
https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/

**Comment by shayo** [comment]
+1

**Comment by shayo** [comment]
Have you started working on this? If not, I might take a stab at it.

**Comment by JohnnyCrazy** [comment]
Not yet.

Sure, feel free to go at it.

**Comment by shayo** [comment]
OK. Can you create a branch I can push my changes to? I've made several changes and it seems to be working nicely.

**Comment by JohnnyCrazy** [comment]
Please create a pull request

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by shayo** [comment]
Ah ok. You work with the fork-pull approach. No worries. I sent you a pull request.

**Comment by JohnnyCrazy** [comment]
The podcast API has been implemented in v6

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/b3670e5636155e1ef193d220db8be8dfb3544634/SpotifyAPI.Web/Clients/Interfaces/IShowsClient.cs

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/b3670e5636155e1ef193d220db8be8dfb3544634/SpotifyAPI.Web/Clients/Interfaces/IEpisodesClient.cs

If you have more feedback/problems/suggestions, feel free to reply here or open another issue!
