### ISSUE TITLE
Logout?

### ISSUE THREAD

**Issue by shayo** [JohnnyCrazy/SpotifyAPI-NET#434]
Is there a way to logout/logoff a user?

**Comment by JohnnyCrazy** [comment]
What is your definition of `logout/logoff`? 

Depending on the authentication method, you get tokens from spotify. Some can be refreshed at a later point in time, some not. The user can `logout` from your app by revoking the every key in their settings: https://www.spotify.com/us/account/apps/

**Comment by shayo** [comment]
I now realize it's probably a webview issue.  It keeps the cookie so when I try to authorize again it skips the login screen and gives the token directly. I need to find a way to clear the cache/cookies.
