### ISSUE TITLE
Request: Allow snapshotId when removing tracks, allow removing local tracks

### ISSUE THREAD

**Issue by richjhart** [JohnnyCrazy/SpotifyAPI-NET#435]
When removing tracks (RemovePlaylistTracks), Spotify allows an optional snapshotId. This can be useful to ensure the playlist has not been modified since being analysed.

Also, the only way to remove local tracks from a playlist uses functionality not available through the API. Instead of providing track URIs, you must provide the playlist positions and a snapshotId.

This is under "Removing the track at a given position in a specific playlist snapshot" at https://developer.spotify.com/documentation/web-api/reference/playlists/remove-tracks-playlist/

**Comment by JohnnyCrazy** [comment]
Hi, this will be coming in the next major release, will take some time for that to release tho, sorry!

> Instead of providing track URIs, you must provide the playlist positions and a snapshotId.

Looking at the docs, how would you provide the positions instead of the uris?

**Comment by JohnnyCrazy** [comment]
Ah, the beta documentation still lacks a lot of the details, found it

> Required. An array of objects containing Spotify URIs of the tracks and episodes to remove with their current positions in the playlist. For example:
{ "tracks": [{ "uri": "spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "positions": [0,3] },{ "uri": "spotify:track:1301WleyT98MSxVHPZCA6M", "positions": [7] }, { "uri": "spotify:episode:512ojhOuo1ktJprKbVcKyQ", "positions": [8] }] }
The positions parameter is zero-indexed, that is the first item in the playlist has the value 0 , the second item 1 , and so on.
A maximum of 100 objects can be sent at once

**Comment by JohnnyCrazy** [comment]
Hi,

In v6, this is now possible:

```csharp
var spotify = new SpotifyClient("YourAccessToken");

var tracks = new List<PlaylistRemoveItemsRequest.Item>
{
  new PlaylistRemoveItemsRequest.Item { Positions = new List<int> { 2 } }
};

await spotify.Playlists.RemoveItems("YourPlaylistId", new PlaylistRemoveItemsRequest(tracks)
{
  SnapshotId = "snapshotid"
});
```

If you have more feedback/problems/suggestions, feel free to reply here or open another issue!
