### ISSUE TITLE
Spotify does not always takes the mute but the icon in the sound mixer shows its muted

### ISSUE THREAD

**Issue by JimmyAppelt** [JohnnyCrazy/SpotifyAPI-NET#44]
After some testing, i find that the muting Spotify does not always works.

It will mute in the sound mixer (the icon will show its muted but its not) but it actually doesn't mute spotify until i mute the app in the sound mixer for myself instead of doing it remotely.

I'm not 100% sure of when or why this actually does what it does. Sometimes it works and sometimes it doesn't.

I'l do more investigation about this issue.

(I'm use the nircmd.dll)

**Comment by JohnnyCrazy** [comment]
Sadly, this is propably related to nircmd and I can't fix anything on my side.
Furthermore, since there is no clean and stable way to mute other programs in c#, I will maybe remove this function (or look for better solutions sometime in the future).

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy same applies with the new VolumeMixer sadly.

It happens that i can see that when exceciting `Mute()` i can see that the icon goes to mute in the volume mixer. But spotify still stays unmuted.

As stated, its not always ... not sure why this is happening.
