### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by LeaklessGfy** [JohnnyCrazy/SpotifyAPI-NET#441]
I've copy/past :
[Example](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web.Examples.CLI/Program.cs)

And when it redirect, spotify write in browser :
INVALID_CLIENT: Invalid redirect URI

The redirectUri parameter :
http://localhost:4002&state=...&scope=playlist-read-private%20playlist-read-collaborative&show_dialog=False

It seems that the redirectUri is badly formatted maybe because ‘&state’ appears before ´?state’ ?

But when I tried to replace it by hand I‘ve got the same error

**Comment by JohnnyCrazy** [comment]
Did you input your credentials? client id and client secret?

**Comment by LeaklessGfy** [comment]
Yes. In both process (web browser when both const are == ´´ and directly in const)

**Comment by JohnnyCrazy** [comment]
What is the exact URL that is opened in your browser when the error occurs? In this URL, there should be a `redirect_uri` parameter. Did you register the value of this parameter in your spotify dashboard? https://developer.spotify.com/dashboard/applications

**Comment by LeaklessGfy** [comment]
> Did you register the value of this parameter in your spotify dashboard? https://developer.spotify.com/dashboard/applications

I missed that part. Thanks for your feedback :)

**Comment by JohnnyCrazy** [comment]
Your welcome! :)
