### ISSUE TITLE
Can't get some things like "GetUsersTopArtists" to work

### ISSUE THREAD

**Issue by 20repsej** [JohnnyCrazy/SpotifyAPI-NET#442]
Hi, I have problems with some of the functions that I want to use.
Some things like GetPrivateProfile and GetUserPlaylists works good but others like GetUsersTopArtists and GetDevices gives me this error: 

`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SpotifyTesting.Program.PrintUsefulData(SpotifyWebAPI api) in /home/jesper/CSpoTUI/Program.cs:line 108
   at SpotifyTesting.Program.<>c__DisplayClass3_0.<<Main>b__0>d.MoveNext() in /home/jesper/CSpoTUI/Program.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

I am using code examples from the docs like this one.

 `Paging<FullTrack> tracks = api.GetUsersTopTracks();
            tracks.Items.ForEach(item => Console.WriteLine(item.Name)); //Display all fetched Track-Names (max 20)
            Console.WriteLine(tracks.Total.ToString());//Display total album track count`

I'm also using AutorizationCodeAuth. There is probably something simple but I can't figure out why some functions don't work.

**Comment by JohnnyCrazy** [comment]
Please add some error handling and see, what the response contains:

```c#
Paging<FullTrack> tracks = api.GetUsersTopTracks();
if(tracks.HasError()) {
  Console.WriteLine(tracks.Error.Message);
}
```

**Comment by 20repsej** [comment]
When I run this:

`Paging<FullTrack> tracks = await api.GetUsersTopTracksAsync();
            if (tracks.HasError())
            {
                System.Console.WriteLine(tracks.Error.Message);
                System.Console.WriteLine("Test");
            }
            Console.WriteLine(tracks.Total.ToString());`

It doesn't find any problems and returns "0". But when I added error handling to GetDevices I got the error message "Permissions missing"

`AvailabeDevices devices = api.GetDevices();
            if (devices.HasError())
            {
                Console.WriteLine(devices.Error.Message);
            }`

**Comment by JohnnyCrazy** [comment]
1. This means the user doesn't have any top tracks.

2. You are probably missing the required scope: https://developer.spotify.com/documentation/general/guides/scopes/

You can set the scopes when initializing your auth code. A sample can be found here: https://johnnycrazy.github.io/SpotifyAPI-NET/auth/authorization_code.html

**Comment by 20repsej** [comment]
Oh, now I get it. So I need to add the scopes for the things I want to access. Is there a way to add all permissions with one command or do I need to add them one by one?

**Comment by JohnnyCrazy** [comment]
Not possible, you will have to join every value of https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/e9685ff4c318f23d9062311f6b03653bc43a3b09/SpotifyAPI.Web/Enums/Scope.cs

Example: `Scope.PlaylistModifyPublic | Scope.PlaylistModifyPrivate `

**Comment by 20repsej** [comment]
Thank you very mush. I think that solves my problems so i close this issue now.
