### ISSUE TITLE
Example in readme give me an unauthorized error

### ISSUE THREAD

**Issue by revoyrm** [JohnnyCrazy/SpotifyAPI-NET#443]
I'm just getting started with this So i am probably doing something wrong but When I try to implement the example in the readme, i get a 401 error. (Code below)

I get the token fine but getting the profile fails. I tried googling but I cant find anything that isn't an expired token but my issue does not appear to be that.

I appreciate any help, Thank you!

`public static async void Example()
        {
            XmlDocument doc = new XmlDocument();
            doc.Load(@"C:\dev\spotifyConfig\config.xml");

            String clientId = doc.SelectNodes("//spotifyConfig/clientId")[0].InnerText;
            String clientSecret = doc.SelectNodes("//spotifyConfig/clientSecret")[0].InnerText;
            CredentialsAuth auth = new CredentialsAuth(clientId, clientSecret);
            Token token = await auth.GetToken();
            SpotifyWebAPI api = new SpotifyWebAPI()
            {
                AccessToken = token.AccessToken,
                TokenType = token.TokenType
            };

            PrivateProfile profile = api.GetPrivateProfile();
            if (!profile.HasError())
            {
                Console.WriteLine(profile.DisplayName);
            } else
            {
                Console.WriteLine("ERROR: " + profile.Error.Message);
            }
        }`

edit: sorry the code is formatting weirdly

**Comment by JohnnyCrazy** [comment]
You can not access current user information with `CredentialsAuth` since the access token is not connected to a user.

See https://johnnycrazy.github.io/SpotifyAPI-NET/auth/client_credentials.html and https://johnnycrazy.github.io/SpotifyAPI-NET/auth/getting_started.html#auth-methods

**Comment by revoyrm** [comment]
Thanks for the answer, I'll close this.

But I do want to ask why is that the example used in the readme?

**Comment by JohnnyCrazy** [comment]
The README does not specify an auth method. Or which README are you referring to?

**Comment by revoyrm** [comment]
https://github.com/JohnnyCrazy/SpotifyAPI-NET#example

**Comment by revoyrm** [comment]
Oh i just read it again, I'm sorry I got two examples mixed up.

**Comment by JohnnyCrazy** [comment]
No problem, maybe I should replace it with a call that works with every auth method, something like `GetTrack` :)
