### ISSUE TITLE
Audio-Analysis Json convert error

### ISSUE THREAD

**Issue by o-litnon** [JohnnyCrazy/SpotifyAPI-NET#446]
[as of 00:00 Sun 26th April]
When accessing the Audio-analysis data endpoint, the deserialization of the Json fails.

Found in **SpotifyAPI.Web.SpotifyWebClient**

Currently working to capture web packets for more information.

   
>  SpotifyAPI.Web - Unkown Spotify Error
>     System.Action`1:Invoke(T)
>     System.Action`1:Invoke(T)
>     System.Threading.Tasks.Task:Execute()
>     System.Threading.ContextCallback:Invoke(Object)
>     System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
>     System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
>     System.Threading.Tasks.Task:ExecuteEntry(Boolean)
>     System.Threading.ThreadPoolWorkQueue:Dispatch()

https://developer.spotify.com/documentation/web-api/reference/tracks/

**Comment by o-litnon** [comment]
NumSamples doesn't seem to correspond to a JSON property?

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web/Models/AnalysisTrack.cs


https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-audio-analysis

**Comment by o-litnon** [comment]
Can I open up a pull request?

Here's the deserialization error, along with a couple of extra suggestions on error handling inside the SpotifyWebClient responses.

![image](https://user-images.githubusercontent.com/40365788/80521145-6dda5380-8982-11ea-9a2b-f111b2423e19.png)

**Comment by JohnnyCrazy** [comment]
Some of the removed fields are on this page tho: https://developer.spotify.com/documentation/web-api/reference-beta/#category-tracks at `Get Audio Analysis for a Track`

Sadly, neither the old nor the new docs cover these fields, it's trial and error :/

Anyway, we can discuss more in a PR since something is wrong definitely, probably the `int` <-> `float` mistake, which causes a parsing error.

**Comment by o-litnon** [comment]
I was using these handy little weblets:

https://developer.spotify.com/console/get-audio-analysis-track

It's a fast way to get the raw data for inspection xD

**Comment by JohnnyCrazy** [comment]
Fixed by #447
