### ISSUE TITLE
Liskov substitution principle

### ISSUE THREAD

**Issue by o-litnon** [JohnnyCrazy/SpotifyAPI-NET#448]
It would be a great benefit to provide public model interfaces, and keep concrete implementations marked as internal. This would allow for better internal object handling and stub testing (perhaps using NSubstitute).

Alternatively...

In order to maintain the public API and not cause a breaking change:
Replace the currently implemented models with an abstracted class, keeping implementations internal.

This change would be handy both for developing the project, and a kindness as a vendor to clients who want to integrate into the API better.

**Comment by JohnnyCrazy** [comment]
I have something planned which involves a huge refactoring and hopefully results in a better project setup, including your mentioned point regarding models.

Some changes I will implement:
* The models will be pure models. Right now, they have to be a child of `BaseModel`, which includes HTTP properties like `Headers` and error states. In the future, they should just be JSON models of the response. I don't think I will convert them to interfaces, but at least simple classes.
* Separate `SpotifyWebAPI` in multiple clients, which are implemented based on interfaces. Similar to how octokit.net does it. Makes testing way easier and splits up the huge file we currently have

	```c#
	var spotify = new SpotifyWebAPI();
	spotify.Playlist.Get("playlist-id"); // IPlaylistClient
	spotify.User.Me(""); // IUserClient
	```

* Remove all non-async methods. They're just duplicated Code and are obsolete IMO.
* Move error handling to Exceptions. While I'm not a fan of exceptions in general, I think this is more suitable for C#. Also allows us to return pure models from the client methods.
* Correctly abstract HTTP Requests and Responses into their own interfaces. Also, to make testing easier. Also, make it easier for users to provide their own HTTP client if needed.
* Add more unit tests. I have to think about integration tests (When to run them? What about endpoints which need user authentication? What about changing live-values?)

I will open another issue where I will track the progress and will close this one once I did. Thanks for your input!

**Comment by JohnnyCrazy** [comment]
Progress will be tracked in #451 and here is a sneak peak how testing could look like with the v6 release:

```c#
public async Task<string> GetAlbumName(IAlbumsClient albumsClient, string albumId)
{
  var album = await albumsClient.Get(albumId);
  return album.Name;
}

[Test]
public async Task TestGetAlbumName()
{
  var albums = new Mock<IAlbumsClient>();
  albums
    .Setup(album => album.Get("my-album-id"))
    .Returns(Task.FromResult(new FullAlbum { Name = "My Album" }));

  Assert.AreEqual("My Album", await GetAlbumName(albums.Object, "my-album-id"));
}
```

Would this be something you would expect? Is there anything we can do to make it even more easier?

If you are adventurous, you can also have a look at the v6 branch :)

**Comment by JohnnyCrazy** [comment]
Hi @o-litnon 

With the beta release of v6, a lot of abstractions are now implemented and testing has been made easier for the user. Endpoint methods  have been split up into clients which provide interfaces, so testing is easier than before. Also, all models are now pure data objects and are not related to any HTTP context.

The [Testing Guide](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/unit_testing) describes an exemplary test.

If you have more feedback/problems/suggestions, feel free to reply here or open another issue!
