### ISSUE TITLE
Updating playlists does not work

### ISSUE THREAD

**Issue by zochris** [JohnnyCrazy/SpotifyAPI-NET#458]
When trying to change the details of a playlist or trying to add tracks the following exception is thrown `System.Reflection.TargetException: 'Object does not match target type.'`

I'm using version `6.0.0-beta.2` from NuGet.

**Comment by JohnnyCrazy** [comment]
Hi @zochris 

Could you share some more infos how you use the API? Small code snippet, .net version and platform? I can't reproduce it with calling it like this:

```csharp
      var success = await spotify.Playlists.AddItems("0euYiidknG1k5MjBKSbVwO", new PlaylistAddItemsRequest(
        new List<string> { "spotify:track:6CcJMwBtXByIz4zQLzFkKc" }
      ));
      Console.WriteLine(success);
```

**Comment by zochris** [comment]
.NET Version: .NET Core 3.1
Platform: Windows 10 (1909)

```c#
var playlists = await spotify.PaginateAll(spotify.Playlists.CurrentUsers());
Console.WriteLine($"Total Playlists in your Account: {playlists.Count}");
foreach (var playlist in playlists)
{
    Console.WriteLine($"{playlist.Name} ({playlist.Id})");

    var pcr = new PlaylistCreateRequest($"{playlist.Name} - Copy") { Public = false };
    var pl = await spotify.Playlists.Create(me.Id, pcr);

    var changeDetailsRequest = new PlaylistChangeDetailsRequest { Name = pl.Name + " + Addition" };
    await spotify.Playlists.ChangeDetails(pl.Id, changeDetailsRequest); // Exception here

    var fullPl = await spotify.Playlists.Get(playlist.Id);
    Console.WriteLine(fullPl.Tracks.Items.Count);
    var uris = fullPl.Tracks.Items.Select(item => (item.Track as FullTrack)?.Uri);

    var addItemsRequest = new PlaylistAddItemsRequest(uris.ToList());
    // also tried this
    //var addItemsRequest = new PlaylistAddItemsRequest(new List<string> { "spotify:track:74xKPuoUJIGAALA2y6IPXt" });
    await spotify.Playlists.AddItems(pl.Id, addItemsRequest); // Exception here
}
```

The code around this loop is the CLI.PersistentConfig example.
The scopes I granted are: `UserReadEmail`, `UserReadPrivate`, `PlaylistReadPrivate` and `PlaylistModifyPrivate`.

Sounds like I must have messed up somewhere, but I can't figure out where…

**Comment by JohnnyCrazy** [comment]
Found the bug. Was because of a request params caching bug. `6.0.0-beta.3` is currently releasing and should be up on nuget soon 👍 

Thanks for the report and help! :)
