### ISSUE TITLE
Question: Paging Follow.OfCurrentUser() with PaginateAll. (.NET Standard 2.0, .NET Framework 4.6.1)

### ISSUE THREAD

**Issue by YettySpaghetty** [JohnnyCrazy/SpotifyAPI-NET#463]
I am trying this on my current Spotify account. I follow a total of 227 people, 200 of which are Artists.

```
var following = await spotify.Follow.OfCurrentUser();
var artistsFollow = following.Artists.Items;

foreach(var item in artistsFollow)
{
       Console.WriteLine("Artist: " + item.Name);
}
```

With the following code I can only get 20 of them, which I assume is the default size of the page. I only have access to the PaginateAll method, due to my .NET Standard version, but I am having trouble finding out where to apply it to get the result I want.

Follow up question: Will the Users type be added in a future version of the API? Thank you in advance!

**Comment by JohnnyCrazy** [comment]
## PaginateAll

Spotify has 2 different kind of paging types: 

* `Paging`, which is used in most of the calls and works by specifying `Limit` and `Offset` parameters
* `CursorPaging`, which is used in very few calls (including `OfCurrentUser`) and uses reference ids in the response to get the next page.

The current beta does include helpers for `Paging`, but not for `CursorPaging`. I opened a branch [ipaginatable-draft](https://github.com/JohnnyCrazy/SpotifyAPI-NET/tree/ipaginatable-draft) which has support for `CursorPaging`. It would be awesome if you could test these changes, you can get the DLL manually [here](https://ci.appveyor.com/project/JohnnyCrazy/spotifyapi-net/build/artifacts)

For `OfCurrentUser`, you can use it like this:

```csharp
// Maximum limit so we do fewer requests in total
var request = new FollowOfCurrentUserRequest { Limit = 50 };
var start = await spotify.Follow.OfCurrentUser(request);

// We need to supply next=>next.Artists due do nested paging object.
var allFollowers = await spotify.PaginateAll(start.Artists, next => next.Artists);

// This will also include the "start" contents!
Console.WriteLine(allFollowers.Count);
```

## Paginator

By default, the `SimplePaginator` is used. It does **not** wait between requests so it could lead to rate limits. If you want to apply a delay, you can create a subclass and override `ShouldContinue` like this:

```csharp
public class DelayedPaginator : SimplePaginator
{
  override protected async Task<bool> ShouldContinue<T>(List<T> results, IPaginatable<T> page)
  {
    await Task.Delay(TimeSpan.FromSeconds(1));
    return true;
  }

  override protected async Task<bool> ShouldContinue<T, TNext>(List<T> results, IPaginatable<T, TNext> page)
  {
    await Task.Delay(TimeSpan.FromSeconds(1));
    return true;
  }
}
```

and register it in your config:

```csharp
var config = SpotifyClientConfig
  .CreateDefault()
  .WithDefaultPaginator(new DelayedPaginator());
```

**Comment by JohnnyCrazy** [comment]
> Will the Users type be added in a future version of the API? Thank you in advance!

Sadly, it's not supported by the Web API itself:

![img](https://i.johnnycrazy.de/eMQLpilpzMBKSBdbjITsm)

https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-followed

**Comment by YettySpaghetty** [comment]
Too bad about the Users type. I'll have to find a way around it until it hopefully becomes a standard feature in the API.

I'll import the DLL and do some testing today and get back to you with feedback. 

Again, thanks a bunch! :)

**Comment by YettySpaghetty** [comment]
Sorry for the long response time. It does work well with the FollowersOfCurrentUserRequest, managed get all 200 and print them individually.

I wanted to check if it there are other types of requests that CursorPaging works with, but I saw in the metadata that only implemented for the FollowedArtistsResponse.

Hope this helps! Keep up the great work!

**Comment by JohnnyCrazy** [comment]
THanks for the feedback! This change is now on NuGET via beta.6
