### ISSUE TITLE
Item search returning bad request.

### ISSUE THREAD

**Issue by Iztral** [JohnnyCrazy/SpotifyAPI-NET#467]
I'm currently experiencing problems with searching for items. No matter how I format the query, I get a bad request error. Here's the request that I send and the error response that I get:

**GET search [type=track,q=Galantis - Firebird,limit=1] 
--> BadRequest application/json {  "error" : {    "status" : 400,    "message" : Missing parameter type
 "**

Here's the call code:
```cs
result = await _spotify.Search.Item(new SearchRequest(SearchRequest.Types.Track, query)
                    {
                        Limit = limitResultAmout
                    });
Am I missing something obvious?

**Comment by JohnnyCrazy** [comment]
Are you on the latest version? `6.0.0-beta.6`

**Comment by JohnnyCrazy** [comment]
This could be related to #461 , where query parameters were not added to the request successfully, depsite them being shown in the log. This has been fixed since version [6.0.0-beta.4](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/6.0.0-beta.4)

**Comment by Iztral** [comment]
Yes, updating to the latest version has fixed the problem. Sorry for the trouble and thank you for the quick answer.

**Comment by JohnnyCrazy** [comment]
Your welcome! ;)

If any other issues arise, feel free to open another issue
