### ISSUE TITLE
General GDI Exception when referencing Image property which is set by GetAlbumArt

### ISSUE THREAD

**Issue by Mrnikbobjeff** [JohnnyCrazy/SpotifyAPI-NET#47]
In my application I wanted to use an Image object which is provided by the GetAlbumArt function several times throughout the code. This however results in an Exception (GDIError - General GDI Exception) because the MemoryStream which creates the Image is disposed. This could be resolved by writing the MemoryStream to a byte array, then disposing the stream and creating the Image object from the byte array. Another possible solution (which I implemented in my private version of this repository) would be to create a separate function which simply returns the byte array. 

Code to trigger the Exception:

pictureBox.Image = track.GetAlbumArt(...);
ImageConverter _imageConverter = new ImageConverter();
byte[] xByte = (byte[])_imageConverter.ConvertTo(pictureBox.Image, typeof(byte[])); //Exception

**Comment by JimmyAppelt** [comment]
The `GetAlbumArt(AlbumArtSize size)` returns a Bitmap, how about making a property in your app to save the Bitmap and re-use it ?

**Comment by Mrnikbobjeff** [comment]
This is not an option as the use of global variables which are only used in one function is unwanted

**Comment by JimmyAppelt** [comment]
bigAlbumPicture.Image = new Bitmap(await track.GetAlbumArtAsync(AlbumArtSize.Size640));
    ImageConverter imageConverter = new ImageConverter();
    byte[] xByte = (byte[])imageConverter.ConvertTo(bigAlbumPicture.Image, typeof(byte[]));

Would work fine, if u don't mind the extra conversion :)

**Comment by JohnnyCrazy** [comment]
Yea, you would need to use it as @JimmyAppelt descriped (make a copy of the bitmap).
But sure, we can add a method to return it as a byte array.

**Comment by Mrnikbobjeff** [comment]
As I said, the method proposed by @JimmyAppelt does result in a General GDI Exception becuase the method which created the PictureBox Image object exited, thus making any later reference to the object invalid. Proof:
![unbenannt](https://cloud.githubusercontent.com/assets/6277666/10412284/75c4f3fe-6f81-11e5-93bb-3183e898cb96.PNG)

**Comment by JohnnyCrazy** [comment]
No, you didn't create a new Bitmap out of the old one.

````csharp
pictureBox1.Image = new Bitmap(await track.GetAlbumArtAsync(AlbumArtSize.Size640));
````

**Comment by Mrnikbobjeff** [comment]
Aahhh i missed this, sorry. Would it then be possible to do this in the GetAlbumArtAsync method? Then the library user would not need to do this trick to use the reference several times. I apologise for my misreading, I really should have caught the change. Regarding the method which returns the byte array, the only real difference is that you would not have to convert it to a memory stream. Instead you would just have to return the result from WebClient.Download method. Why did you use an undefined type there if I may ask?

**Comment by JimmyAppelt** [comment]
Making a Bitmap copy of the Bitmap response will work on both `GetAlbumArt` and `GetAlbumArtAsync` method.

Making extra methods with the return type `Byte[]` is also possible for both methods.

For most users i personally believe the `Bitmap`return type is more convenient and in most cases easier to use, to just filling a control with the Image.

What do you mean with Undefined Type ? 
The `GetAlbumArt` and `GetAlbumArtAsync` methods are both defined with return type of `Bitmap`

**Comment by Mrnikbobjeff** [comment]
He used var to save the byte array which was returned by WebClient.Download.

**Comment by JimmyAppelt** [comment]
Ow i'm sure that is a coding preference :)

**Comment by JohnnyCrazy** [comment]
@Mrnikbobjeff 
You can now use `GetAlbumArtAsByteArrayAsync` and `GetAlbumArtAsByteArray` in Version 2.3.0
