### ISSUE TITLE
v6: Playlists.Get API should allow specifying fields

### ISSUE THREAD

**Issue by palenshus** [JohnnyCrazy/SpotifyAPI-NET#470]
According to https://developer.spotify.com/console/get-playlist/, you can specify the Fields to retrieve for this API, but the PlaylistGetRequest doesn't allow that (though the PlaylistGetItemsRequest does)

**Comment by JohnnyCrazy** [comment]
Indeed. Will be added, thanks for the report! 

Out of interest, what is your particular usecase for requesting specific fields? Minimizing payload size?

**Comment by palenshus** [comment]
Yep! In my case, I literally only want to get the playlist name, so the response is hundreds of kilobytes instead of the few bytes I need.

**Comment by JohnnyCrazy** [comment]
Fixed by d73c87440038c463427e173265a36b0a839b769d

I will release beta.7 with the fixes, thank you very much for the reports, appreciate it! :) If there is anything more, feel free to open another issue.

**Comment by palenshus** [comment]
Works like a charm, thanks! Looking at the resulting object though, it also occurs to me that the boolean fields (like Public and Collaborative) should be nullable. When Fields are specified and those aren't included, then they default to false instead of null, which is misleading

**Comment by JohnnyCrazy** [comment]
Good point, when I built the modules I didn't take `fields `into account. Right now, every nullable can be null with the default request.

Will be tracked in #470!
