### ISSUE TITLE
Retry-After case sensitivity

### ISSUE THREAD

**Issue by michaelfoster9** [JohnnyCrazy/SpotifyAPI-NET#475]
Hello, I am using your API and it's fantastic. I noticed that your SimpleRetryHandler checks for the header as follows
`int.TryParse(response.Headers["Retry-After"]`

however, Spotify seems to be sending the header in all lower case, causing the line above to throw an exception because the Headers dictionary is not case sensitive.

**Comment by JohnnyCrazy** [comment]
Thanks for the report! Which framework version are you on?

**Comment by michaelfoster9** [comment]
I reproduced this on .NET Standard 2.0 with a Xamarin Forms app. 
The UWP application that I believe was compiled as x86 had the problem
When I tried this Android, then I got the upper case variant and it worked fine.

**Comment by JohnnyCrazy** [comment]
Alright, thanks! I pushed a fix to master which makes the header check case insensitive. I will try to release it as soon as we got some more stuff to include. For now, you may want to use the binaries from the build here: https://ci.appveyor.com/project/JohnnyCrazy/spotifyapi-net/builds/33898654/artifacts
