### ISSUE TITLE
Possible Issue with Time Range in PersonlizationTopRequest

### ISSUE THREAD

**Issue by Reywood2357** [JohnnyCrazy/SpotifyAPI-NET#478]
Hi

Using your library in VB.NET to access the Get User's Top Artists and Tracks, however only Long_Term works for the time range parameter. i.e. PersonalizationTopRequest.TimeRangeParam = LongTerm {0} will return either Artists or Tracks as requested, however the following assignments don't work and return an Invalid Request error:
PersonalizationTopRequest.TimeRangeParam = MediumTerm {1}
PersonalizationTopRequest.TimeRangeParam = ShortTerm {2}

If PersonalizationTopRequest.TimeRangeParam isn't assigned, then the medium_term results are returned as expected, since this is the default.

short_time, medium_term and long_term results can all be successfully retrieved via the Spotify Developers Console.

Is there an issue with the use of ShortTerm & MediumTerm in PersonlizationTopRequest.TimeRangeParam?

Using SpotifyAPI.Web (6.0.0-beta.7) and SpotifyAPI.Web.Auth (6.0.0-beta.7) 

Regards
Mick

**Comment by JohnnyCrazy** [comment]
Thanks for the report!

This was indeed a bug. Basically Enums have been treated as having multiple values, but this should only occur when the `[Flags]` attribute is set. If not, only single values should be added to the query parameter list.

This will be released as a hotfix soon 👍

**Comment by Reywood2357** [comment]
Thanks. Appreciate the quick response and fix.
