### ISSUE TITLE
Different Paths for SppotifyWebHelper

### ISSUE THREAD

**Issue by Mrnikbobjeff** [JohnnyCrazy/SpotifyAPI-NET#48]
In recent testing I discovered that the Spotify Installer behaves differently depending on your Windows version. On computers which run Windows 8.1 the Spotifywebhelper is saved directly in the root folder of the Spotify installation. On Windows 7 however the Spotifywebhelper file is saved as specified in the StartSpotifyWebhelper function. To resolve this issue you could add a check whether the file exists before starting it (generally also a good idea for the StartSpotify function). Depending on the result you could also check whether the file exists in the root directory of the installation.
![unbenannt](https://cloud.githubusercontent.com/assets/6277666/10412054/18207202-6f7a-11e5-979b-ae38190d7724.PNG)

**Comment by JohnnyCrazy** [comment]
Fixed by #50
