### ISSUE TITLE
Missing SimplePlaylist in SearchResponse

### ISSUE THREAD

**Issue by harryjjacobs** [JohnnyCrazy/SpotifyAPI-NET#480]
According to https://developer.spotify.com/documentation/web-api/reference/search/search/ search responses can include simplified playlist objects but this appears to be missing in SearchResponse.

**Comment by JohnnyCrazy** [comment]
Sadly the docs are inconsistent in the return type, it does not mention playlists :/

> For each type provided in the type parameter, the response body contains an array of artist objects / simplified album objects / track objects / simplified show objects / simplified episode objects wrapped in a paging object in JSON.

But ofc you're right, they will be added with the next hotfix, thanks for the report 👍

**Comment by JohnnyCrazy** [comment]
Added in beta 9
