### ISSUE TITLE
Getting false status when using Follow Client

### ISSUE THREAD

**Issue by shubham061996** [JohnnyCrazy/SpotifyAPI-NET#496]
Hello,

For our project, we are using SpotifyAPI.Web --version 6.0.0-beta.9 nuget package. 
I am using Follow client to follow a user and Library client to save an album and track.
I was able to Follow the artist and saved the track and album but it is always returning the false status.

It is probably due to wrong status Code comparison..
Like Follow artist return status code 204 but it is being compared with status code 200.

Can you please look into the issue?
Thank you

**Comment by JohnnyCrazy** [comment]
Indeed, hotfix coming up today :)

**Comment by JohnnyCrazy** [comment]
Welcome to the world of spotify's api, where following a playlist returns a 200 and following a user returns a 204 on success 😅 

beta.11 is currently releasing - it should be fixed there @shubham061996  👍

**Comment by shubham061996** [comment]
Hi,

There is same problem with save track and album.

**Comment by JohnnyCrazy** [comment]
I'm sorry, overread that part. Will deliver a fix @shubham061996
