### ISSUE TITLE
Unable to Reorder playlist

### ISSUE THREAD

**Issue by richjhart** [JohnnyCrazy/SpotifyAPI-NET#500]
I'm trying to reorder a playlist, but I'm unable to.

If I leave out the snapshotId:
`Snapshot ss = await api.ReorderPlaylistAsync(Destination.SpotifyId, i, newPos, 1)`
I get a server error 500 (no more info)

If I include it:
`Snapshot ss = await api.ReorderPlaylistAsync(Destination.SpotifyId, i, newPos, 1, snapshotId);`
The library throws an exception:
"Can not add property snapshot_id to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object."

I don't know if it would otherwise work with the snapshotId, if not for the exception.

I definitely have write access to the playlist, as I'd very recently added tracks to it.

I haven't yet had a chance to manually create the call and try it out at `https://developer.spotify.com/console/put-playlist-tracks/` - hoping someone is able to confirm the issue before I need to do that (as I'm now done for the day...).

**Comment by richjhart** [comment]
Quick update - it does work at `https://developer.spotify.com/console/put-playlist-tracks/`. I also checked that out of bounds provides a sensible error and such.

This is the format of the request:
```
curl -X "PUT" "https://api.spotify.com/v1/playlists/<SpotifyId>/tracks" --data "{\"range_start\":0,\"range_length\":1,\"insert_before\":3}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ..."
```
Is there an easy to find out what the library is sending to the server?

**Comment by JohnnyCrazy** [comment]
Can you try this with the the latest version, 6.beta11?

**Comment by richjhart** [comment]
Will be looking at this again shortly.

What's the easiest way of using the beta? Can I get it as a Nuget package?

**Comment by JohnnyCrazy** [comment]
Yes, https://www.nuget.org/packages/SpotifyAPI.Web/6.0.0-beta.11

**Comment by richjhart** [comment]
Is there a migration guide for 5 to 6? I now have 64 errors :)

**Comment by JohnnyCrazy** [comment]
That's sadly still on my TODO list for the initial 6.0 release :/

If you mostly have standard API calls, they're now split up in their own clients. So `api.ReorderPlaylistAsync` becomes `api.Playlists.ReorderItems`.
Regarding path/query/body parameters, they need to be specified differently:
* Path parameters (like spotify-id in your reorder call) are still parameters to the method
* Query/Body parameters are encapsulated in request models. If the specific query/body parameter is required, you have to supply it in the constructor of the model.

```
// old
await api.ReorderPlaylistAsync(Destination.SpotifyId, i, newPos, 1)

// new
await api.Playlists.ReorderItems(Destination.SpotifyId, new PlaylistReorderItemsRequest(i, newPos));
```

**Comment by richjhart** [comment]
I'm getting there - it's just that so much has changed. So for example when looking at tracks from a playlist, there's the fact that it's now playlist.Tracks, and pagination has changed, and that tracks are IPlayableItem. So nothing ends up being a trivial switch over.

As long as it's on the TODO list :)

**Comment by JohnnyCrazy** [comment]
Yes, true, 6.0 is a big one. But on the other hand, a lot of things are now streamlined with the API itself.

Make sure to use the new docs for new concepts: https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/iplayableitem

**Comment by richjhart** [comment]
This might not be the right place for this (probably a new issue), but I'll start the conversation here. I used to use a method to "hack" the library to be able to remove local tracks from a playlist (you can't use the track URI to remove local tracks, you have to just use the position):

```
        public async Task<ErrorResponse> ApiRemovePlaylistTracksLocalAsync(SpotifyWebAPI api, string playlistId, List<int> positions, string snapshotId)
        {
            JObject body = new JObject
            {
                {"positions", JArray.FromObject(positions)},
                {"snapshot_id", snapshotId}
            };
            return await api.UploadDataAsync<ErrorResponse>(_builder.RemovePlaylistTracks(playlistId, new List<DeleteTrackUri>()), body.ToString(Formatting.None), "DELETE") ?? new ErrorResponse();
        }
```

As far as I can tell, specifying track positions isn't supported in version 6 either (since `Positions` is only part of `PlaylistRemoveItemsRequest.Item`, which is turn part of a list).

Is this something that will be supported?

Note that the documentation at https://developer.spotify.com/documentation/web-api/reference/playlists/remove-tracks-playlist/ appear to be incorrect. The `tracks` paramater of "Removing the item at a given position in a specific playlist snapshot" has been copied from the previous section, whereas it should be the `positions` parameter.

**Comment by JohnnyCrazy** [comment]
Definitely will and should be supported. I will open another issue and will fix this within the next version 👍

**Comment by JohnnyCrazy** [comment]
FYI, beta.12 is releasing now and you should be able to use only positions to remove tracks:

```
      var playlist = await spotify.Playlists.Get("XYZ");
      var test = await spotify.Playlists.RemoveItems("XYZ", new PlaylistRemoveItemsRequest
      {
        Positions = new List<int> { 0 },
        SnapshotId = playlist.SnapshotId
      });
```

**Comment by richjhart** [comment]
Wow - that is very quick work, thanks! Have to pop offline but will try as soon as I get back.

Just finished clearing the errors and Reorder is now working great, thanks (sadly, my algorithm isn't quite, but that's not your problem...)
