### ISSUE TITLE
Simple code from examples does not work

### ISSUE THREAD

**Issue by zbigniewcebula** [JohnnyCrazy/SpotifyAPI-NET#502]
Using that code below, I get "3600 Unauthorized Unauthorized", why?
Obviously XXX and xxx are client ID and secret.
```
var config = SpotifyClientConfig.CreateDefault();

var request = new ClientCredentialsRequest("XXX", "xxx");
var response = new OAuthClient(config).RequestToken(request).GetAwaiter().GetResult();
var spotify = new SpotifyClient(config.WithToken(response.AccessToken));
Console.WriteLine(response.ExpiresIn);
try {
	var me = spotify.UserProfile.Current().GetAwaiter().GetResult();
} catch (APIException e) {
	// Prints: invalid id
	Console.WriteLine(e.Message);
	// Prints: BadRequest
	Console.WriteLine(e.Response?.StatusCode);
}
```

**Comment by JohnnyCrazy** [comment]
Because you can't access user related info when using client credentials authentication. The access token is not tied to a user.

https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/client_credentials

You will have to switch to authorization code, pkce or implicit grant auth.

**Comment by zbigniewcebula** [comment]
So example provided in `Using Spotify.Web.Auth` section does not fire `OnAuthorizationCodeReceived` event after `BrowserUtil.Open` with provided correct client id, secret and uri.

Can you provide any working example for example: getting current track on local spotify client from locally logged user?
