### ISSUE TITLE
Need Status Code instead of Boolean status for Spotify Clients

### ISSUE THREAD

**Issue by shubham061996** [JohnnyCrazy/SpotifyAPI-NET#509]
Hi Team,
Can it be possible to get the status code instead of true/false status for Spotify API clients like 
Save show should return 200 status instead of true. 
Actually we need to handle scenarios where status code is 429 i.e. Spotify API limit exceeded. Or Is there any other way to do this from this library?

Thank you

**Comment by JohnnyCrazy** [comment]
This should help you to get started:

https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/error_handling

**Comment by JohnnyCrazy** [comment]
Feel free to reopen if there are any other questions/issues
