### ISSUE TITLE
Request Cfid = Empty.String with allot of Antivirus software

### ISSUE THREAD

**Issue by JimmyAppelt** [JohnnyCrazy/SpotifyAPI-NET#51]
It seems that with allot of Antivirus software the `GetCfid()`return a empty string when requesting.

This result in a being unable to connect to spotify.

This will be the error message: The server committed a protocol violation. Section=ResponseStatusLine

**Comment by JohnnyCrazy** [comment]
>with allot of Antivirus software
Which one exactly?

**Comment by JimmyAppelt** [comment]
I'm already sure of `AVG` (need to ask client what version)

`Bitdefender 2016 Total Security 2016`

I had Bitdefender 2015 installed and i never found any problem, until a released a new version of my application a few days ago with the new implemented spotify function.

Manny people reported me that they couldn't connect to spotify ... so eventually i got connected with a client trough teamviewer ... and did research on hes machine.

It turned out that on hes machine when AVG was enable he could not connect, when it was disabled he could connect.

Few hours later i installed the latest version of Bitdefender 2016 and had the exact same problem.

I tested this with My own app, the Spotify example app and an app GetSpotify (someone else has written) with the same library.

**Comment by JimmyAppelt** [comment]
I need to mention that i tried (for testing purpose) to bring `Connect()` into a loop. After x times it will eventually will get a `Cfid` but the exception ´The server committed a protocol violation. Section=ResponseStatusLine` will get spammed continuously as the application continues. 

And get bad responses most of the time from the `GetStatus ()` all over the place as it is the same query.

**Comment by JimmyAppelt** [comment]
Update:

The client AVG is the latest as of today. (disabling LinkScanner Surfshield inside AVG) will let him him connect.

On my own end with Bitdefender 2016 - I need to un-install the antivirus to be able to connect like normal.

**Comment by JimmyAppelt** [comment]
Tracefile:

System.Net Information: 0 : [13948] ConnectStream#47188045 - Sending headers
{
Origin: https://embed.spotify.com
Referer: https://embed.spotify.com/?uri=spotify:track:5Zp4SWOpbuOdnsxLqwgutt
Host: spotifyapi.spotilocal.com:4380
Connection: Keep-Alive
}.
System.Net.Sockets Verbose: 0 : [13948] Socket#36636535::Send()
System.Net.Sockets Verbose: 0 : [13948] Data from Socket#36636535::Send
System.Net.Sockets Verbose: 0 : [13948] 00000000 : 47 45 54 20 2F 73 69 6D-70 6C 65 63 73 72 66 2F : GET /simplecsrf/
System.Net.Sockets Verbose: 0 : [13948] 00000010 : 74 6F 6B 65 6E 2E 6A 73-6F 6E 3F 26 72 65 66 3D : token.json?&ref=
System.Net.Sockets Verbose: 0 : [13948] 00000020 : 26 63 6F 72 73 3D 26 5F-3D 31 34 34 35 32 31 32 : &cors=&_=1445212
System.Net.Sockets Verbose: 0 : [13948] 00000030 : 33 33 31 26 72 65 74 75-72 6E 61 66 74 65 72 3D : 331&returnafter=
System.Net.Sockets Verbose: 0 : [13948] 00000040 : 36 30 26 72 65 74 75 72-6E 6F 6E 3D 6C 6F 67 69 : 60&returnon=logi
System.Net.Sockets Verbose: 0 : [13948] 00000050 : 6E 25 32 43 6C 6F 67 6F-75 74 25 32 43 70 6C 61 : n%2Clogout%2Cpla
System.Net.Sockets Verbose: 0 : [13948] 00000060 : 79 25 32 43 70 61 75 73-65 25 32 43 65 72 72 6F : y%2Cpause%2Cerro
System.Net.Sockets Verbose: 0 : [13948] 00000070 : 72 25 32 43 61 70 20 48-54 54 50 2F 31 2E 31 0D : r%2Cap HTTP/1.1.
System.Net.Sockets Verbose: 0 : [13948] 00000080 : 0A 4F 72 69 67 69 6E 3A-20 68 74 74 70 73 3A 2F : .Origin: https:/
System.Net.Sockets Verbose: 0 : [13948] 00000090 : 2F 65 6D 62 65 64 2E 73-70 6F 74 69 66 79 2E 63 : /embed.spotify.c
System.Net.Sockets Verbose: 0 : [13948] 000000A0 : 6F 6D 0D 0A 52 65 66 65-72 65 72 3A 20 68 74 74 : om..Referer: htt
System.Net.Sockets Verbose: 0 : [13948] 000000B0 : 70 73 3A 2F 2F 65 6D 62-65 64 2E 73 70 6F 74 69 : ps://embed.spoti
System.Net.Sockets Verbose: 0 : [13948] 000000C0 : 66 79 2E 63 6F 6D 2F 3F-75 72 69 3D 73 70 6F 74 : fy.com/?uri=spot
System.Net.Sockets Verbose: 0 : [13948] 000000D0 : 69 66 79 3A 74 72 61 63-6B 3A 35 5A 70 34 53 57 : ify:track:5Zp4SW
System.Net.Sockets Verbose: 0 : [13948] 000000E0 : 4F 70 62 75 4F 64 6E 73-78 4C 71 77 67 75 74 74 : OpbuOdnsxLqwgutt
System.Net.Sockets Verbose: 0 : [13948] 000000F0 : 0D 0A 48 6F 73 74 3A 20-73 70 6F 74 69 66 79 61 : ..Host: spotifya
System.Net.Sockets Verbose: 0 : [13948] 00000100 : 70 69 2E 73 70 6F 74 69-6C 6F 63 61 6C 2E 63 6F : pi.spotilocal.co
System.Net.Sockets Verbose: 0 : [13948] 00000110 : 6D 3A 34 33 38 30 0D 0A-43 6F 6E 6E 65 63 74 69 : m:4380..Connecti
System.Net.Sockets Verbose: 0 : [13948] 00000120 : 6F 6E 3A 20 4B 65 65 70-2D 41 6C 69 76 65 0D 0A : on: Keep-Alive..
System.Net.Sockets Verbose: 0 : [13948] 00000130 : 0D 0A                                           : ..
System.Net.Sockets Verbose: 0 : [13948] Exiting Socket#36636535::Send() 	-> Int32#306
System.Net.Sockets Verbose: 0 : [13948] Socket#36636535::Receive()
System.Net.Sockets Verbose: 0 : [13948] Data from Socket#36636535::Receive
System.Net.Sockets Verbose: 0 : [13948] 00000000 : 7B 0A 22 74 6F 6B 65 6E-22 3A 20 22 34 38 38 65 : {."token": "488e
System.Net.Sockets Verbose: 0 : [13948] 00000010 : 30 34 66 66 61 61 31 61-66 34 37 34 63 30 36 37 : 04ffaa1af474c067
System.Net.Sockets Verbose: 0 : [13948] 00000020 : 34 65 64 30 62 39 30 35-64 65 38 62 22 0A 7D    : 4ed0b905de8b".}
System.Net.Sockets Verbose: 0 : [13948] Exiting Socket#36636535::Receive() 	-> Int32#47
System.Net.Sockets Verbose: 0 : [13948] Socket#36636535::Dispose()
Exception thrown: 'System.NullReferenceException' in System.dll
`System.Net Error: 0 : [13948] Exception in HttpWebRequest#26603182:: - The server committed a protocol violation. Section=ResponseStatusLine.`
System.Net Error: 0 : [13948] Exception in HttpWebRequest#26603182::GetResponse - The server committed a protocol violation. Section=ResponseStatusLine.
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
System.Net Verbose: 0 : [13948] HttpWebRequest#26603182::Abort()
System.Net Error: 0 : [13948] Exception in HttpWebRequest#26603182:: - The request was aborted: The request was canceled..
System.Net Verbose: 0 : [13948] Exiting HttpWebRequest#26603182::Abort() 
Exception thrown: 'System.Net.WebException' in System.dll
The thread 0x2418 has exited with code 0 (0x0).

**Comment by JimmyAppelt** [comment]
The important piece i believe is:

    System.Net.Sockets Verbose: 0 : [13948] 00000000 : 7B 0A 22 74 6F 6B 65 6E-22 3A 20 22 34     38 38 65 : {."token": "488e
    System.Net.Sockets Verbose: 0 : [13948] 00000010 : 30 34 66 66 61 61 31 61-66 34 37 34 63 30     36 37 : 04ffaa1af474c067
    System.Net.Sockets Verbose: 0 : [13948] 00000020 : 34 65 64 30 62 39 30 35-64 65 38 62 22 0A     7D : 4ed0b905de8b".}
    System.Net.Sockets Verbose: 0 : [13948] Exiting Socket#36636535::Receive() -> Int32#47
    System.Net.Sockets Verbose: 0 : [13948] Socket#36636535::Dispose()
    Exception thrown: 'System.NullReferenceException' in System.dll
    System.Net Error: 0 : [13948] Exception in HttpWebRequest#26603182:: - The server committed a protocol violation. Section=ResponseStatusLine.

Where we received the token already in the socket

**Comment by JimmyAppelt** [comment]
Hooking up Fiddler will give the next exception:

    The Server did not return properly formatted HTTP Headers. Maybe missing 
    altogether (e.g. HTTP/0.9), maybe only \r\r instead of \r\n\r\n?

The response header when failing :

    HTTP/1.0 200 This buggy server did not return headers

The response header in a successful manner:

    HTTP/1.1 200 OK

**Comment by JohnnyCrazy** [comment]
Going through all this, it seems like it's spotify-servers fault, so I think there is not much we can do about it. 

1.
> System.Net Error: 0 : [13948] Exception in HttpWebRequest#26603182:: - The server committed a protocol violation. Section=ResponseStatusLine.

2.
> HTTP/1.0 200 This buggy server did not return headers

We are just doing normal WebRequests (Well, to an unofficial API), can't really change anything I guess

**Comment by JimmyAppelt** [comment]
Sadly this will be true i guess.

As long as spotify doesn't fix the server, it will be a bad idea to deploy an application with the library as it will only work on 50% (rough guess) of peoples machines.

The cause is definitely a antivirus/firewall that is installed.

**Comment by JohnnyCrazy** [comment]
Mh, the only thing you could do is leaving a note in the README or something :/
But we have to note: The API is unofficial and only used internally, so we shouldn't have a lot of expectations to it.

**Comment by swin66** [comment]
Hi, I'm just trying your sample app and I'm experiencing the same problem with AVG.  I disabled it and the app now connects, but it still doesn't function correctly.  Strangley only the Previous & Skip buttons work. Play & Pause do not and there's no info about what is being played.

Any ideas? 
![image](https://cloud.githubusercontent.com/assets/1023849/13570312/a8db703e-e465-11e5-9f3e-3078d180b3b9.png)

**Comment by JohnnyCrazy** [comment]
@swin66 Sorry for the late response, next time please open a new issue for your specific problem.

Try restarting Spotify and the WebHelper, this problem sometimes occurs.

**Comment by JohnnyCrazy** [comment]
Closing this since we can't fix it (AFAIK).

**Comment by JohnnyCrazy** [comment]
Could you test `SpotifyAPI-NET/localapifix` @JimmyAppelt ? This may fix it after some research, sadly I can't test it myself :/

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy i will ! :+1:

**Comment by JimmyAppelt** [comment]
I see you changed to `HttpWebRequest` ... i tested it to double check ... i tried that before unfortunately.

Iv'e spend hours to change the requests before etc. without any luck. Will do some searching and testing again when i have some free time.

**Comment by JohnnyCrazy** [comment]
Mh, that sucks, now I really don't know what else we can do.

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy for some reason, i'm able to connect without any issue anymore.

Might be possible to due an update of spotify

**Comment by JohnnyCrazy** [comment]
@JimmyAppelt Great news, hopefully it stays like that! :+1:
