### ISSUE TITLE
How to set scopes for Access Token

### ISSUE THREAD

**Issue by KenthJ** [JohnnyCrazy/SpotifyAPI-NET#511]
Hi there

I'm using the code below.

But how do I add scopes to the Access Token, like e.g. scopes = playlist-read-private

The code below, without setting the scopes, will result in a permission denied when trying to get private playlists.

Any help is greatly appriciated

``
var config = SpotifyClientConfig.CreateDefault();
var request = new ClientCredentialsRequest(CLIENT_ID, CLIENT_SECRET);
var response = await new OAuthClient(config).RequestToken(request);

var spotify = new SpotifyClient(config.WithToken(response.AccessToken));
var playLists = await spotify.Playlists.CurrentUsers();
``

**Comment by JohnnyCrazy** [comment]
Hi,

You're using `ClientCredentials`, which do not allow to access user data, [quote from the docs](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/client_credentials):

> Only endpoints that do not access user information can be accessed.

You will need to switch to another OAuth flow, depending on platform & usecase:

* [PKCE](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/pkce) - Good for mobile and desktop apps
* [Implicit](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/implicit_grant) - Good for client-side browser apps, short-lived tokens and not refreshable tho
* [Authorization Code](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/authorization_code) - Good for browser apps which have a backend and need to query user related data

**Comment by KenthJ** [comment]
Thank you very much for your response.

This OAuth is completely new to me.

Is it correctly understood that in order to use e.g. PKCE, I need to start a webserver
and the localhost below needs to be replaced with my real external IP address?
var loginRequest = new LoginRequest(new Uri("http://localhost:5000/callback"), CLIENT_ID, LoginRequest.ResponseType.Code)

I guess then I also need to forward port 5000 in my router in order for the spotify server to reach my PC inside my LAN, or am I completely on a wrong track here?

Thanks in advance

**Comment by KenthJ** [comment]
And where do I do this below, google is not helping me much
Make sure "http://localhost:5000" is in your applications redirect URIs

**Comment by JohnnyCrazy** [comment]
> Is it correctly understood that in order to use e.g. PKCE, I need to start a webserver in my C# program
and the localhost below needs to be replaced with my real external IP address?
var loginRequest = new LoginRequest(new Uri("http://localhost:5000/callback"), CLIENT_ID, LoginRequest.ResponseType.Code)

It's correct that a webserver has to be running, but it does not have to be exposed to the internet.
The user will be redirect to `http://localhost:5000` **within** his browser, so he will make a request to his own locally running webserver.

[This guide may also help to understand the flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce)

>And where do I do this below, google is not helping me much
Make sure "http://localhost:5000" is in your applications redirect URIs

You can add redirect URIs on your spotify dashboard: [Dashboard link](https://developer.spotify.com/dashboard/applications)

**Comment by JohnnyCrazy** [comment]
One more: If you develop a UWP App, you can also use custom protocoll handlers without a local WebServer, [see the example app](https://github.com/JohnnyCrazy/SpotifyAPI-NET/tree/master/SpotifyAPI.Web.Examples/Example.UWP)

**Comment by KenthJ** [comment]
Thank you so much for your valuable support.

Now I understood everything, and got it all running including a webserver implemented via HttpListener.

Maybe it would be a good idea to improve the text below:
Make sure "http://localhost:5000" is in your applications redirect URIs

To something like:
Make sure "http://localhost:5000" is in your applications redirect URIs in the Spotify console website

And maybe use a couple of lines to explain the concept of the redirect URI.
Earlier I thought that it was the Spotify server which should access the webserver, until I realized that my local browser would be redirected to this url which is hosted by my webserver which I need to implement myself.

This would have helped me quite a lot.

But thanks a lot once again

**Comment by JohnnyCrazy** [comment]
I hoped this was covered by: https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/auth_introduction

The Spotify Auth Flows are explained in detail at their docs as well, didn't want to redo their work: https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow

But I will make sure to include some more links to the official documentation for better visibility and guidance! Thank you :)

**Comment by iminet** [comment]
Hi, 

Could anybody help me, how I could obtain a playlist modify enabled token without user interact?
My app is running on a headless linux server, I can't open browser on it (because there's no browser on) and can't start embedded web server either.

My schematic idea about, what I want:
```
[myapp] -> opens /authenticate API (clientid, clientsecret)
[spotifyapi] -> receives request, clientid and clientsecret. creates a token with modification ability.
[spotifyapi] -> sends the token to the requester
[myapp] -> receives the token with modification ability

```

Schema with C# formule, with only one step, no web login, no embedded web server. Just client id and client secret. If these are valid, receive the access token. As simple as possible.
`Console.WriteLine(myspotifyinstance.GetAccessToken(apiurl, clientid, clientsecret, arrayOfScopes).AccessToken);`

Is that possible?
Thanks!

**Comment by JohnnyCrazy** [comment]
Please open a new [discussion](https://github.com/JohnnyCrazy/SpotifyAPI-NET/discussions) for your issue.
