### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by WayneHarsman** [JohnnyCrazy/SpotifyAPI-NET#513]
I'm currently trying to create a music hub based on Spotify and Russian service called Yandex.Music. During my tests, I found that string properties (like FullTrack.Name, SimplePlaylist.Name e.t.c) don't support Cyrillic letters, despite that fact that same endpoints in Spotify Developer Console returns all properties of track correct regardless of the language.  The output is a string made of '?' chars. Here is a crapy piece of code that I used:
```cs
foreach (var item in SongsList.Items)
{
       if (item.Track is FullTrack song)
       {
         Console.Write($"{SongsList.Items.IndexOf(item)}.{song.Name}\n");
       }
}
```
 So, cause name property of songs and authors is a vital part for my project I have a few questions:

1. The first one is obviously: am I missing something?
2. Is that issue caused by the encoding of string?

Thank you in advance and thanks for great lib.

**Comment by JohnnyCrazy** [comment]
Do you have a spotify id for a track/album where I can see some of those letters?

**Comment by WayneHarsman** [comment]
This one for example: 2d7xhBhtpAN1ht9hQ0ySSJ

**Comment by JohnnyCrazy** [comment]
Did you just test via Console.Write or did e.g inspect via VS Debugger? Could be that the console does not support crylic letters.

**Comment by WayneHarsman** [comment]
VS Debuger shows Name property correct, no '?' stuff, but as I know, System.Write() method is supports cyrillic letters. I've tried to change OutputEncoding of Console to UTF8 but it didn't solve the problem

**Comment by JohnnyCrazy** [comment]
If the vs code debugger shows it correctly, then the underlying string has the correct format AFAIK. You can try writing it to a file and the open it in a utf-8 compatible editor?

**Comment by WayneHarsman** [comment]
Well, it turns out to be that there's nothing to do with library itself. The whole problem is in standard Console output and input as well. Thank you so much for your time.
