### ISSUE TITLE
Web-API Async Implementation

### ISSUE THREAD

**Issue by JimmyAppelt** [JohnnyCrazy/SpotifyAPI-NET#52]
What do you think about making the webapi async to ?

**Comment by JohnnyCrazy** [comment]
I thought of it a while ago, but couldn't figure out a nice and clean way of implementing it without writing every method twice. I'm open for implementation-ideas! :smiley:

**Comment by JimmyAppelt** [comment]
:smile: 

I doubt there is a way with only one method.

I believe there will be 2 ways of going into it.

* Extend the `IClient` with async methods and double each method in the `SpotifyWebAPI.cs` and `SpotifyWebClient.cs` and make them async.

* Make `IClient` `SpotifyWebAPI.cs` `SpotifyWebClient.cs` > `IClientAsync` `SpotifyWebAPIAsync.cs` `SpotifyWebClientAsync.cs`

The first way is probably the best approach, so there can always be chosen to use a normal or a async method in the same instance.

It will be a bit of work of coarse, but i think if this is added to the library - this could be the best spotify library out :star2:

**Comment by JohnnyCrazy** [comment]
@JimmyAppelt 
First method looks good, some expansions:

I will add another internal class (something like `SpotifyWebAPIBuilder`), which will build the URLs and check all the Inputs. Something like this:

````c#
public SearchItem SearchItems(String q, SearchType type, int limit = 20, int offset = 0, String market = "")
{
	return DownloadData<SearchItem>(_builder.SearchItems(q, type, limit, offset, market));
}
public async Task<SearchItem> SearchItemsAsync(String q, SearchType type, int limit = 20, int offset = 0, String market = "")
{
	return await DownloadDataAsync<SearchItem>(_builder.SearchItems(q, type, limit, offset, market));
}
````

Thoughts @JimmyAppelt ?

**Comment by JimmyAppelt** [comment]
Our bible is to make code as much maintainable as possible and avoid duplication of code.

So yes that would be the best approach. It will make the code for some peeps more complex.

Could there be a problem with only providing async methods (on those who need it, like downloading data) ? This will be the easiest, less work, and easiest to maintain.

**Comment by JohnnyCrazy** [comment]
@JimmyAppelt 
Mh, no, two reasons:

1. I still want to support both types. Some developers like async, some not. And personally, I prefer the Sync-way.
2. I don't want to release another big breaking change that quickly. That would require all developers to adjust their projects again. 

>It will make the code for some peeps more complex.

What do you mean with that exactly? There won't be any change for API-Users, just for the API-Developers.

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy 

> It will make the code for some peeps more complex.

For the API-Devs as you say :wink:  

Duplicating every method with a `_builder` is the most effective thing to do, because you are right.  otherwise it will break currently running apps using the API.

**Comment by JohnnyCrazy** [comment]
Implemented async-structure in 0dd94eaf415b6ce531158cfb4d8648885a461480 (`web-async`-branch)
Now, we/me just need to convert all methods. Maybe I will have some free time in the next days.

 I'm open for PRs :smile:

**Comment by JimmyAppelt** [comment]
Ah great @JohnnyCrazy  I'l PR the async methods - then you can work on the stringbuilder if that fine for you.

**Comment by JimmyAppelt** [comment]
So this is how you would like it @JohnnyCrazy [96bcb7b](https://github.com/JimmyAppelt/SpotifyAPI-NET/commit/ee24751aaed99d5b5bdc01cd8d931905893d9447) ?

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy i'm not sure if the _builder is always implemented as you would like (as i said makes it more complicated.

**Comment by JohnnyCrazy** [comment]
@JimmyAppelt Uhm yea, but `SearchItems` needs to be replaced with the specific method-name like `GetAlbumTracks`. Maybe I have time to make/push the builder methods later this day

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy ah yes that would make sence

**Comment by JimmyAppelt** [comment]
@JohnnyCrazy this should be better [`9bb25a8`](https://github.com/JimmyAppelt/SpotifyAPI-NET/commit/dca8d5e3deb3adf7fb8cc74b911099fe483d8519) :+1:

**Comment by JohnnyCrazy** [comment]
Merged `webapi-async`, Release should be out soon
