### ISSUE TITLE
GetPlaylistAsync() returns the first 100 tracks only

### ISSUE THREAD

**Issue by balintn22** [JohnnyCrazy/SpotifyAPI-NET#520]
The API itself has a flag to show there are more results, but I can't find that in the dotnet API.
Am I missing something? Is there another way to get the rest of a playlist?

I actually found that the result has a Paging<> collection, so I'll look into how to access the rest of the results via that.

**Comment by balintn22** [comment]
Here's the next question: how to get the next batch in a Paging<> collection?
I can get the first page of a plylist like this:

FullPlaylist fullPlaylist = await GetPlaylistAsync(playlistId);

Now, fullPlaylist.Tracks.Items contains the first batch of tracks in the playlist.
fullPlaylist.Tracks.HasNextPage shows that there is another page.

How do I get the items of the next page?

**Comment by balintn22** [comment]
I checked SpotifyAPI.Web source here, but it seems to be way out of sync with the nuget package (5.1.1).

**Comment by JohnnyCrazy** [comment]
Hi @balintn22 

Sorry for the late response here

Yes, 5.1.1 will be deprecated soon once 6 hits stable. If you're just starting out, I recommend you to switch to the beta which will not receive any breaking changes anymore! 👍

For version 6, you can have a look at the pagination helper
https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/pagination

**Comment by JohnnyCrazy** [comment]
If you have any other questions, feel free to reopen or open another issue
