### ISSUE TITLE
'Example.UWP' fails to build (6.0.0-beta.12)

### ISSUE THREAD

**Issue by Heiland** [JohnnyCrazy/SpotifyAPI-NET#524]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/b945e4c272856351b5b9163adcf022984445cfe1/SpotifyAPI.Web.Examples/Example.UWP/ViewModels/PlaylistsListViewModel.cs#L34

Version:
6.0.0-beta.12

Error message:
1>C:\Users\asdf\source\SpotifyAPI-NET-6.0.0-beta.12\SpotifyAPI.Web.Examples\Example.UWP\ViewModels\PlaylistsListViewModel.cs(34,34,34,45): error CS0411: The type arguments for method 'SpotifyClient.PaginateAll<T>(IPaginatable<T>, IPaginator?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by JohnnyCrazy** [comment]
Indeed, will be fixed tomorrow, thank You for the report! 👍
