### ISSUE TITLE
Blazor wasm with .NET 5 RC 2: PKCEUtil throws PlatformNotSupportedException

### ISSUE THREAD

**Issue by Benuhx** [JohnnyCrazy/SpotifyAPI-NET#525]
Hi everyone,

i've updated my Blazor wasm (Client-Side) Project from netstandard2.1 to the latest .NET 5 RC 2 Release. After the update the PKCEUtil for the PKCE authorization workflow throws a PlatformNotSupportedException:

`var (verifier, challenge) = PKCEUtil.GenerateCodes();`

throws

`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.Security.Cryptography.Csp is not supported on this platform.
System.PlatformNotSupportedException: System.Security.Cryptography.Csp is not supported on this platform.
   at System.Security.Cryptography.RNGCryptoServiceProvider..ctor()
   at SpotifyAPI.Web.PKCEUtil.GenerateRandomURLSafeString(Int32 length)
   at SpotifyAPI.Web.PKCEUtil.GenerateCodes(Int32 length)
   at Audify.Client.Pages.SpotifyCallback.RequestFirstAuth() in 
C:\SpotifyCallback.razor:line 27
   at Audify.Client.Pages.SpotifyCallback.OnInitializedAsync() in 
C:\SpotifyCallback.razor:line 22
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()`

There is no exception if i pass a random string (my current workaround):
`var (verifier, challenge) = PKCEUtil.GenerateCodes("YourSecureRandomString");`

After some research i found out that there is a breaking change in the System.Security.Cryptography API with .NET 5 and Blazor: https://docs.microsoft.com/de-de/dotnet/core/compatibility/cryptography#systemsecuritycryptography-apis-not-supported-on-blazor-webassembly

Maybe this is the reason for the exception?

SpotifyAPI.Web Version: 6.0.0-beta.12

**Comment by JohnnyCrazy** [comment]
Hi @Benuhx 

Seems like we currently can't offer an alternative implementation:

> There are no good workarounds to suggest at this time.

If it's completely client-side and you need refreshable tokens, I see no alternative. If you can live with short-lived tokens, you could consider switching to Implicit Grant Auth.
