### ISSUE TITLE
Question: How to use Player.ResumePlayback

### ISSUE THREAD

**Issue by KenthJ** [JohnnyCrazy/SpotifyAPI-NET#536]
I hope you bear with me here, the only documentation I'm able to find, seems to be outdated.

How do I use the ResumePlayback method, like below

mySpotify.Player.ResumePlayback(new PlayerResumePlaybackRequest(what do I put here?));

In the old implementation I can see that I could specify device_id, uri(s), offset etc.

But how do I use this new implementation, could you please provide a code line as an example?

Thanks a lot in advance.

**Comment by JohnnyCrazy** [comment]
Hi @KenthJ 

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web/Models/Request/PlayerResumePlaybackRequest.cs

```csharp
// resume playback without arguments
mySpotify.Player.ResumePlayback();

// resume playback with specifc device
mySpotify.Player.ResumePlayback(new PlayerResumePlaybackRequest
{
  DeviceId = "YourDeviceId"
});

// resume playback with specifc device and uris
mySpotify.Player.ResumePlayback(new PlayerResumePlaybackRequest
{
  DeviceId = "YourDeviceId",
  Uris = new List<string>() { "YourTrackUri" }
});

// start from specific timestamp in milliseconds
mySpotify.Player.ResumePlayback(new PlayerResumePlaybackRequest
{
  DeviceId = "YourDeviceId",
  Uris = new List<string>() { "YourTrackUri" },
  PositionMs = 100
});
```

**Comment by KenthJ** [comment]
Thanks a lot, works like a charm now
