### ISSUE TITLE
Get next page of playlist

### ISSUE THREAD

**Issue by FadyQJ** [JohnnyCrazy/SpotifyAPI-NET#537]
Hello,

I'm using
`await spotify.Playlists.Get(playlistId)`
It is limited to 100 tracks, how do I get the next batch? I can't find the page method to do NextPage

**Comment by JohnnyCrazy** [comment]
If you're on >= .NET Standard 2.1, you can use the following async iterator and simply break if you don't need more pages: https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/pagination#paginate

But you're right, there should be a `NextPage` and `PreviousPage` method as well. I will open a seperate issue to track this feature.
