### ISSUE TITLE
WebClient does not support concurrent I/O 

### ISSUE THREAD

**Issue by JimmyAppelt** [JohnnyCrazy/SpotifyAPI-NET#55]
When requesting to fast after each other (came up with async and await) .NET will throw this error as webclient instance is already busy.

Can be reproduced by doing `SearchItemAsync()` repeatedly quickly after each other.

Best practice says to make a new `WebClient` for every call.

**Comment by JohnnyCrazy** [comment]
Will patch tomorrow, thanks!

**Comment by JohnnyCrazy** [comment]
Hotfix `2.5.1` released, thanks again for reporting :+1:

**Comment by JimmyAppelt** [comment]
No problem @JohnnyCrazy , thank you for the fast fix ! :star2:

**Comment by CVertex** [comment]
Great! I ran into this problem on the latest nuget release. Is this on nuget? Or, am I still doing something wrong

**Comment by JimmyAppelt** [comment]
@CVertex are you using `2.5.1` release ?

**Comment by CVertex** [comment]
@JimmyAppelt I am using the latest nuget, which is 2.5.1. I'm using all the async methods and still seeing this problem..
I have to move on, so I reverted back to the slower serial requests. I'll try to replicate this problem again in a separate app

**Comment by JohnnyCrazy** [comment]
@CVertex Mh, should work fine, every async call has its own `WebClient`. I will see if I can reproduce it

**Comment by duhseekoh** [comment]
I also get this error. Does every async call have its own client? It looks like the WebClient is actually created one time, in the constructor of SpotifyWebAPI. If you look at DownloadDataAsync for example, it just uses that same WebClient already created.

**Comment by JohnnyCrazy** [comment]
The async download uses a new instance every time, while the sync methods use the object's one. Are you on the latest version?

**Comment by duhseekoh** [comment]
Oh I was looking here and didn't realize that WebClient was actually SpotifyWebClient: https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/SpotifyWebAPI.cs#L1831
Which does create a new WebClient for each call.

So strange how I still get the error that I can't have concurrent I/O on a WebClient instance.

**Comment by JohnnyCrazy** [comment]
Do you have a small code snippet to reproduce it?

**Comment by duhseekoh** [comment]
`
public async Task<List<FullTrack>> SearchForTracks(string searchText) {
			System.Diagnostics.Debug.WriteLine ("Searching for: " + searchText);

			Task<SearchItem> searchCall = spotifyWebApi.SearchItemsAsync (searchText, SpotifyAPI.Web.Enums.SearchType.Track);
			SearchItem searchItem = await searchCall;

			List<FullTrack> tracks = searchItem.Tracks.Items;
			return tracks;
		}
`

And I'm just calling that method every time a user types into a search box (each key typed). This is a Xamarin app by the way.

**Comment by JohnnyCrazy** [comment]
I will try it out tomorrow and will get back to you. This is weird...

**Comment by duhseekoh** [comment]
And here is the specific error fyi: 

![image](https://cloud.githubusercontent.com/assets/931588/15486558/4f479cb2-210c-11e6-9f1b-d03ee2b475c2.png)

**Comment by JohnnyCrazy** [comment]
Well, my bad, I'm using the wrong WebClient at https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Web/SpotifyWebClient.cs#L79 ... Hotfix coming soon :wink:

**Comment by duhseekoh** [comment]
Excellent. I'm surprised this hasn't come up more!

**Comment by JohnnyCrazy** [comment]
Fixed in a4c76ec6e3f063927cd43113e3b3d107382071e5, release following
