### ISSUE TITLE
Code suggestion

### ISSUE THREAD

**Issue by hansmbakker** [JohnnyCrazy/SpotifyAPI-NET#556]
Nice library! Seeing that you maintain the HTTP logic yourself, I was wondering whether you know about [Refit](https://github.com/reactiveui/refit)?

It is a library that generates HTTP client logic for you based upon interfaces that you write, which means that you need to spend less time and attention to maintaining that part.

**Comment by JohnnyCrazy** [comment]
Good idea and noted for feature , thanks!
