### ISSUE TITLE
full music url

### ISSUE THREAD

**Issue by babakmdi** [JohnnyCrazy/SpotifyAPI-NET#559]
var spotify = new SpotifyClient("My Token Access");      
 var track = await spotify.Tracks.Get("6StaOnAGq2jhJeSZEy5CYY");

this is a code for get tracks , and i get just PreviewUrl . can we get full music or not? i want download the music.

**Comment by JohnnyCrazy** [comment]
Hi, that's not possible via the Spotify WEB API.

Other resources:

https://developer.spotify.com/documentation/web-playback-sdk/
