### ISSUE TITLE
VB.NET UpdateTrack not declared.

### ISSUE THREAD

**Issue by bicobajas** [JohnnyCrazy/SpotifyAPI-NET#56]
Its just telling me that updatetrack is not declared what do i declare it as? & UpdatePlayingStatus is doing the same...

Imports SpotifyAPI
Imports SpotifyAPI.Local.SpotifyLocalAPI
Imports SpotifyAPI.Local.Models
Imports SpotifyAPI.Local.Enums
Imports Newtonsoft
Public Class Form1
    Private ReadOnly _spotify As SpotifyAPI.Local.SpotifyLocalAPI
    Private _currentTrack As Track
    Dim SpotifyLocalAPI = New SpotifyAPI.Local.SpotifyLocalAPI
    Dim spotify = New SpotifyAPI.Local.SpotifyLocalAPI

    Public Sub Connect()
        Dim _spotify = New SpotifyAPI.Local.SpotifyLocalAPI
        If Not SpotifyLocalAPI.IsSpotifyRunning() Then
            MessageBox.Show("Spotify isn't running!")
            Return
        End If
        If Not SpotifyLocalAPI.IsSpotifyWebHelperRunning() Then
            MessageBox.Show("SpotifyWebHelper isn't running!")
            Return
        End If

        Dim successful As Boolean = _spotify.Connect()
        If successful Then
            MetroButton1.Text = "Connection to Spotify successful"
            MetroButton1.Enabled = False
            'UpdateInfos()
            _spotify.ListenForEvents = True
        Else
            Dim res As DialogResult = MessageBox.Show("Couldn't connect to the spotify client. Retry?", "Spotify", MessageBoxButtons.YesNo)
            If res = DialogResult.Yes Then
                Connect()
            End If
        End If
    End Sub
    Public Sub UpdateInfos()
        Dim status As StatusResponse = _spotify.GetStatus()
        If status Is Nothing Then
            Return
        End If

        'Basic Spotify Infos
        UpdatePlayingStatus(status.Playing)
        clientVersionLabel.Text = status.ClientVersion
        versionLabel.Text = status.Version.ToString()
        repeatShuffleLabel.Text = status.Repeat + " and " + status.Shuffle

        If status.Track IsNot Nothing Then
            'Update track infos
            UpdateTrack(status.Track)
        End If
    End Sub

    Private Sub MetroButton1_Click(sender As Object, e As EventArgs) Handles MetroButton1.Click
        Connect()
    End Sub
End Class

**Comment by JimmyAppelt** [comment]
Hm, yes ofcoarse

> UpdateTrack(status.Track)

Where is your method `UpdateTrack(Track track)` ?

You need to add the method (but then for Visual basic):

    public async void UpdateTrack(Track track)
    {
         _currentTrack = track;

          advertLabel.Text = track.IsAd() ? "ADVERT" : "";
          timeProgressBar.Maximum = track.Length;

          if (track.IsAd())
              return; //Don't process further, maybe null values

          titleLinkLabel.Text = track.TrackResource.Name;
          titleLinkLabel.Tag = track.TrackResource.Uri;

          artistLinkLabel.Text = track.ArtistResource.Name;
          artistLinkLabel.Tag = track.ArtistResource.Uri;

          albumLinkLabel.Text = track.AlbumResource.Name;
          albumLinkLabel.Tag = track.AlbumResource.Uri;

          bigAlbumPicture.Image = await track.GetAlbumArtAsync(AlbumArtSize.Size640);
          smallAlbumPicture.Image = await track.GetAlbumArtAsync(AlbumArtSize.Size160)
    }

**Comment by JohnnyCrazy** [comment]
Hi,

I think you missed some methods when porting from C# to VB.NET.  
Just make sure you port every method, else it, of couse, won't work as expected.
If you still need more help, feel free to reopen the issue
