### ISSUE TITLE
Notification if user cancels authorization?

### ISSUE THREAD

**Issue by JackDjTom** [JohnnyCrazy/SpotifyAPI-NET#566]
Hi,
when I say `BrowserUtil.Open(request.ToUri());` the browser opens a new page where the User can either authorize my app or cancel the authorization.
If he authorizes it, i'll end up in the event `AuthorizationCodeReceived` and that's fine...
But I was wondering if there is any way i get notified in my app when the user clicks _Cancel_ on the authorization page?

And no matter what the user clicks, he'll end up on the /callback page which I specified... is that intended?
(In your Example.CLI.CustomHtml the user will be shown the same custom page, no matter if he accepts or cancels the authorization request.)

**Comment by JohnnyCrazy** [comment]
Hi,

This is now in master and documented here: https://johnnycrazy.github.io/SpotifyAPI-NET/docs/authorization_code#using-spotifywebauth

I also updated the default HTML resources to correctly show if the authorization was erroneous/successful

**Comment by JackDjTom** [comment]
Thank you!
