### ISSUE TITLE
Setting WebClient.Proxy to null stops the local api from working

### ISSUE THREAD

**Issue by haefele** [JohnnyCrazy/SpotifyAPI-NET#57]
In an environment where I have setup a proxy in my internet settings the local spotify api is not working.

It seems that the issue is in these two lines, where the WebClient.Proxy property is set specifically to null.

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Local/RemoteHandler.cs#L65
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Local/ExtendedWebClient.cs#L13

I am unsure why they are specifically set to null, but maybe you guys can tell me that.

I also would be happy to make a pull request to fix this by myself, but first I would like to discuss how this should be fixed (just to match your architectural expectations).

**Comment by JohnnyCrazy** [comment]
@haefele I had problems with it being not null, but that was before I released the library and was propably related to some misconfiguration on my system.

Feel free to create a PR :+1:

**Comment by JohnnyCrazy** [comment]
Fixed by #58
