### ISSUE TITLE
Invalid username error

### ISSUE THREAD

**Issue by shift-eleven** [JohnnyCrazy/SpotifyAPI-NET#583]
Hi!, So I'm trying out this API, and this is my code for getting my currently playing song
```cs
var config = SpotifyClientConfig.CreateDefault()
                .WithHTTPLogger(new SimpleConsoleHTTPLogger())
                .WithRetryHandler(new SimpleRetryHandler() { RetryAfter = TimeSpan.FromSeconds(1) });

            var request = new ClientCredentialsRequest("id", "secret");
            var response = await new OAuthClient(config).RequestToken(request);

            var spotify = new SpotifyClient(config.WithToken(response.AccessToken));

            CurrentlyPlaying currentSong = null;

            currentSong = await spotify.Player.GetCurrentlyPlaying(new PlayerCurrentlyPlayingRequest(PlayerCurrentlyPlayingRequest.AdditionalTypes.All));

            if (currentSong.Item is FullTrack track)
            {
                Console.WriteLine(track.Name);
            }
```

My client id and secret are correct but im getting an invalid username error on GetCurrentlyPlaying()

Any help would be appreciated!

**Comment by JohnnyCrazy** [comment]
Hi,

Quote from the [ClientCredentialsRequest documentation](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/client_credentials):

> Only endpoints that do not access user information can be accessed.

You will have to swap to another authorization flow if you want to access user information.

**Comment by shift-eleven** [comment]
I looked into the other methods, but they all seem to work in web based application. I'm using this in the context of a console application, is there a way I could achieve this?

**Comment by JohnnyCrazy** [comment]
Yes, for console application you can use [PKCE](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/pkce/)

**Comment by shift-eleven** [comment]
Thank you!
