### ISSUE TITLE
Can't retrieve currently playing song name...

### ISSUE THREAD

**Issue by Overflxw** [JohnnyCrazy/SpotifyAPI-NET#588]
I'm not sure if I am missing something here but there is no way for me to get the name of the currently playing song... 
![image](https://user-images.githubusercontent.com/77849687/113635400-75ad7800-9668-11eb-98a6-351e6c64cf2d.png)

**Comment by JohnnyCrazy** [comment]
It's inside `Item`

https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/iplayableitem

**Comment by Overflxw** [comment]
@JohnnyCrazy yeah I just found it lol, knew I was missing something. Thanks!
