### ISSUE TITLE
Image in FullTrack

### ISSUE THREAD

**Issue by Tengokuken** [JohnnyCrazy/SpotifyAPI-NET#600]
Is it possible to include an Images field containing the track's song picture in the response for FullTrack? Other response types (ie FullAlbum) contain Images, and Spotify's Tracks API also contains this field as well.

**Comment by JohnnyCrazy** [comment]
Hi @Tengokuken 

What do you mean with track song pictures? AFAIK and according to the documentation, the album object contains the `images`. You can also get those via `track.Album.Images`.

https://developer.spotify.com/documentation/web-api/reference/#object-trackobject
https://developer.spotify.com/documentation/web-api/reference/#object-simplifiedalbumobject

If you just see a `IPlayableItem` type, you can checkout this guide: https://johnnycrazy.github.io/SpotifyAPI-NET/docs/iplayableitem

**Comment by Tengokuken** [comment]
You're absolutely right, I misread the API response in Spotify's documentation. Thank you!
