### ISSUE TITLE
Link to migration guide in v6 release points to missing page

### ISSUE THREAD

**Issue by piksel** [JohnnyCrazy/SpotifyAPI-NET#609]
Link in [v6.0.0 release notes](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/6.0.0) for migrating from v5 to v6 links to "next" documentation at 
https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/5_to_6 (which does not exist)
instead of
https://johnnycrazy.github.io/SpotifyAPI-NET/docs/5_to_6

**Comment by JohnnyCrazy** [comment]
Thank you, fixed!
