### ISSUE TITLE
VB.NET | Request to create a functional code.

### ISSUE THREAD

**Issue by NaNonnI** [JohnnyCrazy/SpotifyAPI-NET#610]
Hi, Hope all of you doing well!
I found this API and I tried for the last 2 hours lol.
I just want to get the song title and artist of the current song playing ^^"

But I really don't know how to do it so if someone can Help me it can be.. REALLLYYYY cool <3

Thx everyone

**Comment by Nectura** [comment]
If still relevant, I just found out myself.

`CurrentlyPlaying = (FullTrack)(await client.Player.GetCurrentlyPlaying(new PlayerCurrentlyPlayingRequest())).Item`

**Comment by NaNonnI** [comment]
@Nectura Thanks!

Do you know how to make a Spotify Auth too ? 
It can be really helpfull!
*except if the line you give me don't need this lol*

**Comment by Nectura** [comment]
https://www.nuget.org/packages/AspNet.Security.OAuth.Spotify/

or a similar package

**Comment by NaNonnI** [comment]
I can't, I just can't do it.
HOW!

`Imports SpotifyAPI.Web

Public Class Menu_spotify
    Dim ClientID As String = "..."
    Dim ClientSecret As String = "..."
    Dim ClientURI As Uri = New Uri("http://localhost:5000")

    Private Function LoginSpotify()
        Dim SLoginRequest = New LoginRequest(ClientURI, ClientID, LoginRequest.ResponseType.Code)
        Dim Scope = {Scopes.PlaylistReadPrivate, Scopes.PlaylistReadCollaborative}
        Dim Uri = SLoginRequest.ToUri()
        Return Uri
        Console.WriteLine(Uri)
    End Function

    Private Async Function SetClientAsync(code As String) As Task
        Dim response = Await New OAuthClient().RequestToken(New AuthorizationCodeTokenRequest(ClientID, ClientSecret, code, LoginSpotify))
        Dim config = SpotifyClientConfig.CreateDefault().WithAuthenticator(New AuthorizationCodeAuthenticator(ClientID, ClientSecret, response))
        Dim client = New SpotifyClient(config)
        Dim CurrentlyPlaying As FullTrack = (Await client.Player.GetCurrentlyPlaying(New PlayerCurrentlyPlayingRequest())).Item
        testlabel.Text = "Nom du son actuel: " + CurrentlyPlaying.ToString
    End Function

    Private Sub Menu_spotify_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Console.WriteLine(SetClientAsync("access_token"))
        'LoginSpotify()
        Console.WriteLine(LoginSpotify)
        ReloadColors()
    End Sub

    Public Sub ReloadColors()
        Me.BackColor = My.Settings.AllBackColor
    End Sub
End Class`

**Comment by JohnnyCrazy** [comment]
Hi,

I don't give support for VB.NET questions from my side (Too unexperienced and not interested). However, if someone else stumbles upon this issue, they're of course free to provide a working example!
