### ISSUE TITLE
How to get more than 100 tracks in a playlist

### ISSUE THREAD

**Issue by KenthJ** [JohnnyCrazy/SpotifyAPI-NET#614]
spotify.Playlists.Get("playlistId"); only returns the first 100 tracks

How to get the next ones?

In an old thread a pagination helper was mentioned, but the link in there is dead, and I can't find any other info about this.

Any help is greatly appreciated.

**Comment by FrankBJensen** [comment]
Increment Offset by 100, until PUserTracks.Items.Count == 0

`Paging<PlaylistTrack<IPlayableItem>> pUserTracks = await spotify.Playlists.GetItems(id, new PlaylistGetItemsRequest { Offset = 0 });`

**Comment by KenthJ** [comment]
Thanks a lot, that solved the problem
