### ISSUE TITLE
Requests don't go through fiddler

### ISSUE THREAD

**Issue by CVertex** [JohnnyCrazy/SpotifyAPI-NET#63]
Hi,

I'm enjoying using this library! Thanks for making it. It's nicely written with good abstractions. Very simple to understand :smile: 

I've noticed that calls to api.spotify.com using this library aren't captured by Fiddler. I need fiddler to do some network reporting.
Does anyone have any idea why fiddler wouldn't pick these up?
Maybe something to do with proxy being null, or WebClient behaves differently to fiddler..

Thanks,
CVertex

**Comment by JimmyAppelt** [comment]
Try to set the proxy like so:
Instead of `Proxy = null;` to `Proxy = new WebProxy("127.0.0.1", 8888);`

**Comment by JimmyAppelt** [comment]
this worked for you @CVertex ?

**Comment by JohnnyCrazy** [comment]
Setting a proxy should work, yea. Just open it again if you have any questions @CVertex

**Comment by ersensen** [comment]
Hi,

We injected this nice library to our app via nuget. App is running behind the proxy. Is there a way to not set the proxy to null? Or do we have to get the source code into our project and remove the "Proxy = null;"s?

Thanks
