### ISSUE TITLE
BrowserUtil causes error with Xamarin

### ISSUE THREAD

**Issue by NoPlanNomad** [JohnnyCrazy/SpotifyAPI-NET#638]
When using BrowserUtil.open for the authentication a System.AggregateException occurs.
I'm using Xamarin.Forms and I'm testing on android.

using TryOpenAsync is a work around.

**Comment by RSvlad** [comment]
Hey, I also faced this problem and found a solution in using "Device.OpenUri(request.ToUri());"

**Comment by JohnnyCrazy** [comment]
Closing this, Xamarin should have built-in tools to open URLs like @RSvlad suggested!
