### ISSUE TITLE
"invalid access token" / "'This request requires user authentication.'"

### ISSUE THREAD

**Issue by dahanj95** [JohnnyCrazy/SpotifyAPI-NET#645]
Doesn't matter what I do, i get these errors. [This](https://www.reddit.com/r/webdev/comments/b0oaez/spotify_api_oauth_invalid_access_token/) link has interesting info regarding this issue might be in the library, consider looking at it.

I've placed my client id and secret like this

```
      var config = SpotifyClientConfig.CreateDefault();

            var request = new ClientCredentialsRequest(client_id, client_secret);
            var response = new OAuthClient(config).RequestToken(request);

            _spotify = new SpotifyClient(config.WithToken(response.Result.AccessToken));

            //_spotify = new SpotifyClient("BQAwnhNHMdvCeDyq87n0D0tiB96arySilifAe3JlCQeB54tZ7gT9Nbp");
```

doesn't matter which instance i call, it's not working. i'm trying to add an item to a playlist.

**Comment by JohnnyCrazy** [comment]
Please have a thorough look at https://johnnycrazy.github.io/SpotifyAPI-NET/docs/auth_introduction and https://johnnycrazy.github.io/SpotifyAPI-NET/docs/client_credentials

client credentials are **not** user authentication. While you create them with a logged in spotify account, they're not tied to your account and thus can't be used to query user related endpoints. Alternatives are listed [here](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/auth_introduction)
