### ISSUE TITLE
Response "Premium required" though my account is premium

### ISSUE THREAD

**Issue by coder0x0** [JohnnyCrazy/SpotifyAPI-NET#649]
Hey there!

I am having issues using the player controls (next, previous, play/pause, setRepeat and setShuffle) in C#.
My client authorizes successfully when I call my code on initialization but it fails when calling the command.
My account is part of a spotify premium family account.

Auth Code:
```
private void AuthSpotifyClient()
{
    try
    {
        SpotifyClientConfig config = SpotifyClientConfig.CreateDefault();
        ClientCredentialsRequest request = new ClientCredentialsRequest("clientId", "clientSecret");
        ClientCredentialsTokenResponse response = new OAuthClient(config).RequestToken(request).Result;
        spotify = new SpotifyClient(config.WithToken(response.AccessToken));
        Debug.WriteLine($"spotifyAPI successfully authorized");
    }
    catch (Exception ex)
    {
        Debug.WriteLine($"failed to authorize spotifyAPI: {ex.Message}");
    }
}
```

Example player command:
```
private async void PreviousTrackButton_Click(object sender, RoutedEventArgs e)
{
    bool skipped = await spotify.Player.SkipPrevious();
    Debug.WriteLine($"SkipPrevious: {skipped}");
}
```

Best regards

**Comment by JohnnyCrazy** [comment]
Please have a thorough look at https://johnnycrazy.github.io/SpotifyAPI-NET/docs/auth_introduction and https://johnnycrazy.github.io/SpotifyAPI-NET/docs/client_credentials

The player is a user based endpoint, so client credentials can't work.
