### ISSUE TITLE
Code Compile Issue

### ISSUE THREAD

**Issue by stuntguy3000** [JohnnyCrazy/SpotifyAPI-NET#65]
[c# noob, apologies]

I am wanting to compile the example so I can use it myself. 
However, I am recieving lots of these errors. Not sure if it relates to Nuget.

![image](https://cloud.githubusercontent.com/assets/1522389/11746508/676dfc88-a06e-11e5-9067-0d4ade9000fd.png)

Cheers

**Comment by JimmyAppelt** [comment]
@stuntguy3000 

Are you using Visual Studio 2015 ?

I suspect the errors come from the `$` that are used with the new Strings Interpolated in C# 6.0

[https://msdn.microsoft.com/en-us/library/dn961160.aspx](https://msdn.microsoft.com/en-us/library/dn961160.aspx)

**Comment by JohnnyCrazy** [comment]
We are using string-interpolation introduced in C# 6.
You will either have to update your .NET or your Visual Studio. I don't know if you need both or just one of them. 

Feel free to reopen if you have further questions, but updating should work fine :)

**Comment by stuntguy3000** [comment]
I am using Visual Studio '13, Will look into this. Cheers!
