### ISSUE TITLE
Question: How to reorder Playlists (not tracks inside a playlist)

### ISSUE THREAD

**Issue by KenthJ** [JohnnyCrazy/SpotifyAPI-NET#657]
Hi there

How do I reorder the playlists itself?  (not the tracks inside a playlist)

I can only find 'spotify.Playlists.ReorderItems()' which only seems to be used for reordering the tracks inside a playlist

Thanks a lot in advance

**Comment by JohnnyCrazy** [comment]
Please have a look at the issue template, questions should be asked in the discussion tab.
