### ISSUE TITLE
Unable to change volume

### ISSUE THREAD

**Issue by stuntguy3000** [JohnnyCrazy/SpotifyAPI-NET#66]
G'day again.

Whenever I reference setVolume a "Volume object creation failed" COMException is thrown. Music is playing, and other controls are fine. No stacktrace available appoligies. 

Any ideas?

**Comment by JimmyAppelt** [comment]
Yup that is due to a fact that its hooking to the wrong process. >there are more then one processes of spotify running at the same time. And the Correct one to couple is not always at the same place in the array of coarse.

Like in #50 i commented about this issue

> Going to need something like int pid = p.Where(o => o.MainWindowHandle != IntPtr.Zero).Select(o => o.Id).First(); because i get more processes back from the Process.GetProcessesByName method.
The correct Id to create the GetVolumeObject(pid) object is not always first in the array.

**Comment by stuntguy3000** [comment]
Ah right, damn. No worries :)

**Comment by JimmyAppelt** [comment]
Don't close it :smile: it has the need to be fixed :+1:

**Comment by stuntguy3000** [comment]
True :P

**Comment by Mrnikbobjeff** [comment]
I can not reproduce the issue with multiple processes on my Windows 10 Pro x64 system. Could you give me additional information such as os, architecture? And are multiple spotify windows open or why do you have multiple processes

**Comment by stuntguy3000** [comment]
Windows 10 Home premium x64 system, and only a single Spotify instance/process running.

**Comment by JimmyAppelt** [comment]
Wondows 10 Pro x64

* 1 x process from Apps and 
* 2 x process in background 

(so at least 3 processes called spotify.exe are running)

`int pid = p.Where(o => o.MainWindowHandle != IntPtr.Zero).Select(o => o.Id).First();`

Should get you the process that has a windowhandle (where the other once have not)

**Comment by JohnnyCrazy** [comment]
This seems like a windows 10 problem, not ran into this with windows 7.

Could you add your OS @stuntguy3000 ? Maybe this will give us some insights.

I will deploy a fix shortly/tomorrow

**Comment by Mrnikbobjeff** [comment]
I did not know that spotify can have background processes. Are they they when you start spotify or when are they started?

**Comment by JimmyAppelt** [comment]
@Mrnikbobjeff they are started together when starting spotify itself (and run in the background)

**Comment by stuntguy3000** [comment]
@JohnnyCrazy Windows 10, 64Bit, Home Premium.

**Comment by stuntguy3000** [comment]
Resolved ^

**Comment by racquemis** [comment]
This bug seems to be back. Unable to control volume using latest binary on Windows 10 with up-to-date spotify client.

**Comment by JimmyAppelt** [comment]
@racquemis did it work before ?

**Comment by racquemis** [comment]
I couldn't tell. I've started using the Api yesterday.
Everything works great except changing volume, muting and unmuting.

Also doesn't work on the older Windows Server 2012 R2 OS.

**Comment by JohnnyCrazy** [comment]
@racquemis Volume-Control is only possible on >Windows 7 ([code](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI/Local/SpotifyLocalAPI.cs#L204))

I can't reproduce it, Volume-Control is still working.

**Comment by racquemis** [comment]
Hmm strange, can't get it to work. Throws the CO
Mexception on all my win7 win10, server 2012 systems. It's not like the mute command is difficult to use, so I don't know what I'm doing wrong.

**Comment by JohnnyCrazy** [comment]
Does the full exception say anything in particular?

**Comment by racquemis** [comment]
Typical, now it suddenly works first try. Just did a recompile. Sorry for wasting your time. I have no idea why it suddenly starting working, but i won't complain ;)

**Comment by JohnnyCrazy** [comment]
Haha, no problem, I know this feeling. :sweat_smile: 
If you run into any other issues, feel free to open an issue
