### ISSUE TITLE
API rate limit exceeded (APITooManyRequestsException)

### ISSUE THREAD

**Issue by JackDjTom** [JohnnyCrazy/SpotifyAPI-NET#669]
Hi,
I want to load all my playlists and then load all songs from each playlist.
When I try doing this with the following code, I get the Exception: _SpotifyAPI.Web.APITooManyRequestsException: 'API rate limit exceeded_'.
```cs
var playlists = await _spotifyClient.PaginateAll(await _spotifyClient.Playlists.CurrentUsers(new PlaylistCurrentUsersRequest { Limit = 50 })
                                                                           .ConfigureAwait(continueOnCapturedContext: false));

foreach (var playlist in playlists)
{
    var songs = await _spotifyClient.PaginateAll(await _spotifyClient.Playlists.GetItems(playlist.Id, new PlaylistGetItemsRequest { Limit = 100 })
                                                                   .ConfigureAwait(continueOnCapturedContext: false));
}
```

How can I load all my playlists+songs without running into this exception?

**Comment by JohnnyCrazy** [comment]
Like benlane already explained, you need some kind of delay:

1. Use https://johnnycrazy.github.io/SpotifyAPI-NET/docs/retry_handling
2. Add some manual `Thread.Sleep`
