### ISSUE TITLE
New RefreshToken on AuthorizationCodeRefreshRequest

### ISSUE THREAD

**Issue by yepMad** [JohnnyCrazy/SpotifyAPI-NET#676]
According to the Spotify API, when requesting a new token using a RefreshToken, it is possible that the API will or may not return a new RefreshToken - I believe depending on the expiry date of your current refresh token. However, I haven't found a way to get this token or not through AuthorizationCodeRefreshRequest(), am I doing something wrong?

> A token that can be sent to the Spotify Accounts service in place of an authorization code. (When the access code expires, send a POST request to the Accounts service /api/token endpoint, but use this code in place of an authorization code. A new access token will be returned. **A new refresh token might be returned too**.)

https://developer.spotify.com/documentation/general/guides/authorization-guide/

**Comment by Banane9** [comment]
Came here with the same problem - it's been added to the class 27 days ago, but evidently not yet pushed to NuGet

**Comment by JohnnyCrazy** [comment]
Sorry for the delay, 6.2.2 is releasing with the included `RefreshToken` in the response

**Comment by Banane9** [comment]
Thanks Johnny!
