### ISSUE TITLE
GetTrack Not returning a value

### ISSUE THREAD

**Issue by ehcool** [JohnnyCrazy/SpotifyAPI-NET#69]
I used the example of code given on your website, But it does not seem to be filling my fulltrack object with any data. Here's my code

SpotifyWebAPI _webAPI = new SpotifyWebAPI()
            {
                UseAuth = false,
            };
            FullTrack track =  _webAPI.GetTrack("0eW4vkDVxqS4U60ExzsKhR");

**Comment by JimmyAppelt** [comment]
@ehcool thats should work just fine

The `id` that you are passing seems to be a non existing track. 

Try `1mvfvDZOybiEgS1ecJxt9W` for example.

**Comment by JohnnyCrazy** [comment]
Like @JimmyAppelt said, this track-ID isn't valid.
The Error-Object `track.Error` should be filled with some infos
