### ISSUE TITLE
Playlist total items does not match

### ISSUE THREAD

**Issue by ComeOutToPlay** [JohnnyCrazy/SpotifyAPI-NET#692]
I am using Net Core 5.0 with Spotify.API.Web v6.2.2 and when I do

`var page = await this.Client.Playlists.GetUsers(username);`

I see a total of 108 items. Please see this [Net Core Screen Capture](https://drive.google.com/file/d/1rOgHpe5EEVvTgY93uZ8MabN0N2ZorXhC/view?usp=sharing)

But when I do the same from the developer site at [Spotify Developer Console](https://developer.spotify.com/console/get-current-user-playlists/?limit=&offset=) I get 135 elements. Please see this [Spotify Developer Site Screen Capture](https://drive.google.com/file/d/12_BHn-htIynI5Joeunq3NcjkMv1L_0SO/view?usp=sharing)

I don't know why the difference. Could you give me some advice on this topic?

I also attach my Client definition:

```
        public SpotifyClient Client {get; set;}

         ...

        var config = SpotifyClientConfig.CreateDefault("my-key");
        var request = new ClientCredentialsRequest("my-client-id", "my-secret");
        var response = await new OAuthClient(config).RequestToken(request);
   
        this.Client = new SpotifyClient(config.WithToken(response.AccessToken));
```

**Comment by JohnnyCrazy** [comment]
Hi,

In the console your requesting the current users playlists, which also includes private ones. In the app, you only list the public playlists of some user.

If you want to access private user data, have a look at the authorization guide in the docs and open a discussion if you're stuck. Issues are primarily for bug reports.
