### ISSUE TITLE
Continuously getting "User not registered in the Developer Dashboard" auth error

### ISSUE THREAD

**Issue by svr333** [JohnnyCrazy/SpotifyAPI-NET#700]
## Description
Recently, after Spotify's new authentication updates regarding apps (you now have an App Status, which can be *Development Mode* or *Granted Quota Extension*) I started getting the error `User not registered in the Developer Dashboard`.

But first, some more info on my application, I have a simple *Code Authorization* Authentication with one app per user.
So before the user is able to use my product, they have to go to the Spotify Dashboard and create a new Dashboard App **on THEIR Spotify account,** provide my application with a Client Id and Client Secret and then they'll have a working product.

Now, for any new app made after the Spotify changes, authorization will not work and will fail with the error `User not registered in the Developer Dashboard`. However, with my old Dashboard App that I've had for over 2 years, it does not give this error, I'm assuming this is because it has *Granted Quota Extension* on that application.

This issue is rather annoying as all my users have manually get a Refresh Token now, which is not a nice solution.

## Resolving
I've tried resolving this issue but I was unsuccessful, I'm hoping it can be fixed from within this library.
Reason Im not reporting this to Spotify is because there are sites that still work with Code Auth and Im assuming it might just be an error in the library, currently I let my users use [This Site](https://getyourspotifyrefreshtoken.herokuapp.com/) to manually get a Refresh Token that they can provide my app with.

## Links
- [My Authorization Code](https://github.com/svr333/audio-band/blob/master/src/SpotifyAudioSource/SpotifyAudioSource.cs#L782)
  Do note this code still works for apps made before the Spotify change
- [Open Spotify Issue with same problem](https://community.spotify.com/t5/Spotify-for-Developers/User-not-registered-in-the-Developer-Dashboard-on-get-profile/td-p/5260021)

**Comment by JohnnyCrazy** [comment]
Hi,

If I read https://developer.spotify.com/community/news/2021/05/27/improving-the-developer-and-user-experience-for-third-party-apps/ correctly, you'll have to actually put the user ids of your app users into the dialog (there is a screenshot showing this). This is required for the new development mode I guess?

**Comment by svr333** [comment]
Well I've actually tried adding myself as an allowed user, but it still gives the same error
(I waited 10 minutes after adding the email before trying)

Normally it'd make sense to not add the user because you're the user that made the app.
And the other site also still works without adding myself as a user

**Comment by svr333** [comment]
All right, I'll open up my own issue and see how it goes, I'll close this

Though if you ever know why this error occurs I woud love to know why

**Comment by svr333** [comment]
I, uh, found the issue; Lets just say I had a facepalm moment

I tried to log in on my alt via an incognito browser, but when the actual verification came that says do you trust this application, I was still logged in on my main, therefore I didnt have permission
