### ISSUE TITLE
SpotifyClient.Player.SeekTo always sets the position to zero.

### ISSUE THREAD

**Issue by orestescm76** [JohnnyCrazy/SpotifyAPI-NET#704]
When I call SpotifyClient.Player.SeekTo(pos), no matter the input, always sets the playing position to zero, as if it was starting to play again. However, the call returns true as if it worked fine, but does not do the expected behaviour.
I tried to setting to a big value to see if it skips to the next song but again, it sets it to zero.

**Comment by JohnnyCrazy** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/API-Seek-to-Position-Bug-Broken/td-p/5288708

Seems like it's unrelated to the Lib

**Comment by orestescm76** [comment]
Well, that can happen. Thanks for the quick reply though, great work.
