### ISSUE TITLE
Player API .GetRecentlyPlayed() does not .NextPage() properly

### ISSUE THREAD

**Issue by benlane2003** [JohnnyCrazy/SpotifyAPI-NET#707]
When using the .NextPage() call on the List of PlayHistoryItems that is returned from the Player.GetRecentlyPlayed() call, the items returned are always empty, limiting me to only 50 PlayHistoryItems, I want to be able to .NextPage() them and get more. I'm assuming this is a bug because everything else does .NextPage() properly.

**Comment by JohnnyCrazy** [comment]
Hi,

How are you sure that you even have more than 50 recently played? Did you try to reconstruct the problem in the web api console? Pretty sure its not a bug on this project
