### ISSUE TITLE
GetSavedAlbums doesn't return album data

### ISSUE THREAD

**Issue by cwsterling** [JohnnyCrazy/SpotifyAPI-NET#71]
So, I'm playing around with the GetSavedAlbums and the method returns 16 items and when I look at the items returned, the items have an added time, but don't have any item data, it's null.

I would love to look through the code and see if I could work on fixing it or at least tracing through the path to see how the calls are being made, but I load up the source in visual studio 2013 and I can't compile it due to errors.

    public string GetAlbum(String id, String market = "")
        {
            if (String.IsNullOrEmpty(market))
                return $"{APIBase}/albums/{id}";
            return $"{APIBase}/albums/{id}?market={market}";
        }

my visual studio has an issue with the $ in return. I'm using .net4.5 any suggestions because I would love to work on seeing if I myself could possibly look into this and fix it

**Comment by JimmyAppelt** [comment]
@cwsterling for the `$` part check issue #65

**Comment by cwsterling** [comment]
@JimmyAppelt thanks, it's looking like it's because i'm running visual studio 2013 and not 2015. According to stackoverflow, i'm *supposed* to be able to install a nuget package and at least be able to compile it. visual studio will still bug out, but i'm supposed to at least be able to compile.

**Comment by JimmyAppelt** [comment]
@cwsterling i would upgrade at least to VS 2015 as its free anyway

For `GetSavedAlbums` ... are you doing Authenticated calls ?

**Comment by cwsterling** [comment]
@JimmyAppelt I'll take a look. I don't want to mess up too much stuff as I'm on 2013 for work.

As for the `GetSavedAlbums` yes, I'm using the following scopes as well.

`Scope = Scope.UserReadPrivate | Scope.PlaylistReadPrivate | Scope.UserLibrarayRead | Scope.UserReadPrivate `

**Comment by cwsterling** [comment]
fixed in pull request #72 the saved album was being deserizalized incorrectly.
