### ISSUE TITLE
Question: Get Tracks Through Local

### ISSUE THREAD

**Issue by RGoertz** [JohnnyCrazy/SpotifyAPI-NET#73]
Is there a way to get all tracks from spotify through the local API, or do i have to create an instance of web API and use that.

Just thought the local was already connected to spotify, Should be a way to get tracks from it.

**Comment by JohnnyCrazy** [comment]
Hi @RGoertz ,

Sorry for the late response. There is no way to receive tracks through the local API, you need to fetch it via the Web-API.
