### ISSUE TITLE
[QUESTION] Does the SpotifyLocalApi also include the lyrics?

### ISSUE THREAD

**Issue by Mrnikbobjeff** [JohnnyCrazy/SpotifyAPI-NET#74]
In the newest Spotify version you can see song lyrics by clicking on the lyrics button next to the trackbar. I know that Spotify uses an external API to get the lyrics for a track, so the SpotifyWebApi does not include a lyrics request. What I do not know is whether you can still get them locally somehow or not.

**Comment by JohnnyCrazy** [comment]
AFAIK the spotify local API doesnt cover this use-case. However, spotify is using a third-party lyrics-service called Musicxmatch which has an API. This API is also free with some limitations ([Some more infos](https://developer.musixmatch.com/mmplans))
