### ISSUE TITLE
Player.GetCurrentlyPlaying() = Reading the underlying data structure

### ISSUE THREAD

**Issue by Todd442** [JohnnyCrazy/SpotifyAPI-NET#747]
Nice work on the API!

This method returns a TrackInfo Object.. that's cool but when I need to interrogate it down to the PlayableItem level trying to retrieve the DurationMs attributes I can't seem to find the right approach. 

The data is coerced in VS when I look at pi... its listed as pi.DuractionMs but I can seem to figure out how I can access it.

                    PlayerCurrentlyPlayingRequest pcpr = new PlayerCurrentlyPlayingRequest();
                    var trackInfo = spotifyClient.Player.GetCurrentlyPlaying(pcpr);

                     var pi = trackInfo.Result.Item;

The code works. Just don't understand how to access those attributes.

BTW: I do have a stripped down version of a Xamarin Forms sample that I prepped for your examples lib if you'd like it.

**Comment by JohnnyCrazy** [comment]
Hi,

Does this help?

https://johnnycrazy.github.io/SpotifyAPI-NET/docs/iplayableitem

**Comment by JohnnyCrazy** [comment]
Feel free to reopen if you still have a question related to `IPlayableItem`
