### ISSUE TITLE
Does the SpotifyLocalAPI support the "Save to your music" feature?

### ISSUE THREAD

**Issue by eltoncezar** [JohnnyCrazy/SpotifyAPI-NET#75]
And if not, there's another way to implement it?

**Comment by JohnnyCrazy** [comment]
Hi @eltoncezar ,
The local api doesn't, but the Web-API can: [Library Docs](http://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyWebAPI/library/)

**Comment by eltoncezar** [comment]
Nice! Thanks.

**Comment by JohnnyCrazy** [comment]
No problem :smiley:
