### ISSUE TITLE
Recentlyplayed - IResponse missing Total value

### ISSUE THREAD

**Issue by WalterEbbers** [JohnnyCrazy/SpotifyAPI-NET#754]
Hi, 

I have been playing around with the GetRecentLyPlayed() call to get progress on how much % has been loaded and i am seeing that the "Total" value in the response is not there.  I have done something similar for Paging<T> (having a progress paginator) which works very nice and wanted to do the same for the CursorPaging<T>. 

According to the [recently played docs](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recently-played) the response should have a Total property, but when checking the IResponse data, i only see the following properties filled:
Items, Next, Cursors, Limit and Href. 

Is this something something on the Spotify API side? or is there something missing at the .NET side of the API?

**Comment by JohnnyCrazy** [comment]
Hi,

Sorry for the late response here. In this case, I think the docs are wrong as cursor paginations don't have a `total` field. A quick test on https://developer.spotify.com/console/get-recently-played/?limit=&after=&before= seems to confirm it

**Comment by WalterEbbers** [comment]
Hi, 

It's okay! Thnx for the reply about this!
