### ISSUE TITLE
Genres are not returned for albums

### ISSUE THREAD

**Issue by wellhat** [JohnnyCrazy/SpotifyAPI-NET#769]
I couldn't tell for sure if this is a web API bug or a bug in this .NET library, since I found discussions for it here https://github.com/spotify/web-api/issues/157.

Requesting several albums by IDs works, but the `Genres` property on `FullAlbum` is always an empty `List<string>`.

In the discusison it was mentioned that the request might work with the --genres parameter supplied.

**Comment by JohnnyCrazy** [comment]
If it's not delivered by the API, there is not much we can do...

I think the parameter is referring to libspotify, which does not solely use the web API.

Feel free to contact Spotify via their forum and post updates here, but closing for now since it's out of my hands.
