### ISSUE TITLE
Playlists.Get API should allow specifying fields, not force fields to empty list

### ISSUE THREAD

**Issue by ta264** [JohnnyCrazy/SpotifyAPI-NET#779]
See #470 and the fix in d73c87440038c463427e173265a36b0a839b769d

As far as I can tell you cannot actually set the `Fields` property as it's read only.  So it gets forced to an empty list and you get very little back.

I'm trying to update Lidarr to use 6.x but this is currently blocking for me.  Thanks in advance (and apologies if I'm doing something silly)!

**Comment by JohnnyCrazy** [comment]
The field is readonly, but you can still add fields with `model.Fields.Add(...)`

Although we may want to change the type to `List`, which would also allow to do `AddRange(otherList)`

**Comment by ta264** [comment]
Although having said that, that's only 4 calls, could be worse.  Thanks again.

**Comment by ta264** [comment]
In reference to #739, currently I think this setup means everything will be empty unless you explicitly ask for it.  I think it might be more sensible to find a way to not pass through fields unless it's got something in it.  If a user wants everything and has to manually enumerate all the possible fields that's pretty clunky.

**Comment by JohnnyCrazy** [comment]
I just tested this with the following call, and all fields are populated:

```
Paging<SimplePlaylist> playlists = await spotify.Playlists.CurrentUsers();
Debug.WriteLine(playlists.Items[0].Name);
```

![image](https://user-images.githubusercontent.com/3109892/180009081-919ada17-8fe7-4022-84ca-056c6e08f9cf.png)

**Comment by ta264** [comment]
Ah I hadn't spotted the #739 was using `CurrentUsers`.  That one sends a `PlaylistCurrentUsers` reques that doesn't let you set fields https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/b400d63087ce0eb78cd73b59a16cfd3fbf4f5907/SpotifyAPI.Web/Models/Request/PlaylistCurrentUsersRequest.cs

I think my concern above would still apply on the `Playlists.Get` methods, which will default to an empty field list I think.

**Comment by ta264** [comment]
Haha sorry, I think I must have some other bug in Lidarr causing me grief.  Sorry again for the noise, let me dig into it my side.

PS great work on the library, and (coming from 4.x) it does seem like a big improvement even if I have some wrinkles to work out 😁

**Comment by JohnnyCrazy** [comment]
No worries, feel free to ask more in a seperate discussion if stuff comes up :)
