### ISSUE TITLE
Create Method GetCallBack

### ISSUE THREAD

**Issue by LuckyCat17** [JohnnyCrazy/SpotifyAPI-NET#784]
Hi guys I try to use the SpotifyApi-NET with C#.

I'm having some problems, within the code authorization guide, the guide says that the method must be a non-asynchronous method but the visual studio keeps telling me that I can't use the AWAIT keyword, but if I delete the AWAIT keyword it won't I can no longer find the response.AccessToken property inside.
The Method:
![image](https://user-images.githubusercontent.com/62267498/182514051-b71f771e-f430-4ed6-8e6c-77157b26e2de.png)

The error:
![image](https://user-images.githubusercontent.com/62267498/182514167-0d9fec22-61ff-43de-9127-42ed64dc917d.png)

Could you help me solve this problem? In case you solved it how did you do it?

**Comment by ablizorukov** [comment]
Hi, not sure if that is still relevant, but I see two things you can try to make it work:
* add `async` after public modifier to the method definition `public async Task GetCallback()`
* wrap await new OAuthClient to single brackets. `(await new OAuthClient()).RequestToken(...)` or just create a new variable for OAuthClient and call RequestToken method separatelly.

**Comment by JohnnyCrazy** [comment]
This `GetCallback` is just a placeholder for whatever webserver you're using. Even if you copy-paste it into your application, it will not work out of the box. You can have a look at the examples for how a webserver is used in combination with OAuth.
