### ISSUE TITLE
Support getting the user's queue. 

### ISSUE THREAD

**Issue by gavinsteinhoff** [JohnnyCrazy/SpotifyAPI-NET#806]
Spotify now supports getting a user's queue with a get request to an endpoint the program is already using to add to the queue.

https://developer.spotify.com/documentation/web-api/reference/#/operations/get-queue

This support should be integrated.

**Comment by gavinsteinhoff** [comment]
This will be fixed by #807

**Comment by JohnnyCrazy** [comment]
Hi,

Thanks for the attached PR, gonna have a look at it today and will release right afterwards, sorry for the delay!
