### ISSUE TITLE
api.Library.RemoveAlbums() always returns SpotifyAPI.Web.APIException: Bad request

### ISSUE THREAD

**Issue by benlane2003** [JohnnyCrazy/SpotifyAPI-NET#828]
The method to remove a user's albums from Library doesn't seem to work. I created an IList<string>, added in an album's ID, created a LibraryRemoveAlbumsRequest with it and used it as a parameter for the call, but it always fails and returns a Bad request exception.
I tried using the same Album's ID in the Spotify [console](https://developer.spotify.com/console/delete-current-user-saved-albums/) and this successfully removes the album from my account.
I am using SpotifyAPI Web 6.2.2 net standard 2.0

**Comment by JohnnyCrazy** [comment]
Seems like they ignore their own docs again 🤷🏼 It works if you send the IDs via query parameter, but the JSON body parameter does not...

https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-albums-user

Will be fixed in the next release
