### ISSUE TITLE
api.Library.RemoveTracks() keeps returning Bad Request

### ISSUE THREAD

**Issue by benlane2003** [JohnnyCrazy/SpotifyAPI-NET#829]
It seems like RemoveTracks() is having the same problem as [this issue](https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/828) I created last night. Getting Bad Request same as the RemoveAlbums call. What's strange is these calls used to work just fine and it seems like only recently has this started happening. Maybe Spotify changed something.

**Comment by JohnnyCrazy** [comment]
K, then this is definitely an upstream issue...

https://community.spotify.com/t5/Spotify-for-Developers/Library-Remove-IDs-supplied-in-body-result-in-quot-Bad-Request/m-p/5459939#M7079

**Comment by JohnnyCrazy** [comment]
Will switch them to query parameters as well, as spotify is unresponsive, fixed by c5485a7183fc4c48b7a419975cdea6c46c88a600
