### ISSUE TITLE
UTF-8 Requests

### ISSUE THREAD

**Issue by S3NS4Ti0N** [JohnnyCrazy/SpotifyAPI-NET#83]
Please change request/response encoding to UTF-8

Here an album for reference : https://api.spotify.com/v1/albums/3IQOfLuZTVJY7QWvQohQjV

**Comment by JohnnyCrazy** [comment]
Executing this API-Call in Chrome or in Postman always results in wrong UTF8 characters, although the charset is set to UTF8. Are you sure the Spotify-API supports those characters at all?

Also, we [already use UTF8](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/ca4bd1edaf444e58cb77a7fa07b3741829a5e4cc/SpotifyAPI/Web/SpotifyWebClient.cs#L17)

**Comment by S3NS4Ti0N** [comment]
Then I dont understand, why the console window show these chars as "??".

**Comment by JohnnyCrazy** [comment]
Did you look at this [SO Question](http://stackoverflow.com/questions/5750203/how-to-write-unicode-characters-to-the-console)?

In [VS it looks](http://i.imgur.com/YtSYfMu.png) the same as in [spotify](https://open.spotify.com/album/3IQOfLuZTVJY7QWvQohQjV) it.

**Comment by erinxocon** [comment]
Can confirm what @JohnnyCrazy is saying.

**Comment by JohnnyCrazy** [comment]
@S3NS4Ti0N Reopen/create a new issue if you still have issues :)
