### ISSUE TITLE
Spotify.Tracks.GetSeveral method doesn't verify if a trackId is valid

### ISSUE THREAD

**Issue by x0rld** [JohnnyCrazy/SpotifyAPI-NET#834]
if you call the method with a List<string> with random data inside it will return a list of null

is it normal there is no verification in this method ?

**Comment by JohnnyCrazy** [comment]
Hi,

There is no way to check if a spotify id is valid or not, at least it's not provided by spotify. So the Client can't do any validations

**Comment by x0rld** [comment]
but why there is something which warn me it's a wrong id on Spotify.Tracks.Get ? 
![image](https://user-images.githubusercontent.com/45242856/205174724-335d2ab1-c674-4b4f-8ccf-11911d2c5b2f.png)
