### ISSUE TITLE
How do I replace token without creating new instance?

### ISSUE THREAD

**Issue by dahanj95** [JohnnyCrazy/SpotifyAPI-NET#836]
The only way to use the token is to pass it to the ctor of the `SpotifyClient` instance, therefor I have to recreate a new instance every time previous token expires. 

Why is this designed this way? Could we get a method to easily replace an expired token?

**Comment by g4solio** [comment]
After reading the code and the (Spotify) docs I assume that these design choice has been made for a strong reason:
The Client Credential flow ( the one I assume you refer to ) doesn't include a refresh logic.
So by Spotify design if you have a new Client Credential access token it means you re-logged and it make sense that also the instance of the SpotifyClient should be new.

This idea is strengthened by the fact that the other Authentication classes have the renew logic.

pls refer to the Spotify docs:  https://developer.spotify.com/documentation/general/guides/authorization/

**Comment by dahanj95** [comment]
Thank you for the explanation, I am closing this case.
