### ISSUE TITLE
help for integrating the c# api to wpf application

### ISSUE THREAD

**Issue by malembetirick** [JohnnyCrazy/SpotifyAPI-NET#84]
i have an issue, to manage thread in my wpf application by integrating your spotify api, i see that your api is only defined for c# application and .net.

**Comment by JohnnyCrazy** [comment]
I'm using this API inside a WPF-App myself, what's your problem exactly ?

**Comment by malembetirick** [comment]
it's good, i already correct my bug, but i wanna know if in the local api, there is a method to skip randomly songs by genre or artist. Thank u

**Comment by malembetirick** [comment]
Skip a song based randomly on its genre or artist.
2016-05-23 17:02 GMT+02:00 Jonas Dellinger <notifications@github.com>:

**Comment by JohnnyCrazy** [comment]
Mh, I don't think you can get the acutal genre of a track with the web-api, so no, this isn't possible @malembetirick

**Comment by fabiangigler** [comment]
Hi! 

I've  got some new pizza recipe for you, you should try it, more info here <http://have.barryfreas.com/lnajhrtn>

Wishes, fgigler
