### ISSUE TITLE
How to get currently playing song?

### ISSUE THREAD

**Issue by daort** [JohnnyCrazy/SpotifyAPI-NET#853]
Hello everyone!

This is my code. It is quite urgent because we are doing this for a school project. 

![Screenshot](https://user-images.githubusercontent.com/91456685/215746408-133577a4-def3-4e32-aa9b-455ab2046bb7.png)

Please help us. Thanks in advance

**Comment by daort** [comment]
I can't find anything in the documentation. I even used chat gpt to search for the documentation for the correct way to get the name of the currently playing song but the object current.Item doesn't have a .name property. I cannot get the track name no matter what I try.

**Comment by JohnnyCrazy** [comment]
Hi,

This page should have the solution 

https://johnnycrazy.github.io/SpotifyAPI-NET/docs/iplayableitem
