### ISSUE TITLE
CLI - Persistent Config Example macOS issue "Address already in use"

### ISSUE THREAD

**Issue by dscarr3000** [JohnnyCrazy/SpotifyAPI-NET#868]
I've found an issue with the CLI - Persistent Config Example when used on macOS. The web server callback isn't working by default, it appears that macOS now uses port 5000 for its AirPlay Receiver. If you change the port used in the example it works fine, but by default it won't work.

Source: [https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c](https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c)

**Comment by JohnnyCrazy** [comment]
Yea 5000 is a bad port, will try to change port in all the examples + docs.
