### ISSUE TITLE
CustomHTML Example not compiling

### ISSUE THREAD

**Issue by ZeeSarp** [JohnnyCrazy/SpotifyAPI-NET#878]
![image](https://github.com/JohnnyCrazy/SpotifyAPI-NET/assets/51046600/e27d615c-fc99-406d-bfbe-9445e07ee1bc)
If I am not mistaken, there is a "Scopes." missing before UserReadEmail.

**Comment by JohnnyCrazy** [comment]
Hi,

This examples uses `using static SpotifyAPI.Web.Scopes;` at the top, which makes all Scopes directly available, without the need to prepend `Scopes.`

I'm also able to compile it locally with the specified `net7.0`. Feel free to open a discussion if there is something unclear.
