### ISSUE TITLE
Get and Set Spotify Volume fails on Windows 10

### ISSUE THREAD

**Issue by XXLJack** [JohnnyCrazy/SpotifyAPI-NET#88]
Not sure if this has anything to do with Windows 10, but on my system, `GetSpotifyVolume` always returns 0 and `SetSpotifyVolume` does nothing except throwing a `System.Exception` when Spotify is not running.

**Comment by JohnnyCrazy** [comment]
Hi

Sorry for the late response. Are you running your app as admin?
There was also a Win10 in #66 , but it got resolved.

**Comment by XXLJack** [comment]
Hey, no problem!

That indeed fixed the issue, sorry for the hassle. Would be nice if some kind of exception got thrown in case this happens.
But anyways thank you, this has been bugging me for days (pun not intended).
