### ISSUE TITLE
Forbidden error with Library.GetTracks datas

### ISSUE THREAD

**Issue by mucahitimre** [JohnnyCrazy/SpotifyAPI-NET#887]
Hello, I bought error "Forbidden" when get Library.GetTracks datas. Any ideas why I'm getting this error?

My code:
![image](https://github.com/JohnnyCrazy/SpotifyAPI-NET/assets/12904452/666cc9bc-aabc-4561-96bf-12be91763616)

**Comment by JohnnyCrazy** [comment]
`ClientCredentials` does not support accessing user-based data.

See table of https://johnnycrazy.github.io/SpotifyAPI-NET/docs/auth_introduction

**Comment by mucahitimre** [comment]
Thanks for answer.
