### ISSUE TITLE
Cancellation token in PaginateAll method

### ISSUE THREAD

**Issue by DomerKek** [JohnnyCrazy/SpotifyAPI-NET#896]
Is there opportunity to add CancelationToken argument to PaginateAll methods (class SpotifyClient)?

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web/Clients/SpotifyClient.cs#L87-L121

Thanks!

**Comment by JohnnyCrazy** [comment]
Fixed by #907 , will be released soonish
