### ISSUE TITLE
Local files in FullPlaylist bug

### ISSUE THREAD

**Issue by marciweleq** [JohnnyCrazy/SpotifyAPI-NET#926]
When trying to load FullPlaylist with local file it throws error.

JsonReaderException: Error reading integer. Unexpected token: StartObject. Path 'duration_ms', line 1, position 32127.

**Comment by a0w89fwa0f** [comment]
> When trying to load FullPlaylist with local file it throws error.
> 
> JsonReaderException: Error reading integer. Unexpected token: StartObject. Path 'duration_ms', line 1, position 32127.



> Was this something that started to happen suddenly, without changing the code?
> 
> Do you have any problems reading FullArtist?

I'm also having a similar issue,

Newtonsoft.Json.JsonReaderException: Input string '5190.0' is not a valid integer. Path 'followers.total' line 1 position 125

My code hasn't changed and the program was working fine until recently.

**Comment by marciweleq** [comment]
> Was this something that started to happen suddenly, without changing the code?
> 
> Do you have any problems reading FullArtist?

The issue started happening suddenly without any changes in the code. I believe it might be due to the difference in the structure of 'duration_ms' property between a normal track:
```
(...)
"duration_ms": 321560,
(...)
```

and local track:

```
(...)
"duration_ms": {
            "totalMilliseconds": 188000
          },
(...)
```

**Comment by rogamaral** [comment]
> > When trying to load FullPlaylist with local file it throws error.
> > JsonReaderException: Error reading integer. Unexpected token: StartObject. Path 'duration_ms', line 1, position 32127.
> 
> > Was this something that started to happen suddenly, without changing the code?
> > Do you have any problems reading FullArtist?
> 
> I'm also having a similar issue mine is with FullArtist
> 
> Newtonsoft.Json.JsonReaderException: Input string '5190.0' is not a valid integer. Path 'followers.total' line 1 position 125
> 
> My code hasn't changed and the program was working fine until recently.

So I'm not the only one.
Therefore, it appears to be a problem with the Spotify API.
After some further investigation, I found that, in addition to Followers.Total, this also happens with Image.Width and Image.Height.

**Comment by marciweleq** [comment]
> > > When trying to load FullPlaylist with local file it throws error.
> > > JsonReaderException: Error reading integer. Unexpected token: StartObject. Path 'duration_ms', line 1, position 32127.
> > 
> > 
> > > Was this something that started to happen suddenly, without changing the code?
> > > Do you have any problems reading FullArtist?
> > 
> > 
> > I'm also having a similar issue mine is with FullArtist
> > Newtonsoft.Json.JsonReaderException: Input string '5190.0' is not a valid integer. Path 'followers.total' line 1 position 125
> > My code hasn't changed and the program was working fine until recently.
> 
> So I'm not the only one. Therefore, it appears to be a problem with the Spotify API. After some further investigation, I found that, in addition to Followers.Total, this also happens with Image.Width and Image.Height.
> 
> They are **int** but are being returned as **float/double**.
> 
> I created a topic on [Discussions](https://github.com/JohnnyCrazy/SpotifyAPI-NET/discussions/925)

The workaround I found is removing the package via NuGet and downloading it's files. Then I modify the fields accordingly. Now authentication doesn't really work, but I believe it's issue on my side and I'm doing something wrong.

**Comment by JohnnyCrazy** [comment]
The first time we saw this was even earlier: https://github.com/Viperinius/jellyfin-plugin-spotify-import/issues/18

I don't find any official announcments by spotify on this change, were you able to find any communication by them? I'm kinda curious if it's a bug or "new feature"

Another link: https://community.spotify.com/t5/Spotify-for-Developers/duration-ms-includes-nonsense-JSON/m-p/5753768

**Comment by Lewis-Fam** [comment]
> > > > When trying to load FullPlaylist with local file it throws error.
> > > > JsonReaderException: Error reading integer. Unexpected token: StartObject. Path 'duration_ms', line 1, position 32127.
> > > 
> > > 
> > > > Was this something that started to happen suddenly, without changing the code?
> > > > Do you have any problems reading FullArtist?
> > > 
> > > 
> > > I'm also having a similar issue mine is with FullArtist
> > > Newtonsoft.Json.JsonReaderException: Input string '5190.0' is not a valid integer. Path 'followers.total' line 1 position 125
> > > My code hasn't changed and the program was working fine until recently.
> > 
> > 
> > So I'm not the only one. Therefore, it appears to be a problem with the Spotify API. After some further investigation, I found that, in addition to Followers.Total, this also happens with Image.Width and Image.Height.
> > They are **int** but are being returned as **float/double**.
> > I created a topic on [Discussions](https://github.com/JohnnyCrazy/SpotifyAPI-NET/discussions/925)
> 
> The workaround I found is removing the package via NuGet and downloading it's files. Then I modify the fields accordingly. Now authentication doesn't really work, but I believe it's issue on my side and I'm doing something wrong.

I am a little late to the party. I've also removed the package and modified the code. I am not all the failure with this library, but adding a JSON Converter seems to have resolved my issues. I am doing further testing and trying to identify all the properties to modify before submitting a pull...

```c#
public class FullArtist 
{  
     [JsonConverter(typeof(DoubleToIntConverter))]
     public int Popularity { get; set; }
}
    
public class DoubleToIntConverter : JsonConverter<int>
{
    public override void WriteJson(JsonWriter writer, int value, JsonSerializer serializer)
    {
        writer.WriteValue(value);
    }

        public override int ReadJson(JsonReader reader, Type objectType, int existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        return Convert.ToInt32( reader.Value);
    }
}
```

**Comment by JohnnyCrazy** [comment]
In my latest testing, local files had the correct `durationMs` `int` type. If you guys still see this, please provide a playlist id or similar so I can reproduce it. If you don't want to paste the playlist ID publicly, you can also send it via mail.
