### ISSUE TITLE
Feature: Provide "html_description" on SimpleEpisode and FullEpisode

### ISSUE THREAD

**Issue by cultpodcasts** [JohnnyCrazy/SpotifyAPI-NET#944]
Can we add the property "html_description" returned from Spotify-endpoints for v1/shows/{id}/episodes and /v1/episodes/{id}

The Description member populated from the "description" property supplied by these endpoints strips html-tags which means the text is often malformed.

For example; html_description will return text such as:
`.... lorem<br />ipsum ...`

The description field returns text such as: 
`... loremipsum ...`

The result is the text provided by the Description member of SimpleEpisode and FullEpisode is often not what was intended when entered by the author. 

I am prepared to create a pull-request if this is the correct process to follow. I am also prepared to fork if this is outside the scope of the project,

The package is being used to drive the cultpodcasts.com website which is proving helpful to academic researchers. Your package has been very helpful in making this happen. Thank you

**Comment by JohnnyCrazy** [comment]
Hey,

This was a small addition, so I included it in [SpotifyAPI Web 7.1.1](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/untagged-81e8274ea082902453aa).

Let me know if everything checks out!
