### ISSUE TITLE
BUG: PlaylistClient.ReplaceItems() checking for HttpStatusCode.Created when Spotify returns HttpStatusCode.OK

### ISSUE THREAD

**Issue by goldfish1974** [JohnnyCrazy/SpotifyAPI-NET#972]
When using PlayListClient.ReplaceItems(playlist.Id, new PlaylistReplaceItemsRequest(uris),

the return code from the ReplaceItems returns false when the HttpResponse is OK from the Spotify endpoint. In the code, it makes the assumption that calling ReplaceItems returns created whereas the documentation, and in practice it returns OK.

As a result, you cannot trust the return value but must resort to looking at SpotifyClient.LastResponse.StatusCode.

The bug is here: 
- https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/1281ce8732b10fa2c3e7b264c9cc33a983a7ab60/SpotifyAPI.Web/Clients/PlaylistsClient.cs#L105

and the Spotify Documentation for the value return values is here:
- https://developer.spotify.com/documentation/web-api/reference/reorder-or-replace-playlists-tracks

To fix the issue, most likely the line mentioning where the bug is just needs to be updated to OK.

**Comment by JohnnyCrazy** [comment]
Hey,

Indeed, that endpoint should also return a [snapshot response](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web/Models/Response/SnapshotResponse.cs). Might be able to fix this on the weekend, happy to accept PRs too before that!
