### ISSUE TITLE
Exception thrown when interacting with Player

### ISSUE THREAD

**Issue by As2piK** [JohnnyCrazy/SpotifyAPI-NET#985]
Hello,

Everytime I try to interact with the Player in SpotifyClient.Player, I get some JSON exception. The error is always different, but always follows this pattern :

`JsonReaderException: Unexpected character encountered while parsing value: M. Path '', line 0, position 0.`
`JsonReaderException: Unexpected character encountered while parsing value: n. Path '', line 0, position 0.`
`JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.`

This appends either when I try to add a track to the queue, try to play/pause Spotify, try to skip to the next song,...

```
            PlayerAddToQueueRequest r = new PlayerAddToQueueRequest("spotify:track:" + track.ID);
            await spotifyClient.Player.AddToQueue(r);
```

`await spotifyClient.Player.PausePlayback();`

`await spotifyClient.Player.SkipNext();`

Am I doing something wrong?

Thank you

**Comment by JohnnyCrazy** [comment]
#980 (literally the only issue open)
