### ISSUE TITLE
Cannot Connect to Spotify Client

### ISSUE THREAD

**Issue by JKI12** [JohnnyCrazy/SpotifyAPI-NET#99]
I pulled down the source code and built the example and got the message box that states it cannot connect to my Spotify client, I then downloaded the Spofy program that uses the API and that also gives me the same message.

Is this issue just me?

**Comment by erinxocon** [comment]
Did you only build the example or he whole
Project?

**Comment by JKI12** [comment]
@erinxocon Thanks for your reply, I built the whole solution. I also downloaded the Spofy program that is listed in the repo to be using the Api and that returns same message upon launch.

**Comment by JohnnyCrazy** [comment]
Hi, are you using any anti-virus software like avg or Bitdefender? Is the spotify client running in the background?

**Comment by JKI12** [comment]
@JohnnyCrazy I do have avg, the anti-virus is running in the foreground.

Shall i disable the anti-virus and report back with the results?

**Comment by JimmyAppelt** [comment]
@JKI12 it's not said it will work when you only disable the anti virus. 

In case you want to test it out, remove the antivirus from you're system restart and try.
(It would be awesome if you test this out, because i have the same issue - on my machine it works fine without anti virus installed, it only happens on some anti virus softwares. To my knowledge AVG or Bitdefender have this issue)

**Comment by JKI12** [comment]
@JimmyAppelt So yeah upon disabling AVG the program will work. So @JohnnyCrazy is there anything process or anything I should add to AVG whitelist to allow the api to function but not disabling my antivirus

**Comment by JimmyAppelt** [comment]
@JKI12 unfortunately we don't have any solution yet. 

The antivirus says that the header of the response from spotify is basically wrong and blocks it. So initially it is spotify's problem.

Since the library is not official ...  we can only try to find a solution ...

**Comment by JKI12** [comment]
@JimmyAppelt Ok Thanks :smile:

**Comment by JKI12** [comment]
@JimmyAppelt Upon some scouting around, Adding the host with the port inside source code to AVGs url exception list allows its to connect, this is a temp solution for anyone else having this issue

**Comment by JimmyAppelt** [comment]
@JKI12  Could you give an example, screenshot or similar (that would be awesome) ?

**Comment by JKI12** [comment]
@JimmyAppelt This is the exception I added to AVG
![avgexample](https://cloud.githubusercontent.com/assets/15194063/17821861/bdb78976-664b-11e6-9c47-05eb12ac5f2e.png)

**Comment by JimmyAppelt** [comment]
@JKI12 thank you ! Will do a test this weekend on Bitdefener to

**Comment by JohnnyCrazy** [comment]
Thanks for the heads up @JKI12

Once we figure it out what's the exact problem, we could maybe contact spotify. 

@JimmyAppelt 
The other issue is still open, would love to hear your results +1
