### ISSUE TITLE
You must add a reference to assembly 'System.Runtime, Version 7.0.0.0'

### ISSUE THREAD

**Issue by herebecush** [JohnnyCrazy/SpotifyAPI-NET#995]
Hi there,

I've been trying to implement your package but have hit a blocker.

### Environment
- Windows 11
- .NET version 7.0.401
- .NET Framework64 version 4.7.2

### Approach
1. I've downloaded the packaged `.dll` file from the `SpotifyAPI.Web-net7.0` zip on the releases page
2. The package is correctly referenced in my code using `using SpotifyAPI.Web` with the .dll file added as a reference
3. I'm trying to use the [Request Token On-Demand](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/client_credentials/#request-token-on-demand) approach of the Client Credentials auth flow
4. The code running this approach is as follows:
```
string spotifyClientID		= Environment.GetEnvironmentVariable( "SB_SPOTIFY_ID" );
string spotifyClientSecret	= Environment.GetEnvironmentVariable( "SB_SPOTIFY_SECRET" );
		
if( ( null == spotifyClientID ) || ( null == spotifyClientSecret ) ){
	// Some error reporting omitted here
}else{
	var config = SpotifyClientConfig.CreateDefault().WithAuthenticator( new ClientCredentialsAuthenticator( spotifyClientID, spotifyClientSecret ) );
	// Another step here using new SpotifyClient( config );
}
```

### Issue
I've left out some of the particulars above to keep the code short, but that's how I'm using it. When I compile this code, I receive the following error 3x on the `var config` line, and once more on the `new SpotifyClient( config );` line:

`error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

From my past experience with class libraries etc. this is an issue with the .dll and not with my code (I'm using `System` at the top of the code, so there's not a directive missing there). Hopefully I've just missed something somewhere, but the moment I remove the SpotifyAPI-NET functions from my code the error goes away.

Thanks in advance

Cush

**Comment by herebecush** [comment]
Hi, any luck with this yet?

Thanks

**Comment by herebecush** [comment]
Second bump

Looks like this repo could be a good package, but if you're not sure how to fix this issue I can go a more manual route with my Spotify integration, it'd just be nice to know either way

**Comment by JohnnyCrazy** [comment]
Hi,

This is very likely not related to the library but your project setup. Did you download the correct library version for your specific .NET version? Please try a clean setup and also check if you can use nuget to install the package.

**Comment by herebecush** [comment]
Hi there,

Unfortunately it's not related to the environment. I can use packages within the System.Runtime space, it's just erroring when this package attempts to do it.

Also I made my own package which had this issue and I can confirm this error happens when it's a package throwing the error, not the overall environment.

Thanks

**Comment by JohnnyCrazy** [comment]
Here are my steps trying to reproduce this:

Create a new project with net7.0
```
dotnet new console -f net7.0
```

Download the DLLs manually and add the following to the csproject
```xml
    <Reference Include="SpotifyAPI.Web">
      <HintPath>./SpotifyAPI.Web.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>./Newtonsoft.Json.dll</HintPath>
    </Reference>
```

Update Program.cs
```csharp
using SpotifyAPI.Web;

var config = SpotifyClientConfig.CreateDefault().WithAuthenticator(new ClientCredentialsAuthenticator("CLIENT_ID", "CLIENT_SECRET"));
var api = new SpotifyClient(config);

var album = await api.Albums.Get("4aawyAB9vmqN3uQ7FjRGTy");
Console.WriteLine(album.Name);
```

And run it, showing that it works.
```
❯ dotnet run
Global Warming
```

It seems like you're convinced it's an issue with the library, so feel free to remove the library and go the manual route.

**Comment by herebecush** [comment]
Hi Johnny,

I'm convinced because it is, but the manual route is fine. Thanks for trying anyway!

Thanks

**Comment by herebecush** [comment]
Hello again!

Humility where it's needed... my apologies; this was _not_ your package. Once I manually added a reference to the `System.Runtime.dll` file in my .NET Framework folder to my references list this seems to work.

Honestly I didn't expect this to need to be a manual step, and the last time I had this issue it was to do with the third-party package, but I guess not all problems have the same solution... as a long-term dev I should probably know that by now!

Anyway, thanks for helping me debug this and sorry for falsely accusing the package!

Thanks

**Comment by JohnnyCrazy** [comment]
No worries, glad you found the issue and were able to resolve it! 👍
