### ISSUE TITLE
Problem deserialising "shows" that are "audiobooks"

### ISSUE THREAD

**Issue by cultpodcasts** [JohnnyCrazy/SpotifyAPI-NET#997]
If I use the GetEpisodes method on SpotifyAPI.Web.IShowsClient where the "show" is an "audiobook" the client throws a Newtonsoft.Json.JsonSerializationException with message "Error converting value "chapter" to type 'SpotifyAPI.Web.ItemType'"

I am working around this but it might be helpful to tolerate this Spotify-type in the JSON.

An example "show-id" that is an audio-book is "0witfebPufGbHK5itHFcRb" (Edit: using the "GB" market)

**Comment by JohnnyCrazy** [comment]
Hi,

Is audiobook something new? Never knew they introduced that.

I'm trying some API endpoints on the web playground of the API, and I'm unable to get any useful responses for chapters/audiobooks. They all 404 for me, which might be related to my market? (DE = germany). 

Can I ask which market/country you're requesting from?

**Comment by JohnnyCrazy** [comment]
Alright, was able to get audiobooks and chapters working by using credential auth and the US market. We need to add proper support for the new types "audiobook" and "chapter"

**Comment by cultpodcasts** [comment]
It would have been "GB" in the example case case. Sorry for omitting that. Thanks for picking this up and on a Sunday too! Really appreciate it.

**Comment by JohnnyCrazy** [comment]
Published as part of `7.2.0`!

**Comment by cultpodcasts** [comment]
Verify this fixes it. I'm interested in exploring this new feature! Thank you so much!
